firebase/genkit

- js/plugins/vertexai/src/evaluation.ts
- js/plugins/vertexai/src/evaluator_factory.ts
At some point, we should rely on the generated API client. In the short term, this will hopefully prevent issues like we saw before.
> Add strong response types for vertex evaluators

- js/core/src/tracing/instrumentation.ts
- js/flow/src/flow.ts
This follows the [recommendations](https://opentelemetry.io/docs/specs/semconv/exceptions/exceptions-spans/#recording-an-exception) of Open Telemetry and will solve two outstanding issues for us.
1. Currently stacktraces are not appearing in Cloud Trace.
2. We need a nice normalized `message` and `stacktrace` for the dev ui.
```
"status": {
"code": 2,
"message": "Error: Got an error!"
},
"timeEvents": {
"timeEvent": [
{
"time": 1714531849038.1628,
"annotation": {
"attributes": {
"exception.type": "Error",
"exception.message": "Got an error!",
"exception.stacktrace": "Error: Got an error!\n    at /Users/michaeldoyle/repos/src/genkit/js/samples/dev-ui-gallery/lib/main/flows.js:148:23\n    at Context.<anonymous> (/Users/michaeldoyle/repos/src/genkit/js/flow/lib/context.js:71:27)\n    at …
```
> Use span's recordException to record Errors

- docs/plugins/vertex-ai.md
- js/plugins/vertexai/src/evaluation.ts
- js/plugins/vertexai/src/evaluator_factory.ts
And make changes to reduce boilerplate.
> Add Vertex AI fluency metric

- docs/dotprompt.md
- docs/prompts.md
- js/ai/src/index.ts
- js/ai/src/prompt.ts
- js/dotprompt/src/index.ts
- js/dotprompt/src/prompt.ts
- js/dotprompt/src/registry.ts
- js/dotprompt/tests/prompt_test.ts
- js/samples/coffee-shop/src/index.ts
- js/samples/dev-ui-gallery/src/main/prompts.ts
- js/samples/menu/src/01/prompts.ts
- js/samples/menu/src/02/flows.ts
- js/samples/menu/src/02/prompts.ts
- js/samples/menu/src/03/prompts.ts
- js/samples/menu/src/04/prompts.ts
- js/samples/menu/src/05/prompts.ts
- js/samples/menu/src/index.ts
- js/samples/prompt-file/prompts/story.prompt
- js/samples/prompt-file/src/index.ts
- js/samples/rag/src/prompt.ts
This PR lifts prompts into a core Genkit action and facilitates paths to supporting alternative prompting approaches and/or templating systems. It also tweaks Dotprompt somewhat to interact with the new structure.
- Moving definePrompt into ai package
- Reimagining dotprompt to follow the new contract
- Adding renderPrompt veneer to facilitate using prompts in code
- Updating tests and samples to use defineDotprompt.
- Adding new docs for prompts and updating dotprompt
> Lifting definePrompt to genkit core

- docs/plugins/vertex-ai.md
- js/plugins/vertexai/src/evaluation.ts
Also, remove metric specific validation on datapoint fields. Instead, rely on API calls to fail if the input is missing a field.
> Add vertex ai summarization metrics

- go/ai/generator.go
- go/genkit/dotprompt/genkit.go
- go/samples/coffee-shop/main.go
Also add some helper methods to simplify the sample code.
> [Go] add coffee-shop sample

- go/genkit/tracing.go
Use the same naming scheme for the dev file trace store
that the javascript uses.
> [Go] name dev trace store dir like js

- js/ai/src/model.ts
- js/core/src/action.ts
- js/core/tests/action_test.ts
Action now have middleware support. Removed models specific implementation, models now use common middleware.
Ex: 
```ts
const act = action({
name: 'foo',
inputSchema: z.string(),
outputSchema: z.number(),
use: [
async (input, next) => await next(input + 'middle1') + 1,
async (input, next) => await next(input + 'middle2') + 2,
]
}, async (input) => {
return input.length
});
```
> Moved middleware up to actions

- js/plugins/vertexai/src/gemini.ts
Somewhat of an edge case, but you should be able to take `model.name` and look it back up in the registry.
> Use the same names from modelRefs as keys in SUPPORTED_GEMINI_MODELS

- js/core/src/tracing/localFileTraceStore.ts
The prompt runner calls the api to render prompts, which creates a large number of superfluous traces. This change enhances the local trace store with attribute-based filtering and default filters. Prompt rendering traces will continue to be captured in prod trace stores.
> Prevent prompt rendering from spamming local trace store

- docs/models.md
- docs/rag.md
- js/ai/src/generate.ts
- js/ai/src/model.ts
- js/ai/src/model/middleware.ts
- js/ai/src/prompt.ts
- js/ai/tests/model/middleware_test.ts
- js/dotprompt/src/prompt.ts
- js/dotprompt/src/template.ts
- js/dotprompt/tests/template_test.ts
This adds the ability to pass context (an array of `DocumentData[]`) to a model and adds default support for prompt augmentation if a model does not declare specific support for context. Usage:
```ts
const query = "What do cats like to eat?";
const docs = await retrieveStuff({query});
generate({
prompt: `Answer this question: ${query}`,
context: docs
});
```
This will augment the prompt to look something like this:
```
Answer this question: What do cats like to eat?
Use the following information to complete your task:
- [0]: Cats eat a variety of foods including dry kibble and wet foods that can be purchased at a pet store.
- [1]: Cats will hunt mice and birds for fun and for food.
```
> Adds context as first-class feature of Model.

- js/ai/src/generate.ts
- js/ai/src/prompt.ts
Trigger happy Enter-pressing led to importing the wrong type for DocumentData in a couple places. Luckily Firestore DocumentData is very loose (basically `Record<string, any>`) so it's not broken, just not typed correctly.
> Fixes DocumentData imports.

- js/plugins/dotprompt/src/registry.ts
- js/plugins/dotprompt/tests/prompt_test.ts
- js/samples/byo-evaluator/src/index.ts
- js/samples/cat-eval/src/index.ts
- js/samples/coffee-shop/src/index.ts
- js/samples/menu-example/basic/src/index.ts
- js/samples/prompt-file/src/index.ts
- js/samples/rag/src/index.ts
- Adding plugin to samples which use prompt files
- Checking existence of prompt folder before reading dir
- Fixing bug in registry key
> Resolving issues with loading dotprompt files

- js/plugins/googleai/package.json
- js/plugins/googleai/src/gemini.ts
- js/plugins/googleai/tests/gemini_test.ts
- js/pnpm-lock.yaml
Mostly cargo-culted from Vertex. Tested with the `jokeWithToolsFlow`.
> Implement tool calls for Google AI

- genkit-tools/cli/src/cli.ts
- genkit-tools/cli/src/commands/config.ts
- genkit-tools/cli/src/commands/eval-extract-data.ts
- genkit-tools/cli/src/commands/eval-flow.ts
- genkit-tools/cli/src/commands/eval-run.ts
- genkit-tools/cli/src/commands/flow-batch-run.ts
- genkit-tools/cli/src/commands/flow-resume.ts
- genkit-tools/cli/src/commands/flow-run.ts
- genkit-tools/cli/src/commands/init.ts
- genkit-tools/cli/src/commands/plugins.ts
- genkit-tools/cli/src/commands/start.ts
```
$ genkit help
Usage: genkit [options] [command]
Firebase Genkit CLI
Options:
-V, --version                                       output the version number
-h, --help                                          display help for command
Commands:
start [options]
flow:run [options] <flowName> [data]
flow:batchRun [options] <flowName> <inputFileName>
flow:resume <flowName> <flowId> <data>
eval:extractData [options] <flowName>
eval:run [options] <dataset>
eval:flow [options] <flowName> [data]
init [options]                                      Initialize a project directory with Genkit
config
help
```
> Minor cli cleanup: show help when no command provided, hide login/deploy unless plugins installed

- js/ai/src/telemetry.ts
Also move the metrics into separate input and output namespaces.
Counters are more useful for these metrics because they are cost-proxies and so getting the overall sum is more imporant than understanding the per-request rate.
> Update I/O metrics to be counters instead of histograms

- js/core/src/reflectionApi.ts
this sometimes may happen when nodejs gets confused normalizing imports and imports core multiple times
> Properly ensure reflection API is never started more than once

- genkit-tools/cli/package.json
- genkit-tools/package.json
- js/package.json
- package.json
Also removes superfluous `packageManager` field from `genkit-tools/cli/` since this is handled by `genkit-tools/`'s package.json.
https://github.com/pnpm/pnpm/releases/tag/v9.1.1
> Update pnpm to v9.1.1

- go/plugins/googlecloud/googlecloud.go
This is google/genkit#221. It was submitted after the repo
change.
> [Go] adjust traces (redo)

- go/genkit/logging.go
- go/plugins/localvec/localvec.go
- go/plugins/localvec/localvec_test.go
Add a genkit.DebugLog functions so that plugins can log debug info.
> [Go] add localvec to correspond to TypeScript dev-local-vectorstore

- go/go.mod
- go/go.sum
- go/plugins/googlecloud/googlecloud.go
- go/plugins/googlecloud/googlecloud_test.go
- go/plugins/googlecloud/slog_handler.go
- go/plugins/googlecloud/slog_handler_test.go
Add logging to the google-cloud plugin.
Use the GCP logging client for more control over logging that is
provided with JSON output, like the log name.
Write a slog Handler that constructs a logging.Entry.
Init installs a default logger with the handler.
> [Go] logging for GCP

- docs/firebase.md
You first get prompted to select the product and _then_ you select your project.
> Update order of selections in the Firebase

- go/plugins/vertexai/vertexai.go
- go/plugins/vertexai/vertexai_test.go
Copy the googleai tools support in #148 to vertexai.
> [Go] add tools support to vertexai plugin

- js/plugins/evaluators/src/metrics/answer_relevancy.ts
- js/plugins/evaluators/src/metrics/faithfulness.ts
- js/plugins/evaluators/src/metrics/helper.ts
- js/plugins/evaluators/src/metrics/maliciousness.ts
- js/testapps/rag/src/index.ts
- pnpm-lock.yaml
- Fixes Issue #130 
- Also fix minor bug in maliciousness.
> Make Evaluators plugin work with ESM

- docs/cloud-run.md
- docs/deploy-node.md
- docs/firebase.md
- docs/get-started.md
Using `firebase init genkit` instead of separate `firebase init && genkit init`
> Simplified firebase init instructions

- go/genkit/metrics.go
- js/ai/src/telemetry.ts
- js/core/src/telemetry.ts
- js/flow/src/telemetry.ts
Add a source dimension for all metrics for Go.
Add a source and source version to the Config log for TS.
> Add a source and source version dimension to all metrics for TS.

- go/ai/embedder.go
- go/ai/generator.go
- go/ai/retriever.go
- go/genkit/dotprompt/dotprompt.go
- go/genkit/dotprompt/genkit.go
- go/genkit/dotprompt/genkit_test.go
- go/genkit/dotprompt/render.go
- go/genkit/dotprompt/render_test.go
- go/go.mod
- go/internal/fakeembedder/fakeembedder.go
- go/internal/fakeembedder/fakeembedder_test.go
- go/plugins/googleai/googleai.go
- go/plugins/googleai/googleai_test.go
- go/plugins/googlecloud/googlecloud.go
- go/plugins/localvec/localvec.go
- go/plugins/localvec/localvec_test.go
- go/plugins/pinecone/genkit.go
- go/plugins/pinecone/genkit_test.go
- go/plugins/vertexai/embed.go
- go/plugins/vertexai/embed_test.go
- go/plugins/vertexai/vertexai.go
- go/plugins/vertexai/vertexai_test.go
- go/samples/coffee-shop/main.go
- go/samples/flow-sample1/main.go
Change the module path to match the repo.
> [Go] go.mod: change module path

- go/genkit/action.go
- go/genkit/action_test.go
invopop panics when inferring the schema for `struct{}`.
Handle that case specially.
> [Go] fix panic when registering indexer

- docs/templates/pgvector.md
- Should not use `<abc>/<xyz>` format since it is reserved for plugins.
> Update retrieverName in pgvector template

- go/genkit/dotprompt/dotprompt.go
- go/genkit/dotprompt/dotprompt_test.go
- go/genkit/dotprompt/genkit.go
- go/genkit/dotprompt/genkit_test.go
- go/genkit/dotprompt/render.go
- go/samples/coffee-shop/main.go
Attempt to make the dotprompt API a little more user-friendly.
The main change is to replace the exported Frontmatter type
with a type (called Config) that is easier to write a literal for.
Miscellaneous other changes:
- Unexport the Prompt.Hash field.
- Add `New` to create a prompt without registering it,
and use `Define` to mean create + register, as it does elsewhere.
- Remove the generator as an argument; I believe it would only be
used for tests.
> [Go] POC: redo dotprompt API

- docs/plugins/firebase.md
The correct field for passing custom options is `options`. For Issue #212 
> [Docs] Fix config -> options for  firestore retriever

- go/genkit/action.go
- go/genkit/dev_server.go
- go/genkit/flow.go
- go/genkit/flow_test.go
- go/genkit/gen.go
- go/genkit/logging.go
- go/genkit/metrics.go
- go/genkit/registry.go
- go/genkit/schemas.config
- go/genkit/tracing.go
- go/plugins/localvec/localvec.go
- Export Logger, remove DebugLog.
- Simplify the doc for Flow.
- Unexport more symbols that users shouldn't need.
> [Go] more API and doc changes

- genkit-tools/common/src/types/document.ts
- genkit-tools/common/src/types/model.ts
- genkit-tools/genkit-schema.json
Sync latest type definitions from core to tools for dev-ui.
> Sync model type definitions onto tools-common

- js/flow/src/flow.ts
Allows you to specify an optional path prefix for flows server.
if the flow name is `suggestMenuItems` and path prefix is `flows` then the server will be available on `/flows/suggestMenuItems`
Applies to all flows
> [JS] feat: add path prefix option to startFlowsServer

- js/plugins/dotprompt/src/prompt.ts
- js/plugins/dotprompt/src/registry.ts
- js/plugins/dotprompt/tests/prompt_test.ts
- js/testapps/menu/package.json
- js/testapps/menu/src/01/prompts.ts
- js/testapps/menu/src/02/flows.ts
- js/testapps/menu/src/02/prompts.ts
- js/testapps/menu/src/02/tools.ts
- js/testapps/menu/src/03/flows.ts
- js/testapps/menu/src/03/prompts.ts
- js/testapps/menu/src/04/flows.ts
- js/testapps/menu/src/04/prompts.ts
- js/testapps/menu/src/05/flows.ts
- js/testapps/menu/src/05/prompts.ts
- js/testapps/menu/src/index.ts
- js/testapps/menu/tsconfig.json
Addresses friction with defineDotprompt and ESM modules.
- Use of defineDotprompt() no longer requires installing the plugin
- The plugin still needs to be installed to load prompt files
- Validated compatibility with projects built as ESM modules
> Improving dotprompt plugin

- js/testapps/dev-ui-gallery/package.json
- js/testapps/dev-ui-gallery/prompts/hello.first-last-name.prompt
- js/testapps/dev-ui-gallery/prompts/hello.history.prompt
- js/testapps/dev-ui-gallery/prompts/hello.json-output.prompt
- js/testapps/dev-ui-gallery/prompts/hello.prompt
- js/testapps/dev-ui-gallery/prompts/hello.system.prompt
- js/testapps/dev-ui-gallery/prompts/tools.prompt
- js/testapps/dev-ui-gallery/src/index.ts
- js/testapps/dev-ui-gallery/src/main/prompts.ts
- js/testapps/dev-ui-gallery/src/main/tools.ts
Remove dotprompt from file names, add tool prompt(s), use gemini 1.5 flash.
> Updated prompt files in dev-ui-gallery

- js/plugins/dotprompt/src/index.ts
- js/plugins/dotprompt/src/registry.ts
Recursively looks for any `.prompt` file within the configured prompt directory, instead of just in the immediate folder.
Fixes https://github.com/firebase/genkit/issues/210.
> Recursively look for `.prompt` files in specified dir

- go/samples/cloud_run_deploy.sh
- go/samples/cloud_run_request.sh
Cloud Run deployment is more complicated in Go than Javascript,
so provide a shell script to simplify it and serve as a working
example.
Also add a shell script to make a request to a deployed service.
> [Go] shell scripts for Cloud Run

- go/ai/gen.go
- go/genkit/schemas.config
- go/internal/cmd/jsonschemagen/jsonschemagen.go
Some new types were added, and a new aspect of JSON Schema
that the code generator didn't know about.
The new aspect is that a "$ref" can refer to a property
inside a schema. The code generator still doesn't understand
these, but the config file handles them by ignoring them or
replacing them with another type.
> [Go] fix go generate

- go/ai/document.go
- go/ai/document_test.go
- go/ai/gen.go
- go/core/schemas.config
- go/plugins/dotprompt/render.go
- go/plugins/dotprompt/render_test.go
- go/plugins/googleai/googleai.go
- go/plugins/vertexai/vertexai.go
Data parts aren't really useable anywhere, but the js switched to
have this distinction.
> split Go Blob parts into Media and Data.

- genkit-tools/cli/src/commands/init.ts
> Added initialization of Node.js project if no runtime is detected.

- go/core/action.go
- go/core/flow.go
- go/core/logger/logger.go
- go/core/metrics.go
- go/core/servers.go
- go/core/tracing/tracing.go
- go/plugins/localvec/localvec.go
Move logging support out of internal so third-party plugins
can use it.
We can't put it in core because tracing needs it, so I made a
package for it. At that point I felt that `logger.FromContext`
read better than `logging.Logger`.
> [Go] move logging out of internal

- go/plugins/dotprompt/genkit.go
Corresponds to TypeScript PR #231.
> [Go] use "dotprompt" as the provider for dotprompt actions

- go/plugins/googleai/embed.go
- go/plugins/googleai/googleai.go
- go/plugins/pinecone/genkit.go
- go/plugins/vertexai/embed.go
- go/plugins/vertexai/vertexai.go
> Clean up doc strings

- go/plugins/localvec/localvec.go
- go/plugins/pinecone/genkit.go
- go/plugins/pinecone/genkit_test.go
- go/plugins/pinecone/pinecone.go
- go/samples/menu/main.go
- go/samples/menu/s01.go
- go/samples/menu/s02.go
- go/samples/menu/testdata/menu.json
- go/samples/rag/main.go
Change the pinecone and localvec plugins to use a New function that returns an ai.Retriever, and an Init function that registers one with genkit.
This makes the pinecone and localvec plugins consistent with each other, and with other plugins such as googleai.
> [Go] change embedder plugins to use Init and New

- genkit-tools/common/src/server/router.ts
- genkit-tools/common/src/types/apis.ts
Adding the `toolNames` property to `CreatePromptRequestSchema` which will then get passed to the PromptFormatter used to export prompts from the Prompt Runner and Model Runner. I used the property `toolNames` instead of `tools` to prevent incompatibility with the `main` branch of the genkit-ui which sends `tools` as a `ToolDefinitionSchema` object.
Manually tested without UI changes to ensure this is a non-breaking change
> Add array of toolNames to CreatePromptRequest

- js/core/src/tracing/instrumentation.ts
- js/flow/src/flow.ts
- js/flow/src/telemetry.ts
Add a variant counter with flow name, success status, and variant dimensions.
> Capture and log all flow variants.

- go/ai/prompt.go
- go/plugins/dotprompt/dotprompt.go
- go/plugins/dotprompt/genkit.go
- go/plugins/dotprompt/genkit_test.go
- go/plugins/dotprompt/render.go
- go/samples/coffee-shop/main.go
- go/samples/rag/main.go
Also rationalize the dotprompt package and make it easier to use.
> [Go] add general prompt support to ai package

- go/plugins/localvec/localvec.go
- go/plugins/localvec/localvec_test.go
Make LocalVec use the same DB file across runs.
> [Go] Reuse the same file in localvec when indexing

- go/ai/retriever.go
- go/plugins/localvec/localvec.go
- go/plugins/pinecone/genkit.go
Add ai.DefineRetriever, which creates and registers core.Actions for
the index and retrieve methods of a vector DB.
Remove RegisterRetriever.
Remove the Init functions from our vector DB plugins.
Instead, the New functions return a Retriever that supports
actions directly.
There is no longer a way to create a Retriever that doesn't
use actions.
> [Go] retrieve and index calls are always actions

- go/ai/embedder.go
- go/ai/retriever.go
- go/plugins/localvec/localvec.go
- go/plugins/localvec/localvec_test.go
- go/plugins/pinecone/genkit.go
Rename the two-function interface that represents
both indexing and retrieval, to avoid confusion with
the retrieval part alone.
> [Go] rename Retriever to DocumentStore

- go/ai/generator.go
- go/core/action.go
- go/plugins/dotprompt/dotprompt.go
- go/plugins/dotprompt/genkit.go
- go/plugins/dotprompt/genkit_test.go
- go/plugins/googleai/googleai.go
- go/plugins/vertexai/vertexai.go
- go/samples/coffee-shop/main.go
- go/samples/menu/main.go
- go/samples/menu/s01.go
- go/samples/menu/s02.go
- go/samples/menu/s03.go
- go/samples/menu/s04.go
- go/samples/menu/s05.go
- go/samples/rag/main.go
Add ai.DefineGenerator, which wraps a generate function in an action.
This allowed some simplification and deduplication in the ai package's
generate code.
- Rename LookupGeneratorAction to LookupGenerator.
- Add a Generator config option to dotprompt so that model
lookup by string can be avoided.
> [Go] generate calls are always actions

- go/ai/embedder.go
- go/ai/generator.go
- go/ai/retriever.go
- go/ai/tools.go
- go/core/action.go
- go/plugins/googleai/embed.go
- go/plugins/googleai/googleai_test.go
- go/plugins/localvec/localvec.go
- go/plugins/vertexai/embed.go
- go/plugins/vertexai/vertexai_test.go
- go/samples/menu/s02.go
Tools were not working because they were being inserted as
tool/tool/name and looked up as tool/name/name.
> Normalize to type/provider/name pattern for action names.

- go/plugins/pinecone/pinecone.go
> [Go] fix broken struct tags

- go/plugins/googlecloud/googlecloud.go
Change the signature of googlecloud.Init to make it like the other
plugins.
> [Go] make googlecloud.Init conform

- go/ai/embedder.go
- go/internal/fakeembedder/fakeembedder.go
- go/internal/fakeembedder/fakeembedder_test.go
- go/plugins/googleai/googleai.go
- go/plugins/googleai/googleai_test.go
- go/plugins/localvec/localvec.go
- go/plugins/localvec/localvec_test.go
- go/plugins/pinecone/genkit.go
- go/plugins/pinecone/genkit_test.go
- go/plugins/vertexai/vertexai.go
- go/plugins/vertexai/vertexai_test.go
Remove the Embedder interface. Replace it with a type
alias to an Action with the appropriate type parameters.
> [Go] replace Embedder interface with EmbedderAction

- go/ai/retriever.go
- go/core/registry.go
- go/plugins/localvec/localvec.go
- go/plugins/localvec/localvec_test.go
- go/plugins/pinecone/genkit.go
- go/plugins/pinecone/genkit_test.go
- go/samples/menu/main.go
- go/samples/menu/s04.go
- go/samples/rag/main.go
Continue the redesign in which interfaces are replaced by
aliases to action types.
Remove DocumentStore, and replace it with two separate actions,
one for indexers and one for retrievers.
> [Go] replace ai.DocumentStore with indexer and retriever actions

- go/ai/embedder.go
- go/ai/generate.go
- go/ai/prompt.go
- go/ai/retriever.go
- go/ai/tools.go
- go/core/action.go
- go/core/action_test.go
- go/core/flow.go
- go/core/registry.go
- go/core/servers_test.go
- go/internal/atype/atype.go
ActionType is really an implementation detail. By making it internal,
not only do we reduce clutter in the user-facing API, but we also
make it impossible for 3P code to register any actions of a type
that they shouldn't. For instance, now the only way to register an
embedder is with ai.DefineEmbedder.
The exception is custom actions, so we provide DefineCustomAction.
> [Go] make ActionType internal

- go/plugins/localvec/localvec.go
- go/plugins/localvec/localvec_test.go
- go/samples/menu/main.go
- go/samples/rag/main.go
Vector DBs only register two actions: an indexer and a retriever.
Continue to allow users to look up these actions by name.
But also return them from Init.
> [Go] proposal: vector DB Inits return actions

- js/ai/src/telemetry.ts
- js/core/src/telemetry.ts
- js/flow/src/telemetry.ts
- js/plugins/google-cloud/package.json
- js/plugins/google-cloud/src/gcpOpenTelemetry.ts
- js/plugins/google-cloud/src/index.ts
- js/plugins/google-cloud/tests/metrics_test.ts
Initial test infrastructure to verify structure of flow and action level metrics written by the google-cloud plugin.
> Add initial tests for open telemetry metrics exported via the GCP plugin

- js/core/src/tracing/instrumentation.ts
- js/core/src/tracing/types.ts
- js/flow/src/flow.ts
- js/flow/src/telemetry.ts
This allows us to keep the path variants written to metrics to be scoped to a single trace.
Co-authored-by: Konstantin Mandrika <kmandrika@google.com>
> Update path variant logic to store paths in a new trace-scoped async local storage

- js/ai/src/model.ts
- js/ai/src/telemetry.ts
- js/plugins/googleai/src/gemini.ts
- js/plugins/vertexai/src/gemini.ts
Gemini usage metrics now include returned token counts and correctly counts different media types (images, video and audio files). This was previously counting any media type as an image.
> Update usage metrics capture for gemini to include returned token counts

- go/core/action.go
- go/core/registry.go
Export the name method on Action. It turns out to be useful
to identify multiple actions returned from an Init call.
> [Go] export Action.Name

- go/plugins/googleai/googleai_test.go
This should already be the case, just testing it.
> test that streaming and final answer contain the same text.

- .npmrc
- genkit-tools/package.json
- js/package.json
- package.json
Also incorporates the new `package-manager-strict-version` npmrc settings from pnpm 9.2.0 so enforce that everyone uses the same version (useful to prevent lockfile thrashing).
See https://github.com/pnpm/pnpm/releases/tag/v9.3.0 for full release notes.
> Update to pnpm v9.3

- js/plugins/google-cloud/src/gcpOpenTelemetry.ts
- js/plugins/google-cloud/src/index.ts
- js/plugins/google-cloud/tests/metrics_test.ts
Add ability to optionally disable collection of traces/metrics via Google Cloud plugin options.
> Add ability to optionally disable collection of traces/metrics

- js/core/src/metrics.ts
- js/flow/src/telemetry.ts
- js/plugins/google-cloud/src/gcpOpenTelemetry.ts
- js/plugins/google-cloud/tests/metrics_test.ts
* Update default metric export frequency from 10s to 60s
* Truncate metric dimensions to 32 characters
These changes are to prevent unexpected large metric dimensions and frequent exports from running up metrics ingestion costs.
> Update metrics export defaults and truncate metric labels

- js/plugins/vertexai/src/gemini.ts
Originally reported [here](https://github.com/TheFireCo/genkit-plugins/issues/85) (wrong repo).
Gemini 1.5 Pro available model version was incorrectly set to Gemini 1.0 Pro instead.
> [VertexAI] Fix Gemini 1.5 Pro model version

- js/plugins/google-cloud/src/gcpOpenTelemetry.ts
Also switch to using DELTA temporality and reduce export frequency to 5m intervals by default.
> Update GCP metric exporter to use an ExponentialHistogramAggregation

- js/ai/src/telemetry.ts
- js/core/src/telemetry.ts
- js/core/src/tracing/instrumentation.ts
- js/core/src/tracing/types.ts
- js/flow/src/telemetry.ts
- js/plugins/google-cloud/tests/metrics_test.ts
This allows for these metrics to be grouped and filtered by flow.
> Add a flow name label to action and generate level metrics

- go/plugins/localvec/localvec_test.go
- go/plugins/pinecone/genkit_test.go
- go/testing/mockembedder/mockembedder.go
- go/testing/mockembedder/mockembedder_test.go
Move the fakeembedder package out of internal so anyone can
use it for testing.
Also, somewhat pedantically, rename it because it's actually
a mock.
(Hyperpedantically, it's a stub
(https://testing.googleblog.com/2013/07/testing-on-toilet-know-your-test-doubles.html),
but I don't think anyone observes that distinction.)
> [Go] expose mock embedder

- docs/dotprompt.md
- js/plugins/dotprompt/src/picoschema.ts
- js/plugins/dotprompt/tests/picoschema_test.ts
- js/plugins/dotprompt/tests/prompt_test.ts
Three quality-of-life improvements for Picoschema:
1. You can now specify `any` as a scalar type and it will allow anything.
2. When a field is marked as optional, Picoschema will *also* mark it as nullable. This fixes an annoying situation where LLMs return `null` values instead of omitting keys.
3. You can have a wildcard field in an object using `(*)` as a key.
> Adds 'any' scalar, nullable optionals, wildcards to Picoschema.

- go/ai/prompt.go
- go/core/action.go
- go/core/conformance_test.go
- go/core/flow.go
- go/core/registry.go
- go/core/servers_test.go
- go/plugins/dotprompt/dotprompt.go
- go/plugins/dotprompt/genkit.go
- go/plugins/localvec/localvec_test.go
- go/samples/coffee-shop/main.go
Action names are fully qualified (which includes provider id). Action name are used downstream in tracing and being fully qualified is important when loading traces in the Dev UI.
> fix: [Go] action name must include provider

- docs/plugins/firebase.md
- js/plugins/firebase/src/firestoreRetriever.ts
> [plugins/firebase] defineFirestoreRetriever: Allow supplying collection at retrieval time

- go/core/registry.go
- go/core/servers.go
- go/core/servers_test.go
- go/genkit/genkit.go
- go/plugins/googleai/googleai.go
- go/plugins/googleai/googleai_test.go
- go/plugins/localvec/localvec.go
- go/plugins/localvec/localvec_test.go
- go/plugins/pinecone/genkit.go
- go/plugins/pinecone/genkit_test.go
- go/plugins/vertexai/vertexai.go
- go/plugins/vertexai/vertexai_test.go
- go/samples/coffee-shop/main.go
- go/samples/flow-sample1/main.go
- go/samples/menu/main.go
- go/samples/rag/main.go
In this API, configuration (defining actions) should still happen
at the beginning of the program, but can be done incrementally by
calling functions on a plugin. For example:
err := googleai.Init(...)   // creates state common to all actions
m1 := googleai.DefineModel("gemini-1.0-pro")
e1 := googleai.DefineEmbedder("emb-01")
When everything has been configured, the program must call genkit.Init.
This has two effects:
- Attempts to register additional actions will fail.
- The dev server is started.
This API combines the convenience and clarity of building and storing
actions individually with the requirement that everything that the
program needs is registered early.
DO NOT SUBMIT. Implementation is incomplete. For discussion only.
> [Go] proposal: revised API

- go/ai/retriever.go
- go/plugins/localvec/localvec.go
- go/plugins/localvec/localvec_test.go
- go/plugins/pinecone/genkit.go
- go/plugins/pinecone/genkit_test.go
- go/samples/menu/s04.go
- go/samples/rag/main.go
Calling Retriever on a retriever as a method is more natural
in Go than calling a top-level function, as we currently have.
This PR changes Indexer and Retriever from being aliases of Actions
to being their own types, allowing methods.
If we like this, then a followup PR would do the same for
Model, Embedder and possibly Tool.
> [Go] proposal: AI types have methods

- go/plugins/googleai/googleai.go
- go/plugins/googleai/googleai_test.go
- go/samples/coffee-shop/main.go
- go/samples/rag/main.go
Every model must be associated with a set of capabilities.
DefineModel now takes an *ai.ModelCapabilities as a second argument.
It can be omitted for known models, but must be provided
for unknown ones.
Modeled on #426.
(no pun intended)
> [Go] googleai: require models to have capabilities

- go/plugins/localvec/localvec.go
- go/plugins/localvec/localvec_test.go
- go/plugins/pinecone/genkit.go
- go/samples/menu/main.go
- go/samples/rag/main.go
I tried to separate DefineStore into DefineIndexer and DefineRetriever,
but I didn't see a good way to share the in-memory state of the store.
Although DefineIndexerAndRetriever is cumbersome, it at least
removes the otherwise unused term "Store".
> [Go] rename localvec.DefineStore

- go/ai/generate.go
- go/plugins/dotprompt/dotprompt.go
- go/plugins/dotprompt/dotprompt_test.go
- go/plugins/dotprompt/genkit.go
- go/plugins/dotprompt/genkit_test.go
- go/plugins/googleai/googleai.go
- go/plugins/googleai/googleai_test.go
- go/plugins/ollama/ollama.go
- go/plugins/vertexai/vertexai.go
- go/plugins/vertexai/vertexai_test.go
- go/samples/coffee-shop/main.go
- go/samples/menu/s01.go
- go/samples/menu/s02.go
- go/samples/menu/s03.go
- go/samples/menu/s04.go
- go/samples/menu/s05.go
- go/samples/rag/main.go
This continues the work begun in #402 of making the main ai types
distinct from their underlying actions, instead of aliases.
This allows the types to have methods, unstead of using top-level
functions.
It also clarifies documentation and other output, like panic stack
traces.
> [Go] ai.Model is a separate type from its action

- go/ai/embedder.go
- go/internal/fakeembedder/fakeembedder.go
- go/internal/fakeembedder/fakeembedder_test.go
- go/plugins/googleai/googleai.go
- go/plugins/googleai/googleai_test.go
- go/plugins/localvec/localvec.go
- go/plugins/pinecone/genkit.go
- go/plugins/vertexai/vertexai.go
- go/plugins/vertexai/vertexai_test.go
> [Go] ai.Embedder is a separate type from its action

- docs-go/flows.md
- docs-go/models.md
> Update some Go snippets

- js/plugins/firebase/package.json
- js/pnpm-lock.yaml
Picks up https://github.com/firebase/firebase-admin-node/pull/2553 which unlocks using application default credentials for local development.
> Upgrading firebase-admin to 12.2.0

- go/plugins/googleai/googleai.go
- go/plugins/vertexai/vertexai.go
- go/plugins/vertexai/vertexai_test.go
- go/samples/coffee-shop/main.go
- go/samples/menu/main.go
This allows:
```go
for _, mname := range googleai.KnownModels() {
m, err := googleai.DefineModel(mname, nil)
}
```
> feat: [Go] added KnownModels function to googeai and vertexai

- docs/plugins/google-cloud.md
- js/plugins/firebase/package.json
- js/plugins/firebase/src/index.ts
- js/plugins/google-cloud/src/gcpLogger.ts
- js/plugins/google-cloud/src/gcpOpenTelemetry.ts
- js/plugins/google-cloud/src/index.ts
- js/plugins/google-cloud/tests/metrics_test.ts
- js/pnpm-lock.yaml
Adds dependency from Firebase plugin to GCP plugin, and moves the 'forceDevExport' config option under  TelemetryConfig since it is specific to telemetry data export.
> Adds telemetry export support to Firebase plugin

- docs-go/flows.md
- go/core/flow.go
- go/core/flow_test.go
- go/genkit/genkit.go
- go/genkit/genkit_test.go
- go/internal/doc-snippets/flows.go
- go/samples/coffee-shop/main.go
- go/samples/flow-sample1/main.go
- go/samples/menu/s05.go
Make Run and Stream methods on Flow instead of top-level functions.
> [Go] change RunFlow and StreamFlow to methods

- js/plugins/google-cloud/src/gcpOpenTelemetry.ts
- js/plugins/google-cloud/tests/traces_test.ts
Using colons in span attributes make filtering by these labels difficult in the Trace Explorer.
* Add tests for GCP exported traces
* Modify AdjustingTraceExporter to facilitate testing
> Update GCP Trace exporter to avoid ':' in span attributes.

- js/ai/src/telemetry.ts
- js/core/src/telemetry.ts
- js/flow/src/telemetry.ts
- js/plugins/google-cloud/tests/metrics_test.ts
> Add a status label to metrics so that they can be filtered by success state

- js/ai/src/telemetry.ts
- js/core/src/tracing/instrumentation.ts
- js/flow/src/telemetry.ts
- js/plugins/google-cloud/src/gcpLogger.ts
- js/plugins/google-cloud/tests/logs_test.ts
Adds simple tests to make sure the right log messages (with friendly paths) are being written, but does not yet test the structured date.
> Updates logs to write friendly display paths instead of the annotated version

- docs/models.md
Redundant with "Streaming responses" section
> Update models.md -- remove callback streaming example

- genkit-tools/cli/config/firebase.index.ts.template
- genkit-tools/cli/config/googleCloud.index.ts.template
- genkit-tools/cli/config/main.go.template
- genkit-tools/cli/config/nextjs.genkit.ts.template
- genkit-tools/cli/src/commands/init/init-go.ts
- genkit-tools/cli/src/commands/init/init-nodejs.ts
Go output: https://gist.github.com/kevinthecheung/bc41261e4e0e9850f120dd1a2e97dbf3
TS output: https://gist.github.com/kevinthecheung/db024740526e1895f6bbd4169591ee36
> Add comments to init templates

- go/core/file_flow_state_store.go
- go/genkit/flow.go
- go/internal/common/common.go
Provide a higher-level API that does not require callers to
acquire locks.
> [Go] improve the FlowStater interface

- go/core/action.go
- go/core/action_test.go
- go/genkit/flow.go
- go/genkit/servers_test.go
Define a single, general newAction function.
Define a single fully general method for defining an action
in a registry. All other Define functions call it.
Export it so the genkit package can use it to define flows.
It's unfortunate that we have to export it, but code outside the
module can't call it anyway because it takes a registry, which
has an internal type.
> [Go] improve core action API

- go/core/action.go
- go/core/action_test.go
- go/core/core.go
- go/core/file_flow_state_store.go
- go/core/flow_state_store.go
- go/genkit/conformance_test.go
- go/genkit/flow.go
- go/genkit/genkit.go
- go/genkit/servers.go
- go/genkit/servers_test.go
- go/internal/action/action.go
- go/internal/base/misc.go
- go/internal/registry/registry.go
Get rid of the internal/common package by moving things elsewhere.
> [Go] remove internal/common

- go/plugins/dotprompt/dotprompt_test.go
- go/plugins/dotprompt/picoschema.go
- go/plugins/dotprompt/picoschema_test.go
- js/plugins/dotprompt/tests/picoschema_tests.yaml
Use the yaml file of test cases to test the Go picoschema implementation.
This uncovered a few problems. Some new features were implemented in
JS but not in Go; they are implemented here.
More seriously, it was discovered that the JSON schema package we
are using, github.com/invopop/jsonschema, does not support
arrays for the "type" field, and probably never will (see
https://github.com/invopop/jsonschema/issues/134). Tests that
require that are skipped.
> [Go] test picoschema with yaml test cases

- js/ai/src/generate.ts
- js/ai/src/model.ts
- js/ai/src/telemetry.ts
Move logging for generate action to ensure correct context for span
> Move logging to ensure correct context for span

- go/ai/embedder.go
- go/internal/fakeembedder/fakeembedder.go
- go/internal/fakeembedder/fakeembedder_test.go
- go/plugins/googleai/googleai.go
- go/plugins/googleai/googleai_test.go
- go/plugins/localvec/localvec.go
- go/plugins/pinecone/genkit.go
- go/plugins/vertexai/embed.go
- go/plugins/vertexai/vertexai.go
- go/plugins/vertexai/vertexai_test.go
- An EmbedRequest takes a slice of Documents instead of a single Document.
- An EmbedResponse contains embeddings for each document. The []float32
containing the embedding is inside a struct, to accommodate future
additions (and to match the JS).
- The googleai embedder works on multiple documents sequentially.
It should be changed to use the BatchEmbed RPC.
- The vertexai embedder always handled multiple "instances". Now an
instance is the concatenated text parts of a document; before it
was one text part of the sole document. (This is the only behavioral
change.)
There is one unrelated change: the prompt of a generation test
was changed because the previous prompt is now blocked for the
"recitation" reason.
> [Go] align Embedder API with JS

- go/plugins/googleai/googleai.go
- go/plugins/vertexai/vertexai.go
Ensure that the global state is protected during
Init, DefineModel and DefineEmbedder.
> [Go] plugins/googleai: fix locking

- docs/evaluation.md
> Update evals to use menuSuggestion flow

- docs/plugins/firebase.md
> Add telemetry section to the Firebase plugin docs.

- js/ai/src/generate.ts
- js/testapps/flow-simple-ai/src/index.ts
```
Error: FAILED_PRECONDITION: Generation resulted in not a single candidate matching provided output schema.
```
```
Error: FAILED_PRECONDITION: Generation resulted in not a single candidate matching provided output schema.
Candidate[0] Error: INVALID_ARGUMENT: Schema validation failed. Parse Errors:
- (root): must have required property 'name'
Provided data:
{
"displayName": "Some Name"
}
Required JSON schema:
{
"type": "object",
"properties": {
"name": {
"type": "string"
}
},
"required": [
"name"
],
"additionalProperties": true,
"$schema": "http://json-schema.org/draft-07/schema#"
}
```
> Better NoValidCandidatesError messages.

- js/ai/src/generate.ts
- js/ai/src/model/middleware.ts
- js/ai/tests/model/middleware_test.ts
- js/testapps/flow-simple-ai/src/index.ts
Before, combining a tool call with output conformance could result in two different errors:
1. `Vertex response generation failed: ClientError: [VertexAI.ClientError]: Within a single message, FunctionResponse cannot be mixed with other type of part in the request for sending chat message.`
2. A schema validation error.
The first was caused by the output conformance middleware appending instructions to the last message instead of the last *user* role message.
The second was caused by the output schema validation trying to validate all candidates, even if the message returned contained no text or data part (e.g. a tool request).
> Fix bugs related to combining tools and output conformance

- docs/dotprompt.md
> Clarify that prompt variants will not fallback to the base prompt

- genkit-tools/cli/src/commands/eval-flow.ts
- genkit-tools/common/jest.config.ts
- genkit-tools/common/package.json
- genkit-tools/common/src/types/eval.ts
- genkit-tools/common/src/utils/eval.ts
- genkit-tools/common/tests/utils/eval_test.ts
- genkit-tools/common/tests/utils/trace.ts
- genkit-tools/pnpm-lock.yaml
- js/pnpm-lock.yaml
- js/testapps/cat-eval/eval/cat_adoption_questions.json
- js/testapps/cat-eval/package.json
- js/testapps/cat-eval/src/pdf_rag.ts
- package.json
> Gracefully handle inference errors when running `eval:flow`

- docs/firebase.md
> Tweaks and corrections to cloud secrets info

- js/core/src/tracing/instrumentation.ts
- js/core/src/tracing/types.ts
- js/flow/src/telemetry.ts
- js/plugins/google-cloud/tests/metrics_test.ts
Previously it was always being attributed to the root flow path.
> Update telemetry to properly attribute failures to correct path.

- js/core/src/tracing.ts
- js/testapps/flow-simple-ai/src/index.ts
Open Telemetry metrics are not flushed by default on shutdown. For local runs (where shutdown happens immediately following completion of flow) we need to flush manually before the OTel client is shutdown.
- [ X ] Tested (manually)
> Force flush of metrics after local run

- js/flow/package.json
- js/flow/src/flow.ts
- js/pnpm-lock.yaml
this just a cleanup of #193
this allows
```ts
startFlowsServer({
jsonParserOptions: {
limit: '32mb',
}
})
```
Co-authored-by: tzahush
> feat: added json parser options to startFlowsServer

- go/internal/doc-snippets/dotprompt.go
- go/internal/doc-snippets/init/main.go
- go/internal/doc-snippets/models.go
- go/plugins/googleai/googleai.go
- go/plugins/googleai/googleai_test.go
- go/plugins/vertexai/vertexai.go
- go/plugins/vertexai/vertexai_test.go
- go/samples/coffee-shop/main.go
- go/samples/menu/main.go
- go/samples/rag/main.go
Allow users to pass client options to the GCP clients for the
googleai and vertexai plugins.
To allow this and also to enable additional config in the future
without introducing breaking changes, add a Config struct to
each plugin, and have Init take it as an argument.
Also, slightly rewrite the samples to avoid redundant code for
looking up environment variables.
> [Go] add support for GCP client options

- js/core/src/tracing/instrumentation.ts
- js/plugins/google-cloud/tests/metrics_test.ts
* Updates logic for determining whether or not to add a path to the traceMetadata to be based on the presence of any children paths as opposed to checking the path length. This both solves the rethrow problem and cleans up some of the code.
> Fix issue where failed paths are written with parent path due to rethrows

- js/core/src/tracing/instrumentation.ts
- js/plugins/google-cloud/tests/metrics_test.ts
> [Telemetry] Fix issue where non-leaf failure paths aren't being added.

- js/core/src/tracing/localFileTraceStore.ts
These were part of triaging an evals bug long ago, but that has since been fixed and these statements are just noise now.
> Remove superfluous debug log statements

- go/ai/gen.go
- go/ai/request_helpers.go
- go/tests/api_test.go
- go/tests/test_app/main.go
- tests/test_js_app.yaml
- tests/test_js_app/src/index.ts
Write a Go test that uses the yaml file for reflection API tests
from #549.
Currently, the api/actions test fails because the schemas
are very different between Go and JS.
> [Go] e2e test for reflection API

- go/internal/doc-snippets/ollama.go
- go/plugins/ollama/ollama.go
Pass a Config struct to Init instead of just the server address,
to allow for additional configuration options.
By passing a struct, adding options is not a breaking change.
Also make other minor stylistic changes.
> [Go] ollama.Init takes Config

- genkit-tools/common/src/utils/utils.ts
a common use case is when genkit cli is installed locally (to be used with `npx`) but using Go as runtime. In cases when there's both Go  files and `package.json` prefer Go runtime.
> fix: when detecting runtime in the CLI favor Go over nodejs when both are present

- go/ai/embedder.go
- go/ai/generate.go
- go/plugins/googleai/googleai.go
IsDefinedModel is more general. You can call it right after Init
to determine if a model is known, or any time to see if you've already
defined a model, and avoid the panic from DefineModel.
Also remove KnownModels. It's unclear if it's useful. If it is, we can
always add it later.
Do the same for embedders.
> [Go] replace IsKnownModel with IsDefinedModel

- js/plugins/firebase/src/index.ts
> Handle lack of project id in the firebase plugin in dev.

- docs-go/_guides.yaml
- docs-go/deploy.md
> Generic deployment docs for Go

- go/ai/embedder.go
We renamed ModelAction and EmbedderAction to Model and Embedder,
respectively.
> [Go] remove references to FooAction

- go/plugins/dotprompt/dotprompt.go
- go/plugins/dotprompt/dotprompt_test.go
- go/plugins/dotprompt/genkit.go
- go/samples/coffee-shop/main.go
> [Go] Make dotprompt take in `jsonschema.Schema` instead of `map[string]any` for better ergonomics.

- docs/dotprompt.md
- docs/index.md
- docs/models.md
- docs/prompts.md
[#460](https://github.com/firebase/genkit/issues/460)
> docs: make sure to use Gemini 1.5 Flash as the default

- docs/dotprompt.md
Dotprompt variant examples was using Gemini 1.0 Pro, so I changed it to use Gemini 1.5 Pro
> changed dotprompt variable example to use Gemini 1.5 Pro

- CONTRIBUTING.md
- js/ai/package.json
- js/ai/src/extract.ts
- js/ai/src/generate.ts
- js/ai/tests/generate/generate_test.ts
- js/pnpm-lock.yaml
> feat(js): add support for streaming json output

- genkit-tools/common/src/utils/analytics.ts
Add a first-open event after GA acknowledgement so we can track new vs returning users
> Add a first_open even after GA ack to track new users

- go/ai/generate.go
- go/ai/generator_test.go
- go/internal/base/json.go
- go/internal/base/json_test.go
- go/internal/doc-snippets/dotprompt.go
- go/internal/doc-snippets/googleai.go
- go/internal/doc-snippets/init/main.go
- go/internal/doc-snippets/models.go
- go/internal/doc-snippets/ollama.go
- go/internal/doc-snippets/prompts.go
- go/internal/doc-snippets/rag/main.go
- go/internal/doc-snippets/vertexai.go
- go/plugins/dotprompt/genkit.go
- go/plugins/googleai/googleai_test.go
- go/plugins/vertexai/vertexai_test.go
- go/samples/coffee-shop/main.go
- go/samples/menu/s02.go
- go/samples/menu/s03.go
- go/samples/rag/main.go
- go/tests/test_app/main.go
- go/tests/utils/utils.go
```go
model := googleai.Model("gemini-1.5-flash")
// simple text
text, err := model.GenerateText(ctx,
ai.WithConfig(&ai.GenerationCommonConfig{Temperature: 1}),
ai.WithTextPrompt("Tell me a joke"))
// with tools
gablorkenTool := ai.DefineTool("gablorken", "use when need to calculate a gablorken",
func(ctx context.Context, input struct {
Value float64
Over  float64
}) (float64, error) {
return math.Pow(input.Value, input.Over), nil
},
)
text, err := model.GenerateText(ctx,
ai.WithCandidates(1),
ai.WithTextPrompt("what is a gablorken of 2 over 3.5?"),
ai.WithTools(gablorkenTool))
// with mesages
response, err = model.Generate(ctx,
ai.WithMessages(history...),
ai.WithTextPrompt("What were we talking about?"))
// with history
resp1, err := m.Generate(ctx, ai.WithTextPrompt("hi, my name is …
```
> refactor: [Go] updated the ai.Generate API

- js/plugins/firebase/src/auth.ts
- js/plugins/firebase/tests/auth_test.ts
I think the original intention of the author was to default to true if `config.required` isn't specified, but `||true` will just always evaluate to true. This blocks me when I was following the onboarding flow of https://firebase.google.com/docs/genkit/get-started#gemini-google-ai
> Respect config.required for auth

- go/ai/generate.go
- go/ai/generator_test.go
- go/internal/doc-snippets/googleai.go
- go/internal/doc-snippets/init/main.go
- go/internal/doc-snippets/models.go
- go/internal/doc-snippets/ollama.go
- go/internal/doc-snippets/prompts.go
- go/internal/doc-snippets/rag/main.go
- go/internal/doc-snippets/vertexai.go
- go/plugins/dotprompt/dotprompt.go
- go/plugins/dotprompt/genkit.go
- go/plugins/googleai/googleai.go
- go/plugins/googleai/googleai_test.go
- go/plugins/ollama/ollama.go
- go/plugins/vertexai/vertexai.go
- go/plugins/vertexai/vertexai_test.go
- go/samples/menu/s01.go
- go/samples/menu/s02.go
- go/samples/menu/s03.go
- go/samples/menu/s04.go
- go/samples/menu/s05.go
- go/tests/test_app/main.go
```go
model := googleai.Model("gemini-1.5-flash")
resp, err := ai.Generate(ctx, model, ai.WithTextPrompt("tell me a joke"))
text, err := ai.GenerateText(ctx, model, ai.WithTextPrompt("tell me a joke"))
// structured output
type GameCharacter struct {
Name      string
Backstory string
}
character := &GameCharacter{}
_, err = ai.GenerateData(ctx, model, character,
ai.WithTextPrompt("generate a game character"))
// model raw interface
resp, err := model.Generate(ctx, &ai.GenerateRequest{
Messages: []*ai.Message{
// ....
},
}, streamingCallback)
```
> refactor: [Go] Model is an interface and ai.Generate/Text/Data are veneers

- docs/dotprompt.md
- js/plugins/dotprompt/src/index.ts
- js/plugins/dotprompt/src/prompt.ts
- js/plugins/dotprompt/tests/prompt_test.ts
- js/plugins/dotprompt/tests/template_test.ts
This PR adds a DotpromptRef class to allow sync references to prompts in dotprompt.
resolves https://github.com/firebase/genkit/issues/513
> feat: allow for sync references to prompt files

- go/ai/generate.go
- go/ai/generator_test.go
- go/internal/base/json.go
- go/internal/base/json_test.go
Keep same case for acronyms and other initialisms.
> [Go] rename to follow Go initialism rules

- go/ai/embedder.go
- go/internal/doc-snippets/googleai.go
- go/internal/doc-snippets/vertexai.go
- go/internal/fakeembedder/fakeembedder_test.go
- go/plugins/googleai/googleai.go
- go/plugins/googleai/googleai_test.go
- go/plugins/localvec/localvec.go
- go/plugins/pinecone/genkit.go
- go/plugins/vertexai/vertexai.go
- go/plugins/vertexai/vertexai_test.go
- go/samples/pgvector/main.go
```go
res, err := ai.Embed(ctx, embedder, ai.WithEmbedText(userInput))
```
> refactor: [Go] embedder is an interface and ai.Embed is a veneer

- go/ai/generate.go
- go/ai/retriever.go
- go/internal/doc-snippets/googleai.go
- go/internal/doc-snippets/pinecone.go
- go/internal/doc-snippets/rag/main.go
- go/internal/doc-snippets/vertexai.go
- go/plugins/googleai/googleai.go
- go/plugins/localvec/localvec.go
- go/plugins/pinecone/genkit.go
- go/plugins/pinecone/genkit_test.go
- go/plugins/vertexai/vertexai.go
- go/samples/menu/s04.go
- go/samples/pgvector/main.go
- go/samples/rag/main.go
```go
resp, err := ai.Retrieve(ctx, retriever,
ai.WithRetrieverText(userQuery),
ai.WithRetrieverOpts(&localvec.RetrieverOptions{
K: 3,
}))
err = ai.Index(ctx, indexer,
ai.WithIndexerOpts(&pinecone.IndexerOptions{
Namespace: namespace,
}),
ai.WithIndexerDocs(d1, d2, d3))
```
> refactor: [Go] retriever/indexer are interfaces, ai.Retrieve/Index are veneers

- js/plugins/vertexai/src/anthropic.ts
- js/plugins/vertexai/src/embedder.ts
- js/plugins/vertexai/src/gemini.ts
- js/plugins/vertexai/src/imagen.ts
- js/plugins/vertexai/src/index.ts
- js/plugins/vertexai/src/model_garden.ts
- js/plugins/vertexai/src/openai_compatibility.ts
- js/plugins/vertexai/src/predict.ts
- js/plugins/vertexai/tests/anthropic_test.ts
```ts
configureGenkit({
plugins: [
vertextAI({
location: 'us-central1',
modelGarden: {
models: [claude35Sonnet]
}
})
]
})
generate({
model: claude35Sonnet,
prompt: 'banana',
config: {
location: 'us-east5',
}
})
```
> feat: allow overriding location per request in vertex ai plugin

- js/plugins/vertexai/src/vector-search/bigquery.ts
- js/plugins/vertexai/tests/vector-search/bigquery_test.ts
- js/testapps/vertexai-vector-search-bigquery/src/index.ts
- js/testapps/vertexai-vector-search-custom/src/index.ts
- js/testapps/vertexai-vector-search-firestore/src/index.ts
When metadata was null in the BQ table, it was failing the parse check.
Also update the samples to use the correct interface name.
> fix: handle null metadata docs in bq retriever

- docs/plugins/firebase.md
This is an attempt to fix the broken rendering of the `httpsOptions` code snippet in on this page: https://firebase.google.com/docs/genkit/plugins/firebase
This is related to #739.
> Fix broken rendering of code snippet on DevSite

- .npmrc
- genkit-tools/package.json
- js/package.json
- package.json
https://github.com/pnpm/pnpm/releases/tag/v9.7.0
Also sets the new [`manage-package-manager-versions`](https://pnpm.io/npmrc#manage-package-manager-versions) option to `true` in .npmrc to have pnpm automatically install the specified version in package.json to prevent weird installation issues (woot!).
> chore: update to pnpm v9.7

- js/plugins/dotprompt/src/template.ts
Confirmed that Next.js HMR will work with partials after this change.
> Persist Handlebars in global to keep it through HMR. Fixes #744

- genkit-tools/cli/src/commands/eval-flow.ts
- genkit-tools/common/src/eval/localFileEvalStore.ts
- genkit-tools/common/src/server/router.ts
- genkit-tools/common/src/types/apis.ts
- genkit-tools/common/src/types/eval.ts
- genkit-tools/common/tests/eval/exporter_test.ts
- genkit-tools/common/tests/eval/localFileEvalStore_test.ts
- js/testapps/cat-eval/src/index.ts
Changes `actionId` to `actionRef`, stores the full action path. Must be submitted along with https://github.com/FirebasePrivate/genkit-ui/pull/1001
> [Eval] Breaking change -- Modify EvalRunKey

- js/ai/src/generate.ts
- js/ai/src/model.ts
- js/ai/tests/generate/generate_test.ts
- js/plugins/vertexai/src/openai_compatibility.ts
- js/testapps/flow-simple-ai/src/index.ts
Fixes #814 and also fixes a nasty regression with the new `generateAction` that caused `response.toHistory()` to stop working.
There's still an issue with tool calling and `toHistory`, which is that the tool request / responses are elided from history once the LLM comes back with a full response. We should fix that.
> Makes inputSchema optional for tools.

- js/ai/src/prompt.ts
- js/ai/tests/prompt/prompt_test.ts
- js/plugins/dotprompt/src/prompt.ts
- js/testapps/dev-ui-gallery/src/main/prompts.ts
This fixes the bug reported in https://github.com/firebase/genkit/issues/422 where `renderPrompt` does not preserve the output schema that the prompt function returns.
This also fixes the bug reported in https://github.com/firebase/genkit/issues/757 where `Dotprompt.render()` only accepts default options. With this change, the `render` and `generate` methods will accept any options, unless a model is also passed in the method, in which case it requires the custom options defined by that model.
> Fixing bugs in prompt rendering

- docs/models.md
- js/plugins/vertexai/src/imagen.ts
- js/plugins/vertexai/src/index.ts
Also adds Imagen3 and Imagen3 Fast. Both are currently allowlist only - I'm still waiting access to try these specific models.
> [JS] Support multiple imagen models in VertexAI

- docs/plugins/firebase.md
- docs/plugins/google-cloud.md
- js/flow/src/firestoreStateStore.ts
- js/plugins/firebase/src/firestoreTraceStore.ts
- js/plugins/firebase/src/index.ts
- js/plugins/google-cloud/package.json
- js/plugins/google-cloud/src/gcpLogger.ts
- js/plugins/google-cloud/src/gcpOpenTelemetry.ts
- js/plugins/google-cloud/src/index.ts
- js/plugins/vertexai/src/index.ts
- js/pnpm-lock.yaml
- js/testapps/cat-eval/package.json
- js/testapps/cat-eval/src/index.ts
- js/testapps/cat-eval/src/pdf_rag_firebase.ts
- js/testapps/cat-eval/src/setup.ts
Allow customers to pass Google Service Account credentials directly via an environment variable following https://github.com/googleapis/google-auth-library-nodejs?tab=readme-ov-file#loading-credentials-from-environment-variables
Updated the cat-eval example to validate Firestore, GCloud, and Vertex
Added docs around the new option to pass in credentials directly via environment variable
> Provide service account creds to gcloud from environment variables

- js/plugins/dotprompt/src/prompt.ts
Rendering dotprompts in a new trace span for better observability.
> Rendering dotprompts in a new trace span

- js/ai/tests/generate/generate_test.ts
- js/plugins/dotprompt/src/template.ts
- js/plugins/dotprompt/tests/prompt_test.ts
There was a bug in the handling of Dotprompt's history rendering such that if a system message (and only a system message) was rendered, history would be inserted in a weird order. The new behavior adds a check:
- If the last message is a `user` role message, insert history just before it.
- Otherwise, append history to the end of the list of messages.
> Fixes history rendering of Dotprompt system role.

- js/core/src/reflectionApi.ts
Will make it easier on the front-end to know definitively when a trace wasn't found, versus an error.
> Return a proper 400 error when a trace is not found in the trace store

- .github/workflows/formatter.yml
- .github/workflows/tests.yml
We shouldn't be hard-coding pnpm version in the workflow config, it will automatically use the correct version based on the `packageManager` field in package.json.
> chore: fix pnpm version used in workflows

- js/core/src/tracing/instrumentation.ts
This can be called multiple times when running child flows.
> Updates isRoot logic to no longer assume root when calling newTrace.

- docs/rag.md
Yesterday I was running a the docs example and this lib was missing from the tutorial!
> fix: rag docs missing lib

- go/plugins/ollama/embed.go
- go/plugins/ollama/embed_test.go
- go/samples/rag/main.go
> feat(go): Add ollama embeddings support

- docs/nextjs.md
This is a bit picky, but when I copied the example `page.tsx` from https://firebase.google.com/docs/genkit/nextjs I found I had some linter errors in my editor.
I have updated the example code to:
* more closely match React style (`varName` and `setVarName` for `useState`)
* reflect good practices in forms (using `htmlFor` for labels)
I also added some spacing to the button, to make it easier to see.
- [] `N/A` Tested (manually, unit tested, etc.)
- [] `N/A` Changelog updated
> Updates example code for Next.js in docs

- js/plugins/googleai/src/gemini.ts
- js/pnpm-lock.yaml
- js/testapps/basic-gemini/package.json
- js/testapps/basic-gemini/src/index.ts
- js/testapps/basic-gemini/tsconfig.json
This is a workaround for an issue with the Google AI Gemini API - aiming to resolve https://github.com/firebase/genkit/issues/703
In this PR we disable explicit json mode (adding responseMimeType to the request) if tools are specified.
This stops the error, but Gemini doesn't seem to call declared functions if Genkit provides a schema.
> fix(js): disabled explicit json mode when using tools

- js/plugins/google-cloud/src/telemetry/generate.ts
- js/plugins/google-cloud/tests/logs_test.ts
Ported from https://github.com/firebase/genkit/pull/834 after https://github.com/firebase/genkit/pull/866.
> Add usage and safety score logs for output candidates

- js/plugins/google-cloud/src/utils.ts
- js/plugins/google-cloud/tests/metrics_test.ts
When running locally, there is a parent `dev-run-action-wrapper` span, and this results in an extracted flow name that looks like `dev-run-action-wrapper/{<flowName>`.
> Update the flow name extraction regex to support the scenario where there is a parent span.

- js/plugins/google-cloud/package.json
- js/plugins/google-cloud/src/telemetry/generate.ts
- js/pnpm-lock.yaml
There's no guarantee each character is exactly 2 bytes, so our previous truncation logic did not work for large messages containing a lot of unicode characters.
Although @google-cloud/logging-winston uses the default maxEntrySize of 250k, when all of those characters are in a single json field, it was still not truncating.
> Truncate logs based on utf bytes instead of characters. 

- js/plugins/vertexai/package.json
- js/plugins/vertexai/src/gemini.ts
- js/pnpm-lock.yaml
- js/testapps/basic-gemini/package.json
- js/testapps/basic-gemini/src/index.ts
This PR adds JSON mode to Vertex AI plugin.
Note that Vertex AI has the same limitation of not supporting tool calling/function calling and json mode at the same time.
Note this bumps @google-cloud/vertexai and google-auth-library in the plugin.
> feat(js): Vertex AI plugin JSON mode

- docs/monitoring.md
Replacing obsolete package name in documentation to current version [genkit-ai/firebase](https://www.npmjs.com/package/@genkit-ai/firebase)
> fix(docs): replace obsolete package name (Firebase plugin)

- js/plugins/google-cloud/src/gcpOpenTelemetry.ts
- js/plugins/google-cloud/tests/traces_test.ts
Adding a new "failedSpan" attribute on flow step or action spans which have failed. This makes it much easier for the GCP trace api to find them.
> Labeling failed spans

- genkit-tools/common/package.json
- genkit-tools/pnpm-lock.yaml
- js/core/package.json
- js/flow/package.json
- js/plugins/firebase/package.json
- js/pnpm-lock.yaml
- js/testapps/anthropic-models/package.json
- js/testapps/basic-gemini/package.json
- js/testapps/docs-menu-basic/package.json
- js/testapps/google-ai-code-execution/package.json
- js/testapps/vertexai-vector-search-bigquery/package.json
- js/testapps/vertexai-vector-search-custom/package.json
- js/testapps/vertexai-vector-search-firestore/package.json
- samples/chatbot/server/package.json
- samples/js-angular/server/package.json
- samples/prompts/package.json
Addresses the following security vulns:
https://github.com/expressjs/express/security/advisories/GHSA-qw6h-vgh9-j6wx
https://github.com/expressjs/express/security/advisories/GHSA-rv95-896h-c2vc
> chore: update express to 4.21.0

- js/plugins/vertexai/src/index.ts
- js/plugins/vertexai/src/model_garden.ts
- js/testapps/flow-simple-ai/src/index.ts
- [ x ] Tested (manually, unit tested, etc.)
> feat(js): add llama-3.2 support to model garden plugin

- js/plugins/google-cloud/package.json
- js/pnpm-lock.yaml
Has critical fixes for supporting bundlers such as es-build
Fixes #937
> Set min version for cloud-trace-exporter to 2.4.1

- docs/plugins/vertex-ai.md
- js/plugins/vertexai/src/imagen.ts
```ts
const baseImg = fs.readFileSync('base.png', { encoding: 'base64' });
const maskImg = fs.readFileSync('mask.png', { encoding: 'base64' });
const response = await generate({
model: imagen3,
output: { format: 'media' },
prompt: [
{ media: { url: `data:image/png;base64,${baseImg}` }},
{
media: { url: `data:image/png;base64,${maskImg}` },
metadata: { type: 'mask' },
},
{ text: 'replace the background with foo bar baz' },
],
config: {
editConfig: {
editMode: 'outpainting',
},
},
});
return response.media();
```
> feat: added support for image editing and upscaling for imagen3

- js/plugins/googleai/src/gemini.ts
- js/plugins/vertexai/src/gemini.ts
- js/testapps/basic-gemini/src/index.ts
This PR fixes a regression introduced with strict JSON mode on Gemini plugins (Google AI and Vertex AI plugins)
Should fix https://github.com/firebase/genkit/issues/958 in main
> fix(js): fix streaming json mode in gemini plugins

- js/plugins/googleai/src/gemini.ts
- js/plugins/googleai/src/index.ts
- js/plugins/vertexai/src/gemini.ts
PR does the following:
- Adds support for Gemini 1.5 Flash 8B to the Google AI plugin
- Adds all available versions to all Gemini models in the Google AI plugin based on https://ai.google.dev/gemini-api/docs/models/gemini
- Adds all available versions to all Gemini models in the Vertex AI plugin based on https://cloud.google.com/vertex-ai/generative-ai/docs/learn/models
Tested Gemini 1.5 Flash 8B manually in the DevUI and it works based on test apps: https://screenshot.googleplex.com/ryTsEwLtx4J2Amc
> Added support for Gemini 1.5 Flash 8B and updated available versions for Google AI and Vertex AI Gemini models

- js/plugins/vertexai/src/reranker.ts
This PR prevents rerankers from throwing if no options are provided to the vertex ai plugin.
> fix(js): fix no pluginOptions logic in vertexai rerankers

- docs/get-started.md
Duplicate of the changes originally made in https://github.com/firebase/genkit/pull/953 but for main.
> Revamp get started docs

- genkit-tools/common/src/types/model.ts
- genkit-tools/genkit-schema.json
- js/ai/src/model.ts
Brings the genkit-tools version of models up to date with the `js/ai/src/model.ts` changes from https://github.com/firebase/genkit/pull/959.
Part 1 of addressing https://github.com/firebase/genkit/issues/960. Dev UI PR to be merged right after this.
> chore(js): update genkit-tools types to align with candidate changes

- js/core/src/flow.ts
- js/core/tests/flow_test.ts
- js/genkit/src/genkit.ts
this allows:
```ts
ai.defineFlow('banana', () => {
return 'banana'
})
```
vs 
```ts
ai.defineFlow({ name: 'banana' }, async () => {
return 'banana'
})
```
> feat: simplified syntax for defining super-simple flows

- js/plugins/ollama/package.json
- js/plugins/ollama/src/embeddings.ts
- js/plugins/ollama/src/index.ts
- js/plugins/ollama/tests/embedding_live_test.ts
- js/plugins/ollama/tests/embeddings_test.ts
This PR adds Ollama embeddings into the plugin on `next`
> feat(js/plugins/ollama): add ollama embeddings back in (after rollback)

- js/core/src/action.ts
- js/core/src/tracing/instrumentation.ts
- js/core/src/tracing/types.ts
- js/core/src/utils.ts
- js/plugins/google-cloud/src/gcpOpenTelemetry.ts
- js/plugins/google-cloud/src/telemetry/action.ts
- js/plugins/google-cloud/src/telemetry/feature.ts
- js/plugins/google-cloud/src/telemetry/generate.ts
- js/plugins/google-cloud/src/telemetry/path.ts
- js/plugins/google-cloud/src/utils.ts
- js/plugins/google-cloud/tests/logs_no_io_test.ts
- js/plugins/google-cloud/tests/logs_test.ts
- js/plugins/google-cloud/tests/metrics_test.ts
Enabling top level actions such as prompts or generate calls to be used for telemetry as effectively as those wrapped in flows.
- Switching actions to use newTrace, which starts a trace similar to a flow if it is not currently inside something.
- Improving instrumentation to always assign a feature name
- Renaming metric dimensions from flowName -> featureName
> Using features in telemetry

- js/ai/src/model.ts
Counts input multimedia content when provided via a `data:<mediaType>:<encoded>` URL
> Update I/O multimedia usage counters to support input data URIs

- js/plugins/ollama/package.json
- js/plugins/ollama/src/embeddings.ts
- js/plugins/ollama/src/index.ts
- js/plugins/ollama/tests/embeddings_live_test.ts
- js/plugins/ollama/tests/embeddings_test.ts
- js/pnpm-lock.yaml
This PR adds ollama embeddings back in after a merge error/rollback
> feat(js/plugins/ollama): restore Ollama embeddings feature on main

- genkit-tools/cli/src/commands/init/init-go.ts
- genkit-tools/cli/src/commands/init/init-nodejs.ts
> chore: pin package versions in `genkit init` in prep for next release

- js/plugins/google-cloud/src/telemetry/action.ts
- js/plugins/google-cloud/tests/metrics_test.ts
- Always using top level feature name for action metrics
- Fixing spurious error logging
> Marking the correct feature when failing in subflows

- js/plugins/google-cloud/src/telemetry/action.ts
- js/plugins/google-cloud/tests/logs_test.ts
- js/plugins/google-cloud/tests/metrics_test.ts
- Adding input and output logs for tool calls.
- Restoring skipped action tests
> Logging I/O for tool spans

- js/core/src/action.ts
- js/genkit/src/genkit.ts
Prune the session state from the input just prior to validation (at the action level), similar to what we're doing for rendering prompts.
See also:
https://github.com/firebase/genkit/blob/next/js/plugins/dotprompt/src/prompt.ts#L182-L198
> Fix action schema validation

- js/plugins/google-cloud/src/gcpOpenTelemetry.ts
For logs written during span export in the GCP plugin, these default Otel trace fields are incorrect because the log is being written at a different time than during span execution.
> Clear trace metadata from logs not used by GCP plugin.

- js/ai/package.json
- js/ai/src/extract.ts
- js/ai/src/formats/array.ts
- js/ai/src/formats/enum.ts
- js/ai/src/formats/index.ts
- js/ai/src/formats/json.ts
- js/ai/src/formats/jsonl.ts
- js/ai/src/formats/text.ts
- js/ai/src/formats/types.d.ts
- js/ai/src/generate.ts
- js/ai/src/index.ts
- js/ai/tests/extract_test.ts
- js/ai/tests/formats/array_test.ts
- js/ai/tests/formats/enum_test.ts
- js/ai/tests/formats/json_test.ts
- js/ai/tests/formats/jsonl_test.ts
- js/ai/tests/formats/text_test.ts
- js/core/src/registry.ts
This is the first PR in a series that will work toward #708, which has now been updated with a work plan for the various pieces that need to go into it..
@galihlprakoso FYI -- this feature is pretty big and consequential and has been on my list to work through for a long time. I appreciate the contribution (and would love if you can find more things you want to add!) but I'm going to implement custom formats directly since there's a lot of complex interaction between various parts of the library.
In this PR I've added a new interface for custom formats and implemented several default formats but haven't yet integrated it with `generate` or the broader ecosystem. It is well-tested though.
> [JS] Adds custom format implementations. #708 part 1

- js/ai/src/generate.ts
- js/ai/src/index.ts
- js/ai/src/message.ts
- js/ai/tests/generate/generate_test.ts
- js/ai/tests/message/message_test.ts
- js/genkit/src/session.ts
- js/genkit/tests/generate_test.ts
Also standardizes on Message.parse and Message.parseContent for coercing lenient options into proper form.
> Refactors Message into its own file

- js/genkit/src/genkit.ts
When wrapping prompt actions as ExecutablePrompt, we need to include the model in the options. This is because the PromptAction returns GenerateRequest, which in turn does not actually include model. This is particularly a problem for dotprompt files.
- [NA] Docs updated
cc @pavelgj 
Fixes #1119
> Include model in options for executable prompts

- js/plugins/vertexai/package.json
- js/plugins/vertexai/src/gemini.ts
- js/pnpm-lock.yaml
This PR is to add https://github.com/firebase/genkit/pull/890/files and sync next with main.
I will open a new PR to support passing a schema to the API.
> feat(js/plugins/vertexai): support resposeMimeType in next

- genkit-tools/common/src/manager/manager.ts
- genkit-tools/common/src/manager/types.ts
- genkit-tools/common/src/server/server.ts
- genkit-tools/common/src/types/apis.ts
- genkit-tools/common/src/types/index.ts
- [N/A] Docs updated
cc @tonybaroneee
> Add endpoint for the Dev UI to subscribe to runtime updates

- js/plugins/google-cloud/src/gcpLogger.ts
When deployed on Cloud Run, the winston logger stops sending logs after a connection error.
This change creates a new logger when the error handler detects a problem.
> Re-initializing GCP logger after it experiences a failure.

- genkit-tools/common/src/utils/utils.ts
- go/genkit/genkit.go
- go/genkit/servers.go
- go/genkit/servers_test.go
> [Go] Implemented new runtime discovery behavior.

- js/ai/src/generate.ts
> Factors out some standalone functions to simplify generate()

- js/plugins/google-cloud/src/telemetry/generate.ts
When calling a model with a structured output schema, the data goes into the `part` field.
> Add support for logging data or custom responses from LLMs

- js/ai/src/generate.ts
- js/genkit/tests/generate_test.ts
> fix: handle (and rethrow) exceptions during `generateStream`

- js/genkit/src/chat.ts
- js/genkit/src/session.ts
- js/genkit/tests/chat_test.ts
- js/genkit/tests/generate_test.ts
- js/genkit/tests/session_test.ts
- js/package.json
```ts
const chat = session.chat({ preamble: agent });
```
Fixes #1117
> chore: rename 'prompt' to 'preamble' in chat

- js/ai/src/generate.ts
- js/ai/src/generate/action.ts
- js/ai/src/model.ts
- js/ai/src/tool.ts
- js/testapps/format-tester/src/tools.ts
Extracts `resolveModel` into a common helper in `model.ts`, use `resolveTools` instead of duplicating tool resolution.
> Reduce duplicate codepaths for resolving models and tools.

- js/ai/src/index.ts
- js/ai/src/prompt.ts
- js/genkit/src/chat.ts
- js/genkit/src/genkit.ts
- js/genkit/src/session.ts
- js/genkit/tests/chat_test.ts
- js/genkit/tests/session_test.ts
```ts
const chat = ai.chat(agent);
const chat = ai.chat(agent, {
input: ...
});
const chat = session.chat(agent);
const chat = session.chat(agent, {
input: ...
});
const chat = session.chat('thread', agent, {
input: ...
});
```
> feat: updated syntax for creating preamble/agent chat

- js/ai/src/chat.ts
- js/ai/src/session.ts
- js/genkit/src/genkit.ts
- js/genkit/tests/chat_test.ts
- js/genkit/tests/prompts_test.ts
Parent PR: https://github.com/firebase/genkit/pull/1215
```ts
const greeting = ai.definePrompt(
{ name: 'greeter' },
`{{ role "system"}} user's name is {{ @state.userName}}. Important: greet them by this name.`
);
(async () => {
const session = ai.createSession({
initialState: {
userName: 'Pavel',
},
});
let chat = session.chat(greeting);
let response = await chat.send('hi');
console.log(response.text); // hi Pavel
await session.updateState({
userName: 'Chris',
})
chat = session.chat(greeting); // <----- important: causes the preamble to refresh
response = await chat.send('hi');
console.log(response.text); // hi Chris
})();
```
Fixes: #1116
> fix: reload the preamble every time a 'fresh' chat session is created

- js/ai/package.json
- js/ai/src/chat.ts
- js/ai/src/model.ts
- js/ai/src/session.ts
- js/core/src/action.ts
- js/genkit/package.json
- js/genkit/src/genkit.ts
- js/genkit/src/index.ts
- js/genkit/tests/chat_test.ts
- js/genkit/tests/prompts/toolPrompt.prompt
- js/genkit/tests/prompts_test.ts
- js/plugins/dotprompt/src/metadata.ts
- js/plugins/dotprompt/src/prompt.ts
- js/plugins/dotprompt/src/registry.ts
- js/pnpm-lock.yaml
> fix: fixed prompt file descriptions and namespacing to unblock use as tool

- docs/dotprompt.md
- docs/flows.md
> docs: genkit start is back

- js/ai/src/prompt.ts
- js/genkit/src/genkit.ts
- js/genkit/tests/prompts_test.ts
- js/testapps/flow-simple-ai/src/index.ts
- js/testapps/menu/src/02/flows.ts
- js/testapps/menu/src/04/flows.ts
- js/testapps/menu/src/05/flows.ts
- js/testapps/prompt-file/src/index.ts
- js/testapps/rag/src/pdf_rag.ts
- js/testapps/rag/src/simple_rag.ts
unnecessary/redundant as everything can be done with ()/.stream()
> chore: removed generate/generateStream from executable prompts

- genkit-tools/common/src/server/router.ts
IDX does not currently support SSE (text/stream) via its proxy. We will poll for runtime(s) via dev ui for now.
> Add new endpoint to trpc for polling runtime status from dev ui

- docs/plugins/ollama.md
- js/plugins/ollama/package.json
- js/plugins/ollama/src/embeddings.ts
- js/plugins/ollama/src/index.ts
- js/plugins/ollama/src/types.ts
- js/plugins/ollama/tests/embedding_live_test.ts
- js/plugins/ollama/tests/embeddings_test.ts
- js/pnpm-lock.yaml
- js/testapps/ollama/README.md
- js/testapps/ollama/package.json
- js/testapps/ollama/src/index.ts
- js/testapps/ollama/tsconfig.json
This PR is to resolve https://github.com/firebase/genkit/issues/1080
It also updates the plugin to use the `/embed` endpoint, which allows batches
> fix(js/plugins/ollama): fix ollama embedding config

- docs/plugins/firebase.md
- docs/plugins/google-cloud.md
> Update firebase and google-cloud plugin docs

- docs/evaluation.md
- docs/get-started.md
- docs/rag.md
- docs/tool-calling.md
> docs: some 0.9 updates

- js/plugins/vertexai/src/evaluation/index.ts
- js/plugins/vertexai/src/evaluation/types.ts
- js/plugins/vertexai/src/modelgarden/index.ts
- js/plugins/vertexai/src/modelgarden/types.ts
- js/plugins/vertexai/src/rerankers/index.ts
- js/plugins/vertexai/src/rerankers/reranker.ts
- js/plugins/vertexai/src/rerankers/types.ts
- js/testapps/anthropic-models/src/index.ts
- js/testapps/dev-ui-gallery/src/genkit.ts
- js/testapps/format-tester/src/index.ts
- js/testapps/model-tester/src/index.ts
- js/testapps/rag/src/genkit.ts
- js/testapps/vertexai-reranker/src/index.ts
```ts
vertexAIModelGarden({
location: 'us-central1',
models: [claude3Sonnet, llama31],
}),
vertexAIEvaluation({
location: 'us-central1',
metrics: [
VertexAIEvaluationMetricType.BLEU,
VertexAIEvaluationMetricType.GROUNDEDNESS,
VertexAIEvaluationMetricType.SAFETY,
{
type: VertexAIEvaluationMetricType.ROUGE,
metricSpec: {
rougeType: 'rougeLsum',
useStemmer: true,
splitSummaries: 'true',
},
},
],
}),
vertexAIRerankers({
projectId: PROJECT_ID,
location: LOCATION,
rerankers: ['vertexai/reranker'],
}),
```
> fix: simplified vertex plugin APIs

- js/core/src/tracing/instrumentation.ts
- js/plugins/firebase/src/user_engagement.ts
- js/plugins/firebase/tests/user_engagement_test.ts
- js/plugins/google-cloud/tests/logs_test.ts
- js/plugins/google-cloud/tests/metrics_test.ts
- js/plugins/google-cloud/tests/traces_test.ts
- js/testapps/firebase-functions-sample1/functions/src/index.ts
Avoid race condition when appending a span by waiting for telemetry initialization.
> Avoid race condition in user engagement collection

- docs/firebase.md
- docs/monitoring.md
- js/plugins/vertexai/src/gemini.ts
This PR updates the docs after upgrading to 0.9.0:
1. Since the firebase emulator and the genkit UI uses by default the same port (4000), it is better to start first the genkit UI and then the firebase emulator. The firebase emulator autodetect that the port 4000 is in use and uses another one.
2. Added the npm command provided by the firebase template `npm run genkit:start`
3. fixes this visualization problem: https://firebase.google.com/docs/genkit/monitoring#trace_storage_and_developer_ui
> fix: firebase documentation after 0.9 upgrade

- js/ai/src/formats/index.ts
- js/ai/src/generate.ts
- js/ai/src/generate/action.ts
- js/genkit/tests/prompts_test.ts
```ts
import { gemini15Flash, googleAI } from '@genkit-ai/googleai';
import { genkit, z } from 'genkit';
const ai = genkit({
plugins: [googleAI()],
model: gemini15Flash,
});
const MenuItemSchema = z.object({
dishname: z.string(),
description: z.string(),
});
const helloFlow = ai.defineFlow('hello', async (restaurantTheme) => {
const { output } = await ai.generate({
model: gemini15Flash,
prompt: `Invent a menu item for a ${restaurantTheme} themed restaurant.`,
output: {
// format: 'json', //// <------ SHOULD NOT BE REQUIRED
schema: MenuItemSchema,
},
});
return output;
});
(async () => {
console.log(await helloFlow('banana'));
})();
```
> fix: default to json format if not explicitly specified

- js/doc-snippets/src/flows/index.ts
> docs: Update streaming flows snippet

- js/ai/src/session.ts
- js/genkit/tests/chat_test.ts
> fix(js/ai): pass chat messages to premable prompt to correctly render history

- genkit-tools/common/src/manager/manager.ts
- genkit-tools/common/src/manager/types.ts
- genkit-tools/common/src/utils/utils.ts
- genkit-tools/common/tests/utils/utils_test.ts
We'll show project name in the breadcrumbs on the dev ui (my-ai-app in the screenshot below).
- [na] Changelog updated
- [na] Docs updated
> Return project name with runtime info

- js/core/src/flow.ts
- js/core/tests/flow_test.ts
> fix: correctly pass auth when invoking streaming flow

- genkit-tools/package.json
- genkit-tools/pnpm-lock.yaml
- js/package.json
- js/pnpm-lock.yaml
- package.json
- pnpm-lock.yaml
Fixes:
- https://github.com/firebase/genkit/security/dependabot/38
- https://github.com/firebase/genkit/security/dependabot/37
- https://github.com/firebase/genkit/security/dependabot/36
- https://github.com/firebase/genkit/security/dependabot/35
- https://github.com/firebase/genkit/security/dependabot/34
- https://github.com/firebase/genkit/security/dependabot/33
- https://github.com/firebase/genkit/security/dependabot/32
> chore: force-upgrade cross-spawn dep to address security vulns

- tests/package.json
- tests/pnpm-lock.yaml
Missed this top-level pacjage from the last PR.
Fixes https://github.com/firebase/genkit/security/dependabot/38.
> Set cross-spawn version override in `tests/`

- README.md
Remove genkit init from the Readme
> fix: Remove genkit init from README

- go/plugins/dotprompt/genkit.go
- go/plugins/dotprompt/genkit_test.go
Cherrypicks 486dc9d181876c89e2c829d56096b5ee210ba775 that was overwritten when we reset `main` to `next`.
> [Go] Fix model name lookup in dotprompt.

- js/core/src/action.ts
- js/core/src/reflection.ts
- js/core/tests/action_test.ts
- js/genkit/src/index.ts
> feat: added a way to run action with telemetry, no more 'dev-run-action-wrapper'

- js/ai/src/formats/index.ts
- js/genkit/package.json
- js/genkit/src/formats.ts
- js/genkit/src/genkit.ts
- js/genkit/tests/formats_test.ts
```ts
ai.defineFormat(
{
name: 'banana',
format: 'banana',
},
(schema) => {
let instructions: string | undefined;
if (schema) {
instructions = `Output should be in banana format`;
}
return {
parseChunk: (chunk) => {
return `banana: ${chunk.content[0].text}`;
},
parseMessage: (message) => {
return `banana: ${message.content[0].text}`;
},
instructions,
};
}
);
```
> feat: expose defineFormat on Genkit instance, allowing to define custom formats

- docs-go/get-started-go.md
Fixes #1373 , replacing `npm i -g genkit` with  `npm i -g genkit-cli
> doc: update cli installation

- js/genkit/src/genkit.ts
- js/genkit/tests/prompts/test.variant.prompt
- js/genkit/tests/prompts_test.ts
> fix(js/genkit): properly look up prompt variants

- js/plugins/google-cloud/src/telemetry/generate.ts
- js/plugins/google-cloud/tests/metrics_test.ts
Removing the numerical dimensions from generation metrics which are expensive to store and query.
> Removing overly dimensional generate metrics

- docs/auth.md
- docs/evaluation.md
- docs/get-started.md
- docs/plugin-authoring-evaluator.md
Fixed:
- formatting in intro
- broken link 
- correct target heading [Evaluation](https://firebase.google.com/docs/genkit/evaluation#evaluator_plugins)
Relevant Discord link: https://discord.com/channels/1255578482214305893/1309810547302338570/1309810551223877634
> fix: text formatting in docs

- js/ai/src/generate/action.ts
- js/ai/src/model.ts
- js/ai/src/prompt.ts
- js/ai/src/reranker.ts
- js/ai/src/retriever.ts
- js/core/src/action.ts
- js/core/tests/action_test.ts
```ts
const act = action(
{
name: 'foo',
inputSchema: z.string(),
outputSchema: z.number(),
},
async (input, { sendChunk, context }) => {
checkAuth(context);
sendChunk(1);
sendChunk(2);
sendChunk(3);
return input.length;
}
);
const chunks: any[] = [];
await act('1234', {
context: { user: 'pavel' },
onChunk: (c) => chunks.push(c),
});
```
> feat(js/core): added a way to run actions with side-channel data and streaming

- js/plugins/googleai/src/gemini.ts
- js/plugins/googleai/tests/gemini_test.ts
- js/plugins/vertexai/src/gemini.ts
- js/plugins/vertexai/tests/gemini_test.ts
Zod schema like this:
```ts
schema: z.object({
title: z.string(),
subtitle: z.string().nulish(),
}),
```
and  picoschema like this:
```yaml
output:
schema:
title: string
subtitle?: string
```
produce schema:
```json
{
"type": "object",
"properties": {
"title": {
"type": "string"
},
"subtitle": {
"type": [
"string",
"null"
]
}
},
"required": [
"title"
],
"additionalProperties": false
}
```
which is not a valid schema in Gemini API request for constrained generation.
```
status: 400,
statusText: 'Bad Request',
errorDetails: [
{
'@type': 'type.googleapis.com/google.rpc.BadRequest',
fieldViolations: [
{
field: 'generation_config.response_schema.properties[1].value',
description: `Invalid JSON payload received. Unknown name "type" at 'generation_config.response_schema.properties[1].value': …
```
> fix: fixed gemini model handling of nullish optional fields in response schema

- genkit-tools/cli/src/commands/start.ts
> fix(cli): fixed `genkit start` port option to accept the port value

- genkit-tools/common/src/types/model.ts
- genkit-tools/genkit-schema.json
- js/ai/src/generate.ts
- js/ai/src/generate/action.ts
- js/ai/src/model.ts
- js/ai/src/tool.ts
- js/ai/tests/generate/generate_test.ts
- js/genkit/src/genkit.ts
- js/testapps/flow-simple-ai/src/index.ts
Tested both with a unit test and by running a namespaced tool through the `flow-simple-ai` testapp.
> fix(js/ai): Fixes use of namespaced tools in model calls.

- docs/plugins/vertex-ai.md
Imagen3 is also supported by [Models supported by Genkit](https://firebase.google.com/docs/genkit/models#models-supported) but missing in the plugin detail.
> docs: add imagen3 to supported Vertex AI services

- docs/evaluation.md
- docs/templates/pgvector.md
- docs/tool-calling.md
This seems to be a typo - the npm package is hosted at https://www.npmjs.com/package/@genkit-ai/googleai.
> fix: googleai import typo in docs

- docs/evaluation.md
- genkit-tools/cli/src/commands/eval-extract-data.ts
- genkit-tools/cli/src/commands/eval-flow.ts
- genkit-tools/cli/src/commands/flow-batch-run.ts
- genkit-tools/common/src/eval/evaluate.ts
- genkit-tools/common/src/eval/localFileDatasetStore.ts
- genkit-tools/common/src/types/eval.ts
- genkit-tools/common/tests/eval/localFileDatasetStore_test.ts
- js/testapps/evals/data/cat_adoption_questions.json
- js/testapps/evals/data/cat_adoption_questions_with_reference.json
This PR implements the changes discussed with AIM to support a more coherent dataset IO format.
Changes:
- `{samples: [{input, reference}]}`  is no longer a valid format. All IO will be using `[{input, reference}]`.
- As a consequence `any[]` is not allowed anymore. i.e. users cannot use an array of inputs for evals. They have to use the format above.
- On the upside, the result of `eval:extractData` can be used for both `eval:run` and `eval:flow`. (In other words, `eval:flow` input format is a strict subset of `eval:run` input format -- which is the same as the output format of `eval:extractData`). Users can use the same `.json` file for multiple evaluation tasks, provided they have the right fields present.
- Formats like JSONL can be supported as a follow-up.
> feat(evals): New data format for evals IO

- .gitignore
- js/plugins/checks/README.md
- js/plugins/checks/src/evaluation.ts
Update checks evaluators to return multiple results, one per requested policy. 
> feat(js/plugins/checks): checks evaluator plugin returns multiple scores

- README.md
Deprecating Discussions in favor of Discord
> docs: remove reference to Discussions

- js/core/src/action.ts
- js/core/src/context.ts
- js/core/src/flow.ts
- js/core/src/index.ts
- js/core/tests/flow_test.ts
- js/plugins/express/tests/express_test.ts
```ts
const myFlow = ai.defineFlow(
{
name: 'myFlow',
inputSchema: z.string(),
outputSchema: z.string(),
},
async (input, { sendChunk, context }) => {
sendChunk(1);
sendChunk(2);
sendChunk(3);
return `${input} ${JSON.stringify(context)}`;
}
);
```
old way still works
```ts
const myFlow = ai.defineFlow(
{
name: 'myFlow',
inputSchema: z.string(),
outputSchema: z.string(),
},
async (input, sendChunk) => {
sendChunk(1);
sendChunk(2);
sendChunk(3);
return `${input} ${JSON.stringify(getFlowAuth())}`;
}
);
```
- [IOU] Docs updated (updated docs or a docs bug required)
> feat: turned flow second param into a destructurable side channel object (backwards compatible)

- docs/flows.md
docs: Prepends import statement to code snippet imported via includecode widget.
> docs: prepends import statement to code snippet imported via includecode widget.

- js/plugins/googleai/src/embedder.ts
- js/plugins/vertexai/src/embedder.ts
- js/plugins/vertexai/src/predict.ts
How to use
```typescript
ai.embed({
embedder: textEmbedding005,
content: 'String to be embedded',
options: {
outputDimensionality: 500 // Between 1 and 768, inclusive
}
})
```
> feat(js/plugins): added custom dimensions parameter to text-embedding

- docs/_guides.yaml
- docs/codelabs/codelab-chat-with-a-pdf.md
This adds a codelab that walks the user through the experience of building a command-line based chat app that allows them to chat with a PDF file.
> docs: add codelab "Chat with a PDF file"

- README.md
The IDX button was using the generic Github import link. This updates the URL to the Genkit template for IDX.
> docs: Point to Genkit template for IDX

- README.md
The samples in the readme were pointing to non-existent locations since the location was migrated to the quickstart-nodejs repo. Migrated the sample links to point to the right location.
> docs: Point samples to new locations

- docs/plugin-authoring-evaluator.md
Fix some errors and mismatched types so that if someone copy/pastes all the code from the doc, it will at least compile and run
> docs(eval): fix evaluator plugin docs so code compiles

- go/genkit/servers.go
- go/samples/flow-sample1/main.go
- go/tests/api_test.go
- go/tests/test_app/main.go
- js/testapps/flow-sample1/src/index.ts
- tests/flow_server_tests.yaml
- tests/package.json
- tests/reflection_api_tests.yaml
- tests/src/flow_server_test.ts
- tests/test_js_app/src/index.ts
OK
```shell
curl -X POST -H "Accept: text/event-stream" http://localhost:3400/streamy -d '{"data":5}'
data: {"count":0}\n\n
data: {"count":1}\n\n
data: {"count":2}\n\n
data: {"count":3}\n\n
data: {"count":4}\n\n
data: {"result": "done: 5, streamed: 5 times"}\n\n
```
ERROR
```shell
curl -X POST -H "Accept: text/event-stream" http://localhost:3400/streamy -d '{"data":5}'                                                                       
data: {"message": {"count":0}}\n\n
data: {"message": {"count":1}}\n\n
data: {"message": {"count":2}}\n\n
data: {"message": {"count":3}}\n\n
data: {"message": {"count":4}}\n\n
data: {"error": {"status": "INTERNAL", "message": "stream flow error", "details": "this is a dummy error"}}\n\n         
```
> breaking(go): update flow streaming protocol to SSE

- js/ai/src/chat.ts
- js/plugins/google-cloud/src/gcpOpenTelemetry.ts
Improves traces that include calls to Chat#send
* Setting helper type
* Adding labels for sessionId and threadName
* Including I/O in send spans
> fix(js): Including missing labels in chat spans

- js/ai/src/formats/index.ts
- js/ai/src/generate.ts
- js/ai/tests/generate/generate_test.ts
- js/core/package.json
- js/core/src/async.ts
- js/genkit/src/genkit.ts
- js/genkit/tests/generate_test.ts
- package.json
Fixes #1593 
Rewrote generateStream so you longer need to call `await` to get the return value of objects that are themselves async.
As a style change I named the struct for {resolve, reject, promise} as Task because that's how I've commonly seen this design called.
The former method for passing into an async generator was a bit fragile because it depended on the exact order of the callbacks to the run loop (in fact, in my refactoring I broke it). Instead I created a buffering utility class called `Channel<T>`, inspired by Go channels but implements `AsyncIterable` for receiving.
I've had to change the copyright script from `ts-node` to `tsx` in many of my PRs because I get import vs require errors trying to load child-process. Since tsx is more officially supported I decided to change …
> [Feat][Js] Make ai.generateStream no longer require a double await

- js/ai/src/generate/action.ts
- js/ai/src/generate/response.ts
- js/ai/tests/generate/response_test.ts
- js/genkit/tests/generate_test.ts
Fixes https://github.com/firebase/genkit/issues/889
> fix(js/ai): skip response schema validation on tool calls

- genkit-tools/common/src/types/model.ts
- genkit-tools/genkit-schema.json
- js/ai/src/generate/action.ts
- js/ai/src/generate/chunk.ts
- js/ai/src/model.ts
- js/ai/tests/formats/array_test.ts
- js/ai/tests/formats/json_test.ts
- js/ai/tests/formats/jsonl_test.ts
- js/ai/tests/formats/text_test.ts
- js/ai/tests/generate/chunk_test.ts
- js/ai/tests/generate/generate_test.ts
- js/genkit/tests/generate_test.ts
- js/plugins/express/tests/express_test.ts
- js/testapps/flow-simple-ai/src/index.ts
> feat(js/ai): stream tools responses

- js/ai/src/chat.ts
- js/plugins/google-cloud/src/gcpLogger.ts
- js/plugins/google-cloud/src/telemetry/action.ts
- js/plugins/google-cloud/src/telemetry/feature.ts
- js/plugins/google-cloud/src/telemetry/generate.ts
- js/plugins/google-cloud/src/telemetry/path.ts
- js/plugins/google-cloud/tests/logs_session_test.ts
- js/plugins/google-cloud/tests/traces_test.ts
- js/pnpm-lock.yaml
To better support observability for chat/sessions in Firebase, add the sessionId and threadName attributes to log entries when present. 
> feat(js): Log sessionId to I/O logs when span attribute is present

- docs/monitoring.md
Remove mentions of Google Cloud plugin from the main observability and monitoring page in order to direct users to using the Firebase plugin. This more closely aligns with Genkit branding.
> Make observability docs more opinionated.

- js/ai/package.json
While trying to write `onCallGenkit` with a hard dependency I came up with the weeeeeirdest compiler error. Genkit couldn't find a deep export from @genkit-ai/ai!
```bash
node_modules/genkit/lib/index-BbHVu_0v.d.ts:10:27 - error TS2307: Cannot find module '@genkit-ai/ai/formats' or its corresponding type declarations.
10 import { Formatter } from '@genkit-ai/ai/formats';
~~~~~~~~~~~~~~~~~~~~~~~
```
Turns out it's because the directory is missing from package.json's typesVersions dictionary.
> fix(js): Fix deep export of @genkit-ai/ai/formats

- genkit-tools/common/src/types/model.ts
- genkit-tools/genkit-schema.json
- js/ai/src/generate/action.ts
- js/ai/src/index.ts
- js/ai/src/model.ts
- js/ai/src/tool.ts
- js/genkit/src/genkit.ts
- js/genkit/src/index.ts
- js/genkit/tests/generate_test.ts
```ts
ai.defineTool(..., (input, {interrupt}) => {
interrupt();
});
```
> feat(js/ai): added a simple way to interrupt tool execution

- docs/plugins/firebase.md
Docs: Replaces internal-only URL with a link accessible to non-Google developers.
> Docs: Update firebase.md

- js/ai/src/generate.ts
- js/ai/src/generate/response.ts
- js/ai/src/index.ts
- js/ai/src/message.ts
- js/ai/src/tool.ts
- js/ai/tests/generate/generate_test.ts
- js/ai/tests/tool_test.ts
- js/core/src/error.ts
- js/core/tests/flow_test.ts
- js/genkit/src/index.ts
```ts
const myInterrupt = ai.defineInterrupt(...);
const response = await ai.generate({tools: [myInterrupt], prompt: "Call myInterrupt"});
const resumedResponse = await ai.generate({
messages: response.messages,
resume: {reply: myInterrupt.reply(response.interrupts[0], "the interrupt response");
});
```
> feat(js/ai): Adds GenerateOptions#resume, ToolAction#reply, Message#interrupts

- genkit-tools/cli/src/commands/eval-flow.ts
- genkit-tools/cli/src/commands/eval-run.ts
- genkit-tools/common/src/eval/evaluate.ts
- genkit-tools/common/src/utils/eval.ts
- js/tsconfig.json
> feat: more specific errors for evals

- js/core/src/async.ts
- js/genkit/tests/generate_test.ts
Fixed this error case:
```ts
const { stream } = ai.generateStream({
prompt: 'hi',
model: 'modelNotFound',
});
for await (const chunk of stream) {
// something
}
```
which was resulting in a hanging generate call.
> fix(js/core/async): reject channel ready promise on channel error

- genkit-tools/common/package.json
- genkit-tools/common/src/eval/index.ts
- genkit-tools/common/src/eval/validate.ts
- genkit-tools/common/src/server/router.ts
- genkit-tools/common/src/types/apis.ts
- genkit-tools/pnpm-lock.yaml
Part of https://github.com/firebase/genkit/issues/1554
This change provides the required API. The Dev UI can use this API to add validation callouts.
> feat: add new API for data validation

- js/plugins/vertexai/src/common/index.ts
- js/plugins/vertexai/src/common/types.ts
- js/plugins/vertexai/src/gemini.ts
- js/plugins/vertexai/src/index.ts
- js/plugins/vertexai/src/modelgarden/mistral.ts
- js/plugins/vertexai/tests/plugin_test.ts
`gemini` model ref helper, consistent with googleAI plugin.
```ts
import { vertexAI, gemini } from '@genkit-ai/vertexai';
const gemini15Flash042 = gemini('gemini-1.5-flash-042');
const ai = genkit({
plugins: [
vertexAI({
models: [gemini15Flash042]
})
],
model: gemini15Flash042
});
await generate('hi')
```
- [iou] Docs updated (updated docs or a docs bug required)
> feat(js/plugins/vertexai): instruduced gemini model ref helper and ability to register versions

- docs/plugins/google-cloud.md
- js/plugins/google-cloud/src/gcpOpenTelemetry.ts
- js/plugins/google-cloud/src/telemetry/action.ts
- js/plugins/google-cloud/src/telemetry/defaults.ts
- js/plugins/google-cloud/src/telemetry/engagement.ts
- js/plugins/google-cloud/src/telemetry/feature.ts
- js/plugins/google-cloud/src/telemetry/generate.ts
- js/plugins/google-cloud/src/telemetry/path.ts
- js/plugins/google-cloud/src/types.ts
- js/plugins/google-cloud/tests/logs_no_input_output_test.ts
IO generally refers to interfaces between a computer and the outside world. Reading/writing from disk, reading/writing from the network, etc (and also of course peripherals like mice, keyboards, monitors, etc). Renaming this removes ambiguity that we are referring to something different.
This *is* technically a breaking change. But I think its a good one, while we have a chance.
> fix(js/plugins/google-cloud)!: rename io to inputAndOutput

- js/plugins/google-cloud/src/telemetry/action.ts
- js/plugins/google-cloud/src/telemetry/engagement.ts
- js/plugins/google-cloud/src/telemetry/feature.ts
- js/plugins/google-cloud/src/telemetry/generate.ts
- js/plugins/google-cloud/src/telemetry/path.ts
- js/plugins/google-cloud/src/utils.ts
- js/plugins/google-cloud/tests/logs_test.ts
GCP limits log lines to 256k. This change truncates the main culprits - input and output - and attempts to truncate paths, model names, and other potential sources contributing to large log lines.
> feat(js): truncate input/output to align with GCP limits

- js/ai/src/prompt.ts
- js/core/tests/schema_test.ts
- js/genkit/tests/prompts/schemaRef.prompt
- js/genkit/tests/prompts_test.ts
it causes description getting sent to the model as:
```
"output": {
"format": "json",
"contentType": "application/json",
"constrained": true,
"schema": {
"type": "object",
"properties": {
"output": {
"type": "string"
}
},
"required": [
"output"
],
"additionalProperties": true,
"$schema": "http://json-schema.org/draft-07/schema#",
"description": {} // <---------
}
}
```
> fix(js/ai/prompt): delete null descriptions returned by dotprompt

- js/core/src/async.ts
- js/genkit/src/client/client.ts
- js/plugins/express/README.md
- js/plugins/express/tests/express_test.ts
- js/plugins/firebase/tests/functions_test.ts
- samples/chatbot/genkit-app/src/app/samples/chatbot/chatbot.component.ts
- samples/js-angular/genkit-app/src/app/samples/chatbot/chatbot.component.ts
- samples/js-angular/genkit-app/src/app/samples/streaming-json/streaming-json.component.ts
- tests/src/flow_server_test.ts
Reconciles the discrepancy between the client and server methods for calling an action so that they both return a Promise/AsyncIterable rather than a method returning those types.
Note for reviewer: we decided to call the firebase functions method "onCallGenkit" because we wanted to support invoking any action. Do we similarly want to rename the client SDK to runAction and streamAction?
- [] Tested (compiles, but **tests fail on main**)
> fix(js)!: client streamFlow returns properties, not functions

- docs/firebase.md
docs: Pre-PR version sends you to install CLI, which tells you to create a project. Then, when you come back, you subsequently get told to create a project again (but with with additional requirements).
This PR improves the UX by fixing this issue.
> docs: Fix out-of-sequence instructions

- docs/rag.md
> fix: rag doc updates

- js/genkit/src/genkit.ts
- js/genkit/tests/prompts_test.ts
will still work....
```ts
const hi = ai.definePrompt({
name: 'hi',
input: {
schema: z.object({
name: z.string(),
}),
},
}, 'hi {{ name }}');
```
> feat(js/ai): improving definePrompt backwards compatibility, to ease the transition

- js/plugins/firebase/src/firestoreRetriever.ts
Code was trying to access `[0]` on the promise, instead of on the result.
> fix(js/plugins/firebase): properly await embedding promise

- samples/js-character-generator/README.md
- samples/js-character-generator/package.json
- samples/js-coffee-shop/README.md
- samples/js-menu/README.md
Remove the button on the individual sample in favor or the button on the overall /samples/ directory.  I'll look at adding the sub-button back, but it might need to wait for a FR in IDX to prevent duplication
- [ x] PR title is following https://www.conventionalcommits.org/en/v1.0.0/
- [ x] Docs updated (updated docs or a docs bug required)
> fix: remove idx subbutton and lint fixes

- js/genkit/package.json
- js/genkit/src/client/client.ts
- js/plugins/express/README.md
- js/plugins/express/tests/express_test.ts
- js/plugins/firebase/tests/functions_test.ts
- js/plugins/next/README.md
- js/plugins/next/src/client.ts
- tests/src/flow_server_test.ts
> chore(js/client): moved client to beta namespace

- js/genkit/src/beta.ts
Bugfix (one-line fix)
Fixes issue #1180 
There is an implicit contract when creating a new session that you can set the sessionId by providing this optional parameter on the `createSession()` options-paramter object.
The implementation of `createSession()` ignores this, and always creates a new uuidv4 as the sessionId.
This PR changes that to prioritize the supplied options.sessionId string - if provided.
However, there might be a bigger problem to address, as the `loadSession()` implementation has a potential "footgun" problem: it both accepts an explicit sessionId function parameter (which will take effect), as well as the same kind of `SessionOptions` object – capable of carrying a `sessionId` property too, which will never be used. Mentioning this as there might be a better an more …
> fix: uses the provided sessionId from session options if provided

- docs/flows.md
- js/doc-snippets/src/flows/index.ts
- js/genkit/src/client/client.ts
- js/genkit/tests/helpers.ts
- js/plugins/express/README.md
- js/plugins/googleai/src/gemini.ts
- js/plugins/vertexai/src/modelgarden/anthropic.ts
- js/plugins/vertexai/src/modelgarden/mistral.ts
- js/plugins/vertexai/src/modelgarden/openai_compatibility.ts
- js/pnpm-lock.yaml
- js/testapps/dev-ui-gallery/src/main/flows.ts
- js/testapps/express/src/index.ts
- js/testapps/flow-sample1/src/index.ts
- js/testapps/flow-simple-ai/src/index.ts
- js/testapps/multimodal/src/pdf.ts
- js/testapps/multimodal/src/video.ts
- js/testapps/prompt-file/src/index.ts
- js/testapps/rag/src/pdf-rag.ts
- samples/js-angular/server/src/jsonStreaming.ts
- samples/js-chatbot/server/src/index.ts
- tests/test_js_app/src/index.ts
Also took the opportunity to update a few samples to use `{ sendChunk }` vs `streamingCallback` and to remove null checks since it's now always present.
A surprising number of samples seemed to have errors where they were streaming raw model chunks instead of calling something like `chunk.text` to coerce it into a wire type
> chore(js): Rename streamingCallback to sendChunk

- docs/interrupts.md
- docs/tool-calling.md
> docs(js): Adds a guide for interrupts.

- samples/idx-template.json
- samples/js-chatbot/README.md
- samples/js-menu/.gitignore
- samples/js-menu/.idx/dev.nix
- samples/js-menu/README.md
- samples/js-menu/package-lock.json
- samples/js-menu/src/index.ts
Adds jsmenu to the IDX samples, also fixes a couple links that pointed internally
This sample can be tested here:
<a href="https://idx.google.com/new?template=https%3A%2F%2Fgithub.com%2Ffirebase%2Fgenkit%2Ftree%2Fupdate-jsmenu-to-use-idx%2Fsamples">
<img
height="32"
alt="Try in IDX"
src="https://cdn.idx.dev/btn/try_light_32.svg">
</a>
> feat: Add dev.nix for js-menu

- docs/evaluation.md
> fix: evaluation.md

- js/ai/src/generate/resolve-tool-requests.ts
- js/core/src/tracing/processor.ts
- js/plugins/langchain/src/tracing.ts
- js/plugins/mcp/src/server.ts
Also relaxes requirement on interrupt resuming to only require tool requests, not necessarily interrupts (metadata sometimes gets lost, see #1816)
> chore(js): remove extraneous console.log statements

- samples/README.md
Consistent with main README, lets the button pop more so it's less easy to miss.
> chore: update samples readme to use purple IDX button

- genkit-tools/package.json
- js/package.json
- package.json
Upgrading from v9 to v10. None of the breaking changes affect us (already did this in `genkit-ui`).
https://github.com/pnpm/pnpm/releases/tag/v10.2.0
> chore: update pnpm to v10.2.0

- samples/idx-template.json
- samples/js-chatbot/.idx/dev.nix
- samples/js-chatbot/README.md
- samples/js-chatbot/genkit-app/package.json
- samples/js-chatbot/genkit-app/src/app/samples/chatbot/chatbot.component.ts
- samples/js-chatbot/package-lock.json
- samples/js-chatbot/package.json
- samples/js-chatbot/server/package-lock.json
- samples/js-chatbot/server/package.json
Updates the chatbot sample to include a preview pane in IDX and instructions for using Vertex
This PR can be tested here (choose Chatbot)
<a href="https://idx.google.com/new?template=https%3A%2F%2Fgithub.com%2Ffirebase%2Fgenkit%2Ftree%2Fadd-idx-to-chatbot%2Fsamples">
<img
height="32"
alt="Try in IDX"
src="https://cdn.idx.dev/btn/try_light_32.svg">
</a>
> Add nix config to js-chatbot

- package.json
- samples/js-angular/genkit-app/angular.json
- samples/js-angular/package.json
- samples/js-schoolAgent/package.json
- samples/package.json
> fix: add more samples to be run

- docs/plugins/vertex-ai.md
- js/pnpm-lock.yaml
- js/testapps/custom-evaluators/package.json
- js/testapps/dev-ui-gallery/package.json
- js/testapps/esm/package.json
- js/testapps/evals/package.json
- js/testapps/multimodal/package.json
- js/testapps/ollama/package.json
- js/testapps/rag/package.json
- js/testapps/vertexai-vector-search-firestore/README.md
- js/testapps/vertexai-vector-search-firestore/package.json
> docs: vertexai updates

- genkit-tools/common/src/types/model.ts
- genkit-tools/genkit-schema.json
- js/ai/src/chat.ts
- js/ai/src/model.ts
- js/ai/src/tool.ts
it wasn't really used or useful
> breaking(js/ai): drop ToolDefinition from ToolArgument (and generate action interface)

- docs/context.md
> docs(js): Adds doc for context.

- docs/firebase.md
- docs/flows.md
- docs/plugin-authoring-evaluator.md
- docs/tool-calling.md
This PR contains a second installment of edits made after an editorial and production pass.
First installment was [PR 1846](https://github.com/firebase/genkit/pull/1846).
> docs: 2nd tranche of docs updates for 6 Feb GA release

- samples/idx-template.json
- samples/js-chatbot/genkit-app/angular.json
- samples/js-chatbot/genkit-app/proxy.conf.json
- samples/js-chatbot/genkit-app/src/app/samples/chatbot/chatbot.component.ts
Moves to proxy calls to the flowSever through the angular app, this allows it to work as part of the preview pane in IDX
This can be tested here:
<a href="https://idx.google.com/new?template=https%3A%2F%2Fgithub.com%2Ffirebase%2Fgenkit%2Ftree%2Fadd-chatbot-sample-back%2Fsamples">
<img
height="32"
alt="Open in IDX"
src="https://cdn.idx.dev/btn/open_dark_32.svg">
</a>
> fix: update js-chatbot to work in IDX preview

- docs/plugins/vertex-ai.md
Helps prevent issues where the auth project and the configured project are different
> fix: be more specific about Vertex project id in auth

- js/plugins/google-cloud/src/gcpOpenTelemetry.ts
- js/pnpm-lock.yaml
- js/testapps/dev-ui-gallery/package.json
- js/testapps/dev-ui-gallery/src/genkit.ts
*The short of it:*
Modify the startTime of the datapoints so that we ensure there are no overlapping export intervals.
Add a shutdown hook to our metrics wrapper ensures we are awaiting the callback function from the wrapped cloud exporter which delegates to an async function with a callback.
*The long of it:*
We were seeing occasions where exported metrics are being overwritten. This is because Cloud does not currently support the delta metric kind for custom metrics. Instead, it will convert delta metrics into "pseudo delta" metrics by calling them cumulative for the time interval provided. Where we run into trouble is that the PeriodicMetricExporterReader creates a time interval based on the last export, setting the start time of the subsequent export to the end time of the previous …
> fix(js/plugins/google-cloud): Make metric export time intervals mutually exclusive

- go/plugins/googleai/googleai.go
- go/plugins/googleai/googleai_test.go
* In this CL a bug is fixed that prevented errors from being propagated from convertSchema() through convertTools().
* The above bug hid an issue where the genkit schema type switch was trying to match "int" instead of "integer".  This issue is also corrected.
* Tests updated and corrected
> fix(go/plugins/googleai): convertTools err propagate and schema type integer

- js/plugins/vertexai/src/gemini.ts
See Discord thread: https://discord.com/channels/1255578482214305893/1255583176089276566/1338956279896608800
And related Vertex SDK bug: https://github.com/googleapis/nodejs-vertexai/issues/494
It should never be the case where a single part has multiple types, so we can work around this for now by prioritizing functionCall which will bypass the current behavior of returning `"undefined\n"`.
> fix(js/vertexai): workaround for tool calling issue in Vertex SDK

- docs/plugins/firebase.md
It seems like when breaking a line to 80 columns, a bullet point was introduced. This PR fixes that.
> docs: fix a line break that turned into a bullet point

- js/plugins/firebase/src/index.ts
- js/plugins/google-cloud/src/index.ts
- js/plugins/google-cloud/src/types.ts
Paves the way for Genkit docs to link back to the API reference.
> docs(js/plugins/google-cloud): API reference docs

- docs/chat.md
- docs/get-started.md
- js/doc-snippets/src/index.ts
- js/doc-snippets/src/models/imagen.ts
- js/doc-snippets/src/models/minimal.ts
- js/plugins/dev-local-vectorstore/README.md
- js/plugins/ollama/README.md
Updated user-facing docs and samples to use Gemini 2.0 and `async function...` syntax.
We should use Gemini 2.0 Flash by default instead of Gemini 1.5 Flash, now that it's GA.
Additionally, I've seen that `async function main...` is a lot more common and seemingly better understood than `(async() => ...` - so I'm switching to that by default.
> docs: Updated user-facing docs and samples to use Gemini 2.0 and `async function...` syntax

- genkit-tools/cli/src/commands/start.ts
> fix(cli): fix genkit start in no runtime mode

- py/packages/genkit/src/genkit/core/plugin_abc.py
- py/packages/genkit/src/genkit/veneer/veneer.py
- py/plugins/vertex-ai/src/genkit/plugins/vertex_ai/__init__.py
- py/samples/hello/hello.py
Description
- Refactored Plugin API to use generic `genkit.core.plugin_abc.Plugin` interface
- Updated VertexAI implementation to follow the new specification
> feat(py): Refactored Plugins API to follow generic `Plugin` interface.

- js/ai/src/formats/json.ts
- js/ai/src/formats/types.ts
- js/ai/src/generate.ts
- js/ai/src/generate/action.ts
- js/ai/src/model.ts
- js/ai/tests/model/middleware_test.ts
- js/core/src/action.ts
- js/core/src/error.ts
- js/genkit/src/registry.ts
- js/genkit/tests/formats_test.ts
- js/genkit/tests/prompts_test.ts
- js/testapps/flow-simple-ai/src/index.ts
- js/testapps/format-tester/src/index.ts
```ts
const { output } = await generate(registry, {
prompt: 'generate json',
output: {
constrained: false,
instructions: true,
schema: z.object({
foo: z.string(),
}),
},
});
```
> feat(js/ai): allow disabling native constrained generation and enabling custom instruction

- bin/setup
node is managed by nvm, installing it with homebrew breaks nvm
> chore: do not install node with homebrew in the setup script

- js/plugins/googleai/src/gemini.ts
- js/plugins/googleai/tests/gemini_test.ts
- js/plugins/vertexai/src/gemini.ts
- js/plugins/vertexai/tests/gemini_test.ts
- js/testapps/flow-simple-ai/src/index.ts
> fix(js/plugins): fixed gemini tool schema converter to correctly handle descriptions, enums and nullable fields

- js/plugins/googleai/src/gemini.ts
- js/plugins/googleai/src/index.ts
- js/plugins/vertexai/src/common/types.ts
- js/plugins/vertexai/src/gemini.ts
- js/plugins/vertexai/src/index.ts
- js/testapps/context-caching/src/index.ts
- js/testapps/flow-simple-ai/src/index.ts
```ts
const ai = genkit({
plugins: [googleAI({experimental_debugTraces: true})],
});
```
> feat(js/plugins): added `experimental_debugTraces` option to googleai and vertexai plugins

- js/plugins/google-cloud/src/gcpLogger.ts
- js/plugins/google-cloud/src/gcpOpenTelemetry.ts
Since the various Google telemetry clients will perform their own credential/project lookups, we need to make sure we're always passing the user provided `projectId` into their constructors. Otherwise, `GCLOUD_PROJECT` will take precedence, and we don't want that. :)
- [N/A] Docs updated (updated docs or a docs bug required)
> fix(js/plugins/google-cloud): pass projectId through to GoogleAuth client

- js/plugins/google-cloud/src/gcpOpenTelemetry.ts
Example using openai instrumentation from elastic:
> fix(js/plugins/google-cloud): allow user specified otel instrumentations

- py/plugins/vertex-ai/src/genkit/plugins/vertex_ai/__init__.py
- py/plugins/vertex-ai/src/genkit/plugins/vertex_ai/constants.py
- py/plugins/vertex-ai/src/genkit/plugins/vertex_ai/gemini.py
- py/plugins/vertex-ai/src/genkit/plugins/vertex_ai/plugin_api.py
- py/samples/hello/README.md
- py/samples/hello/src/hello.py
This is a small pull request to correct VertexAI. I aim to provide basic corrections here to add more sophisticated features later.
- I previously created [draft](https://github.com/firebase/genkit/pull/1934) and I've used the feedback from there. 
> feat(py): Core VertexAI plugin

- py/packages/genkit/src/genkit/core/plugin_abc.py
- py/packages/genkit/src/genkit/veneer/veneer.py
- py/plugins/vertex-ai/src/genkit/plugins/vertex_ai/plugin_api.py
- py/samples/hello/src/hello.py
Description:
- Refactored a Plugin abstraction to make it more versatile in use.
- Updated the `VertexAI` plugin and a code sample
Problem:
1. Current implementation assumes that only one model is defined, whereas we may have multiple models.
2. It is unclear why `_model_callback` needs to be defined in the Plugin. Since each model (or model family) has its own execution logic, it should provide its own callback
> feat(py): refactoring a Plugin abstraction

- js/testapps/dev-ui-gallery/src/genkit.ts
- js/testapps/dev-ui-gallery/src/main/flows-firebase-functions.ts
Greet sample was broken because of missing default model and wrong call to run.
Before:
After:
> fix(js/testapps/dev-ui-gallery): Fixed greet sample

- js/ai/src/prompt.ts
Fixes https://github.com/firebase/genkit/issues/2056.
Also checked that go runtime adds variant name at the top level, so it doesn't have the same issue.
With dev-ui-gallery sample:
Before:
After:
> fix(js/ai/src/prompt): Add variant name in prompt metadata

- genkit-tools/common/src/server/server.ts
DevUI has switched to using the polling service since IDX does not support SSE.
> chore: cleanup unused /api/sse tooling endpoint

- py/packages/genkit/src/genkit/core/action.py
- py/packages/genkit/src/genkit/core/action_test.py
- py/packages/genkit/src/genkit/core/reflection.py
- py/packages/genkit/src/genkit/core/registry.py
- py/packages/genkit/src/genkit/core/registry_test.py
- py/packages/genkit/src/genkit/core/utils.py
- py/packages/genkit/src/genkit/veneer/server.py
- py/packages/genkit/src/genkit/veneer/veneer.py
- py/samples/hello/src/hello.py
Actions can be sync or async
```py
def syncFoo(input: str):
return f"syncFoo {input}"
syncFooAction = Action(name='syncFoo', kind=ActionKind.CUSTOM, fn=syncFoo)
async def asyncFoo():
return "asyncFoo"
asyncFooAction = Action(name='asyncFoo', kind=ActionKind.CUSTOM, fn=asyncFoo)
```
same for flows:
```py
@ai.flow()
def syncFoo(input: str):
return f"syncFoo {input}"
@ai.flow()
async def asyncFoo():
return "asyncFoo"
```
all actions can be run asyncronously:
```py
await syncFooAction.arun(input)
```
but only sync actions can be run synchronously (I couldn't find a way around this limitation)
```py
syncFooAction.run(input)
```
any (sync/async) action can stream
```py
async def asyncFoo(input: str, ctx: ActionRunContext):
ctx.send_chunk('1')
ctx.send_chunk('2')
return 3
```
dev facing …
> feat(py/core/action): added support for async actions (and flows) and streaming

- js/testapps/docs-menu-rag/src/genkit.ts
- js/testapps/docs-menu-rag/src/index.ts
- js/testapps/docs-menu-rag/src/indexer.ts
- js/testapps/docs-menu-rag/src/menuQA.ts
This PR resolves the problem where the sample code could not be executed by addressing the dependency issue.
When attempting to run the sample code for `js/testapps/docs-menu-rag` using `pnpm run build-and-run`, an error occurred stating that `defineFlow` was not defined. 
<details>
<summary>logs</summary>
```bash
$ genkit start -- pnpm run build-and-run                                                                                                                                                    (base) 
[Telemetry Server] initialized local file trace store at root: [REDACTED]/genkit/js/testapps/docs-menu-rag/.genkit/traces
Telemetry API running on http://localhost:4034
Genkit Developer UI: http://localhost:4001
> rag@1.0.0 build-and-run [REDACTED]/genkit/js/testapps/docs-menu-rag
> …
```
> fix(js/testapps/docs-menu-rag): resolve circular dependency by moving ai to genkit.ts

- js/plugins/google-cloud/src/telemetry/generate.ts
It's an array, so pass along object. 
I thought about stringify-ing it and truncating, but these should generally be small, and I think we do want the array as is.
> fix(js/plugins/google-cloud) don't truncate stopSequences

- py/packages/genkit/src/genkit/ai/embedding.py
- py/packages/genkit/src/genkit/veneer/veneer.py
- py/plugins/vertex-ai/src/genkit/plugins/vertex_ai/__init__.py
- py/plugins/vertex-ai/src/genkit/plugins/vertex_ai/embedding.py
- py/plugins/vertex-ai/src/genkit/plugins/vertex_ai/gemini.py
- py/plugins/vertex-ai/src/genkit/plugins/vertex_ai/plugin_api.py
- py/samples/hello/src/hello.py
Description:
- Added base models for Embedders: EmbedRequest, EmbedResponse and EmbedderFn function definition
- Created embed and defineEmbedder function in Genkit class
- Added VertexAI embedder, all the embedders defined in Enum can be used. 
- Added support for using different models/embedders
- The only task currently supported by embedders is a RETRIEVAL_QUERY
> feat(py): Add Embeddings and test on VertexAI

- go/ai/embedder.go
- go/ai/generate.go
- go/ai/prompt.go
- go/ai/retriever.go
- go/ai/tools.go
- go/core/action.go
- go/core/flow.go
- go/genkit/genkit.go
- go/genkit/servers.go
> refactor(go): Removed exposure to internal action interface.

- js/plugins/vertexai/src/gemini.ts
Looks like at one point we placed a description of location as banana. This seems to have been left over from a previous edit and wanted to clean it out. Not sure if its an easter egg for folks browsing the code or a load bearing banana.
> refactor: remove the location description of banana

- go/core/action.go
- go/internal/base/json.go
Fixes #2205.
Passing a type to the JSON schema reflector like the following:
```go
type MyStruct struct {
MyField []any `json:"myField"`
}
```
Results in the following JSON schema:
```json
{
"properties": {
"myField": {
"type": "string",
"items": true,
}
},
"additionalProperties": false,
"type": "object"
}
```
Which is not valid. `items` needs to be an object (can be with no fields). The package we're using does not generate that.
> fix(go): Added JSON schema hack for `[]any` types.

- js/plugins/ollama/src/embeddings.ts
- js/plugins/ollama/tests/embeddings_test.ts
- js/plugins/vertexai/src/vectorsearch/index.ts
- js/plugins/vertexai/src/vectorsearch/vector_search/firestore.ts
- js/plugins/vertexai/src/vectorsearch/vector_search/indexers.ts
- js/plugins/vertexai/src/vectorsearch/vector_search/query_public_endpoint.ts
- js/plugins/vertexai/src/vectorsearch/vector_search/retrievers.ts
- js/plugins/vertexai/src/vectorsearch/vector_search/types.ts
- js/plugins/vertexai/src/vectorsearch/vector_search/upsert_datapoints.ts
- js/plugins/vertexai/tests/vectorsearch/bigquery_test.ts
- js/plugins/vertexai/tests/vectorsearch/query_public_endpoint_test.ts
- js/plugins/vertexai/tests/vectorsearch/upsert_datapoints_test.ts
- js/testapps/context-caching2/src/index.ts
- js/testapps/multimodal/src/pdf.ts
- js/testapps/multimodal/src/video.ts
- js/testapps/vertexai-vector-search-firestore/src/index.ts
chore: improve multimodal testapp with defaults
fix(js/plugins/vertexai/vectorsearch/firestore): stored doc metadata is  returned with the response.
> feat(js/plugins/vertexai): added support for restricts and numerical restricts in vector search

- js/ai/src/prompt.ts
- js/genkit/tests/prompts_test.ts
- [N/A] Docs updated (updated docs or a docs bug required)
> fix: set prompt metadata for render action as expected by dev ui

- go/ai/retriever.go
- go/internal/doc-snippets/pinecone.go
- go/internal/doc-snippets/rag/main.go
- go/plugins/firebase/retriever.go
- go/plugins/firebase/retriever_test.go
- go/plugins/localvec/localvec.go
- go/plugins/localvec/localvec_test.go
- go/plugins/pinecone/genkit.go
- go/plugins/weaviate/weaviate.go
- go/samples/firebase-retrievers/main.go
- go/samples/pgvector/main.go
Fixes https://github.com/firebase/genkit/issues/2197.
> fix(go): Fixed retrievers data types (Dev UI mismatch).

- py/packages/genkit/src/genkit/ai/embedding.py
- py/packages/genkit/src/genkit/veneer/veneer.py
- py/plugins/vertex-ai/src/genkit/plugins/vertex_ai/__init__.py
- py/plugins/vertex-ai/src/genkit/plugins/vertex_ai/embedding.py
- py/plugins/vertex-ai/src/genkit/plugins/vertex_ai/gemini.py
- py/plugins/vertex-ai/src/genkit/plugins/vertex_ai/imagen.py
- py/plugins/vertex-ai/src/genkit/plugins/vertex_ai/plugin_api.py
- py/plugins/vertex-ai/tests/test_embeddings.py
- py/plugins/vertex-ai/tests/test_gemini.py
- py/plugins/vertex-ai/tests/test_imagen.py
- py/samples/hello/README.md
- py/samples/hello/src/hello.py
- py/samples/vertex-ai-imagen/README.md
- py/samples/vertex-ai-imagen/src/vertex-ai-imagen.py
- Add more unit tests to VertexAI
- Separate some functionality and test it
- Support multiple image generation
- Support streaming
> feat(py/vertexai): Enhance VertexAI plugin

- py/plugins/google-ai/src/genkit/plugins/google_ai/__init__.py
- py/plugins/google-ai/src/genkit/plugins/google_ai/google_ai.py
- py/plugins/google-ai/src/genkit/plugins/google_ai/models/gemini.py
- py/plugins/google-ai/src/genkit/plugins/google_ai/schemas.py
- py/samples/google-ai/LICENSE
- py/samples/google-ai/README.md
- py/samples/google-ai/pyproject.toml
- py/samples/google-ai/src/hello.py
Created google ai plugin
- plugin code
- plugin models
- plugin sample
> feat(py): Python GoogleAi plugin

- js/plugins/googleai/src/gemini.ts
- js/plugins/vertexai/src/gemini.ts
- js/testapps/flow-simple-ai/src/index.ts
```ts
const {text} = ai.generate({
model: 'googleai/gemini-2.0-flash',
prompt: [
{text: 'what is this a video of?'},
{media: {url: "https://www.youtube.com/watch?v=y8Kyi0WNg40", contentType: "video/mp4"}}
],
})
```
> feat(js/plugins/{googleai,vertexai}): adds YouTube URL support

- py/packages/genkit/src/genkit/core/action.py
- py/packages/genkit/tests/genkit/core/action_test.py
This fix is needed because for plugin action (eg `/model/vertexai/gemini`) we should preserve `vertexai/gemini` as the name.
> fix(py): lookup fix for plugin actions

- py/packages/genkit/src/genkit/core/action.py
- py/packages/genkit/src/genkit/veneer/registry.py
- py/packages/genkit/tests/genkit/core/action_test.py
- py/packages/genkit/tests/genkit/veneer/veneer_test.py
```py
@ai.flow()
async def my_flow(input: str, ctx):
ctx.send_chunk(1)
ctx.send_chunk(2)
ctx.send_chunk(3)
return input
stream, response = my_flow.stream('banana')
async for chunk in stream:
print(chunk)
print(await response)
```
> faet(py/core): added stream method to actions and flows

- js/plugins/firebase/src/firestoreRetriever.ts
Fixes bug discussed [in Discord](https://discord.com/channels/1255578482214305893/1347641604004909208).
Right now `ai.retrieve()` with a Firestore retriever won't give you a type error if you don't supply options, but will have a runtime exception. This makes options fully optional.
> fix(js/plugins/firebase): Ensure Firestore retriever works with no options.

- go/ai/generate.go
- go/ai/option.go
- go/ai/option_test.go
- go/ai/prompt.go
- go/ai/prompt_test.go
- go/ai/tools.go
`ai.WithTools` took in a `Tool` which is a resolved tool action. This works for in-code usages but when loading .prompt files, we only have tool names as strings. We can resolve these but since we load .prompt files at `Genkit` init, tools won't have been initialized yet and during prompt definition, we convert the tools to tool names to adhere to the `GenerateActionOptions` interface. But the user experience is still nicer when defining tools and passing those tool references directly so this is the compromise.
> fix(go): Made `WithTools` accept a `ToolRef` interface

- .github/workflows/go.yml
- .github/workflows/scripts/check-generated-go.sh
> fix(go): Return error message if go code is not re-generated from updated schema

- go/ai/generate.go
- go/ai/generator_test.go
- go/ai/model_middleware.go
- go/ai/model_middleware_test.go
- go/ai/request_helpers.go
- go/samples/basic-gemini-with-context/main.go
Addition of augmentWithContext middleware to simulated document-based grounding support.
Resolving : https://github.com/firebase/genkit/issues/1926
> feat(go): Added simulated document-based context support

- js/plugins/googleai/src/gemini.ts
- js/plugins/googleai/src/index.ts
```ts
import { gemini25ProExp0325, googleAI } from '@genkit-ai/googleai';
const ai = genkit({ 
plugins: [ googleAI() ],
model: gemini25ProExp0325,
});
const { text } = await await ai.generate('hi');
```
> chore(js/plugins/googleai): expose gemini-2.5-pro-exp-03-25 (`gemini25ProExp0325`)

- py/packages/genkit-ai/src/genkit/core/action.py
- py/plugins/compat-oai/src/genkit/plugins/compat_oai/models/handler.py
- py/plugins/compat-oai/src/genkit/plugins/compat_oai/models/model.py
- py/plugins/compat-oai/src/genkit/plugins/compat_oai/openai_plugin.py
- py/plugins/compat-oai/src/genkit/plugins/compat_oai/typing.py
- py/plugins/compat-oai/tests/test_handler.py
- py/plugins/compat-oai/tests/test_model.py
- py/plugins/compat-oai/tests/test_tool_calling.py
- py/samples/openai/src/main.py
Add tool support for OpenAI compat plugin:
- detects and extracts tool call information 
- looks up the corresponding tool/action via the GenkitRegistry
- validates and executes the tool using the defined input schema
- formats the result into a tool message and appends it to the conversation
- re-queries OpenAI with the tool result included, continuing the flow seamlessly.
(Also includes a fix for the action context)
> feat(py): add tool support for openai-compat plugin

- js/ai/package.json
- js/ai/src/prompt.ts
- js/core/package.json
- js/plugins/evaluators/package.json
- js/pnpm-lock.yaml
This updates Dotprompt to version `v1.1.0` which no longer escapes HTML inside`{{ expressions }}`.
> chore(js): Update Dotprompt to v1.1.0. Fixes #2039

- go/genkit/reflection.go
`json.NewEncoder()` and `encoder.Encode()` were causing unexpected flushes to the response writer when streaming responses back to the reflection server causing invalid JSONS to be received during the stream execution.
> fix(go/genkit): use controlled flushing on JSON responses

- go/ai/prompt.go
This is needed for https://github.com/FirebasePrivate/genkit-ui/pull/1332
> fix: remove legacy prompts from go

- go/ai/prompt.go
- go/ai/prompt_test.go
- go/genkit/genkit.go
- go/go.mod
- go/go.sum
- go/internal/registry/registry.go
- go/samples/partials-and-helpers/main.go
- #2365 
- Add dotprompt functions for rendering prompts
- Modify metadata to pass template data as well 
- Add input from ActionCtx as input for rendering the templates
- Removed predefined helpers from prompt.go since they are already declared in the dotprompt function : https://github.com/google/dotprompt/blob/main/go/dotprompt/helper.go#L26
> feat(go/genkit): Use `dotprompt` package for rendering prompt templates

- js/plugins/express/src/index.ts
If the plugin user misconfigured things, there was a possibility that request.body was undefined.
> fix(js/plugins/express): Check request.body is defined before reading data from it

- go/ai/model_middleware.go
- go/genkit/genkit.go
- go/genkit/reflection.go
- go/plugins/googlegenai/gemini.go
- Avoid a crash when streaming encounters an error
- Prevent panic() when `ToolChoice` is unknown
- Prevent a crash if no messages are sent in a `Generate` call
> fix(go): minor bug fixes

- genkit-tools/common/src/eval/evaluate.ts
- genkit-tools/common/src/eval/validate.ts
- py/packages/genkit/src/genkit/ai/_registry.py
- `evaluate.ts` -- go returns the new format of responses, updated error collection logic in evals tooling
-  `validate.ts` -- go sets IDs for schemas which are cached in ajv, causing problems for subsequent calls due to the global `ajv` object, made it local instead.
- `_registry.py` -- made uuid string, like it should be.
> fix(go/py/tooling): More small fixes related to evals

- py/docs/get-started.md
- py/docs/index.md
- py/docs/reference/models.md
- py/docs/reference/rag.md
- py/packages/genkit/src/genkit/ai/_base.py
- py/samples/compat-oai-hello/src/compat_oai_hello.py
- py/samples/dev-local-vectorstore-hello/src/hello.py
- py/samples/firestore-retreiver/src/main.py
- py/samples/google-genai-hello/src/google_genai_hello.py
- py/samples/google-genai-image/src/google_genai_image.py
- py/samples/google-genai-vertexai-hello/src/google_genai_vertexai_hello.py
- py/samples/ollama-hello/src/ollama_hello.py
in Genkit JS we also have `ai.run`, but it's for a different purpose: https://js.api.genkit.dev/classes/genkit._.Genkit.html#run
> refactor(py): renamed `ai.run` to `ai.run_main` to avoid confusion with `ai.run` in JS

- js/ai/src/model.ts
- js/genkit/src/model.ts
- js/plugins/ollama/src/index.ts
- js/plugins/vertexai/src/gemini.ts
- js/plugins/vertexai/src/modelgarden/mistral.ts
Here's the link to the issue: https://github.com/firebase/genkit/issues/2333. This updates the following plugins: `Ollama`, `vertexai/gemini` and `vertexai/mistral`.
I checked that I am getting the new values on the dev UI by logging out the configuration:
**Ollama:**
**vertexai/gemini:**
**vertexai/mistral:**
> chore: update model config parameters

- js/ai/src/prompt.ts
- js/genkit/tests/prompts_test.ts
Prompt variants weren't loading in the dev ui. Now they are. :)
Name/variant in the metadata is a composite key, so don't set name to the full name (`name.variant`). Note this is not the same as the action name, which remains fully qualified.
> fix(js/ai): properly set prompt meta for variants

- js/ai/src/formats/index.ts
- js/ai/tests/formats/format_test.ts
The generate action takes a jsonSchema as part of the output configuration. In that case, we should also default to json output conformance.
> fix(js/ai/formats): default to json if jsonSchema present

- py/plugins/google-genai/src/genkit/plugins/google_genai/models/gemini.py
- py/plugins/vertex-ai/src/genkit/plugins/vertex_ai/gemini.py
This PR adds support for the gemini-2.5-flash-preview-04-17 model to the Genkit Python plugins (google-genai and vertex-ai).
Note: Support for this model in the Go and JavaScript plugins has already been added in separate pull requests
> feat(py/plugins/google-genai, py/plugins/vertex-ai): add gemini-2.5-flash-preview-04-17 model

- samples/README.md
Updated the link in the /samples folder, prompts to js-prompts, fixing the 404 error
**Update**
Added chatbot.
> docs(samples): Fixed broken link in the samples guide

- go/plugins/googlegenai/gemini.go
- go/plugins/googlegenai/googleai_live_test.go
`ai.NewMediaPart` was originally supporting only hosted data. This PR includes the support for inline data as in `ai.NewDataPart`
> fix(go/plugins/googlegenai): `ai.NewMediaPart` support to inline and hosted data

- go/plugins/ollama/ollama.go
- go/samples/ollama-vision/main.go
Supports vision models in generate method. Tested locally with sample script.
> feat(go): Add ollama vision support

- js/core/src/action.ts
- js/core/src/plugin.ts
- js/core/src/reflection.ts
- js/core/src/registry.ts
- js/core/tests/registry_test.ts
- js/genkit/src/genkit.ts
- js/genkit/src/plugin.ts
Added new `listResolvableActions()` method to the registry that calls `listActions()` for plugins. Switched reflection API `list actions` endpoint to use `listResolvableActions()` .
> feat(js/core): allow defining a "list actions" fn for plugins

- genkit-tools/common/src/manager/manager.ts
- go/genkit/reflection.go
Having colons in the runtime causes Genkit to fail during startup in non-POSIX systems.
> fix(go/genkit): remove colons from runtime filename

- js/genkit/src/genkit.ts
- js/genkit/tests/chat_test.ts
- js/genkit/tests/prompts/chat_preamble.prompt
- js/genkit/tests/prompts_test.ts
wrapExecutablePromptPromise was  incorrectly handling input for render.
> fix(js/prompts): fixed .prompt input handling on prompt render

- js/ai/src/generate.ts
- js/ai/src/generate/resolve-tool-requests.ts
- js/ai/src/tool.ts
- js/core/src/registry.ts
- js/genkit/src/common.ts
- js/genkit/src/tool.ts
- js/genkit/tests/generate_test.ts
- js/testapps/flow-simple-ai/src/index.ts
> feat(js/ai): added dynamic tools that can be dynamically defined at runtime

- README.md
- docs/_guides.yaml
- docs/angular.md
Add a quickstart guide for Genkit + Angular
> Add Angular quickstart guide

- go/ai/action_test.go
- go/ai/document.go
- go/go.mod
- go/tests/api_test.go
1. Fixes the YAML library issue by importing the correct goccy/go-yaml package.
2. Directly modifies the ModelRequest's tool definitions by setting the schema fields that the test expects.
3. Do not modify the ToolDefinition in the registry, which was causing issues.
4. Ensures the test has the correct schema values when comparing the expected and actual responses.
> fix(go/genkit): update YAML library from go-yaml/yaml to goccy/go-yaml

- go/genkit/reflection.go
- go/genkit/reflection_test.go
Handling of telemetryLabels coming from UI in payload to set in span.
Resolving : https://github.com/firebase/genkit/issues/2422
> bug(go):Propagate telemetry labels from Reflection API to tracing

- docs/interrupts.md
- docs/tool-calling.md
Fix import from `@genkitai/google-ai` to `@genkit-ai/googleai`
> docs: fix imports

- genkit-tools/common/src/types/document.ts
- genkit-tools/common/src/types/model.ts
- genkit-tools/genkit-schema.json
- js/ai/src/document.ts
- js/ai/src/generate/chunk.ts
- js/ai/src/generate/response.ts
- js/ai/src/message.ts
- js/ai/src/model.ts
- js/plugins/googleai/src/gemini.ts
- js/plugins/vertexai/src/gemini.ts
- js/testapps/flow-simple-ai/src/index.ts
- py/packages/genkit/src/genkit/core/typing.py
> feat(js): added reasoning part type and implemented for googleai and vertexai

- go/plugins/googlegenai/gemini.go
https://github.com/firebase/genkit/issues/2924
> fix(go/plugins/googlegenai): runtime panic if no candidates returned

- py/packages/genkit/src/genkit/ai/_base.py
- py/packages/genkit/src/genkit/ai/_plugin.py
- py/packages/genkit/src/genkit/ai/_registry.py
- py/packages/genkit/src/genkit/blocks/embedding.py
- py/packages/genkit/src/genkit/blocks/model.py
- py/packages/genkit/src/genkit/core/action/__init__.py
- py/packages/genkit/src/genkit/core/action/_action.py
- py/packages/genkit/src/genkit/core/reflection.py
- py/packages/genkit/src/genkit/core/registry.py
- py/packages/genkit/tests/genkit/blocks/embedding_test.py
- py/packages/genkit/tests/genkit/blocks/model_test.py
- py/packages/genkit/tests/genkit/core/endpoints/reflection_test.py
- py/packages/genkit/tests/genkit/core/registry_test.py
- py/plugins/google-genai/src/genkit/plugins/google_genai/google.py
- py/plugins/google-genai/src/genkit/plugins/google_genai/models/embedder.py
- py/plugins/google-genai/test/test_google_plugin.py
Add list models for Dev UI
- Add method in Plugin interface
- Add override of list_models method for GoogleAI and VertexAI plugin
- Add fix typo in resolve_action implementations.
- Add patter of resolve_action for list_model functions
> feat(py): Add list models for dev UI Gemini

- genkit-tools/cli/src/commands/eval-flow.ts
- genkit-tools/cli/src/commands/eval-run.ts
- genkit-tools/common/src/eval/evaluate.ts
- genkit-tools/common/src/types/apis.ts
- js/ai/src/evaluator.ts
- js/testapps/evals/data/dogfacts.json
Description:
- JS fix #1643 
- Support batching in JS evaluators
- Restrictions placed for non-JS runtimes
> feat(js/ai/evaluators): Support batching for JS evaluator & CLI

- go/plugins/googlegenai/gemini.go
This change resolves a bug (?) that caused googlegenai gemini models to return an error when generating streaming responses with tools. 
The issues is detailed here with a test module: https://github.com/firebase/genkit/issues/2978
There was a comment that noted only text is supported while streaming. Not sure why this would be the case. I didn't have any issues generating streaming responses with these changes.
> fix(go/plugins/googlegenai):  Tool calls with streaming

- js/plugins/mcp/README.md
- js/plugins/mcp/src/client/client.ts
- js/plugins/mcp/src/client/host.ts
- js/plugins/mcp/src/client/index.ts
- js/plugins/mcp/src/index.ts
- js/plugins/mcp/src/util/resources.ts
- js/plugins/mcp/tests/manager_test.ts
- js/testapps/esm/src/index.ts
- js/testapps/mcp/src/index.ts
The terminology for "thing that managers multiple MCP clients" seems to be converging on "MCP Host" so I'm going with that instead of Manager for the name.
> chore(js/mcp): Rename "Manager" -> "Host" to align terminology.

- py/plugins/compat-oai/src/genkit/plugins/compat_oai/models/model.py
- py/plugins/compat-oai/src/genkit/plugins/compat_oai/models/model_info.py
- py/plugins/vertex-ai/src/genkit/plugins/vertex_ai/model_garden/model_garden.py
- py/plugins/vertex-ai/src/genkit/plugins/vertex_ai/model_garden/modelgarden_plugin.py
- py/samples/model-garden/src/main.py
I added the methods of resolve_action and list_actions for model garden plugin
still missing unit testing
> feat(py): Resolve action and list actions methods for model garden plugin

- go/go.mod
- go/go.sum
- https://github.com/firebase/genkit/issues/3019
- Update the dotprompt version to get changes from the PR : https://github.com/google/dotprompt/pull/312
> fix(go/genkit): Update dotprompt version

- js/plugins/mcp/src/client/host.ts
- js/plugins/mcp/src/util/prompts.ts
- js/plugins/mcp/src/util/tools.ts
- js/plugins/mcp/tests/fakes.ts
- js/plugins/mcp/tests/host_test.ts
This solves the issue raised by #2662 by allowing MCP metadata to be specified as part of context and passed to the server.
> feat(js/mcp): Adds support for MCP _meta via context.

- js/plugins/google-cloud/src/metrics.ts
- js/plugins/google-cloud/tests/metrics_test.ts
Attribute truncation should be consistent between metric data written and trace data written so that data can be correlated between aggregate metric data and specific traces.
> fix: Update metric attribute length truncation to match Trace attribute max length.

- js/plugins/google-cloud/tests/logs_test.ts
There was an 'it.only' in one of the tests. Removing it uncovered that the two describe blocks couldn't actually both run successfully because they were each enabling telemetry when this can only happen once.  I rearranged the tests to make sure that we only initialize telemetry once, but this uncovered another problem, where only one of them was enabling JSON format for the logs, so I updated everything to use structured JSON format.
> fix(js/plugins/google-cloud): Run all tests and refactor to only initialize telemetry once

- go/plugins/compat_oai/openai/README.md
Close #3079 
Fix up typo in the docs for OpenAI plugin.
> docs: fix up OpenAI plugin example

- js/plugins/google-cloud/src/utils.ts
Include "dotprompt" as a valid path segment type. When extracting the root "feature name", this prevents paths of this type falling back to the default ("generate").
> fix(js/plugins/google-cloud): Fix feature name parsing to include "dotprompt" type

- go/samples/mcp-server/run-server.sh
- py/plugins/google-genai/src/genkit/plugins/google_genai/models/gemini.py
- py/plugins/google-genai/test/models/test_googlegenai_gemini.py
I was doing a recommender system by myself, and I found that gemini do not support this kind of output_schemas:
```
class Product(BaseModel):
product_name: str = Field(description='name of the product')
product_description: str = Field(description='description of the product')
class StoreSchema(BaseModel):
store_name: str = Field(description='name of the store')
products: list[Product] = Field(description='list of products in the store (5 to 10)')
```
So I decided to generate the bugfix
> fix(py): Support more complex schemas gemini

- js/plugins/google-cloud/src/gcpOpenTelemetry.ts
- js/plugins/google-cloud/src/telemetry/action.ts
- js/plugins/google-cloud/tests/logs_test.ts
Previously the 'generate' helpers wrote their full input/output logs only when it is a root node (outside a flow). This change ensures that those logs always get written. They provide useful information in the Firebase console.
> fix(js/plugins/google-cloud): Write input and output logs for generate step

- js/plugins/compat-oai/src/openai/gpt.ts
- js/plugins/compat-oai/src/openai/index.ts
- js/testapps/compat-oai/src/index.ts
> feat(js/plugins/compat-oai): Add explicit model types for dynamic resolution

- py/plugins/vertex-ai/src/genkit/plugins/vertex_ai/model_garden/client.py
- py/plugins/vertex-ai/src/genkit/plugins/vertex_ai/model_garden/model_garden.py
- py/plugins/vertex-ai/tests/model_garden/test_client.py
- py/plugins/vertex-ai/tests/model_garden/test_model_garden.py
This PR only adds tests for the model garden plugin
> chore(py): Add tests model garden

- samples/js-schoolAgent/src/attendanceAgent.ts
- samples/js-schoolAgent/src/gradesAgent.ts
Description
-  Refer to https://github.com/firebase/genkit/issues/3004#issuecomment-2934472274
```
[ 'actionFn', 'actionFn', 'routingAgent' ]
[ 'actionFn', 'routingAgent' ]
```
- The fix `item.name` → `item.__action.name`
```
[ 'reportAbsence', 'reportTardy', 'routingAgent' ]
[ 'getRecentGrades', 'routingAgent' ]
```
> fix: wrong item name actionFn

- py/packages/genkit/src/genkit/ai/_aio.py
py/packages/genkit/src/genkit/ai/_aio.py was missing the "or none" in its type annotation
> fix(py/genkit/ai): add missing type annotation

- js/plugins/googleai/src/veo.ts
Also added a step value for durationSeconds, since it supports only whole numbers.
> fix(js): Remove numberOfVideos config parameter for Veo

- js/core/src/reflection.ts
If multiple reflection APIs start in quick succession in the same process, the file names can collide. Adding the port number gives it better uniqueness.
We need the same for Go, but it doesn't seem to use port ranges currently?
> fix(js/core): add port number to runtime file name

- js/core/src/action.ts
- js/core/src/reflection.ts
- js/core/tests/flow_test.ts
> fix(js/core): correctly passthrough telemetry labels when streaming

- js/ai/src/generate.ts
- js/ai/src/index.ts
- js/ai/src/resource.ts
- js/ai/tests/resource/resource_test.ts
- js/genkit/src/common.ts
- js/genkit/tests/generate_test.ts
Similar to `dynamicTool`
```ts
const myResource = dynamicResource(
{
uri: 'foo://foo',
description: 'description',
},
async () => ({ content: [...] })
);
const { text } = await ai.generate({
prompt: [
{ text: 'analyze this: ' },
{ resource: { uri: 'foo://foo' } },
],
resources: [myResource],
});
```
> feat(js/ai): added a way to define resources dynamically

- js/ai/src/index.ts
- js/genkit/src/common.ts
- js/plugins/mcp/src/client/client.ts
- js/plugins/mcp/src/client/host.ts
- js/plugins/mcp/src/util/message.ts
- js/plugins/mcp/src/util/resource.ts
- js/plugins/mcp/tests/fakes.ts
- js/plugins/mcp/tests/host_test.ts
- js/testapps/mcp/src/index.ts
```ts
const { text } = await ai.generate({
prompt: [
{ text: 'analyze this: ' },
{ resource: { uri: 'test://static/resource/1' } },
],
resources: await mcpHost.getActiveResources(ai),
});
```
> feat(js/plugins/mcp): added support for MCP resources via dynamicResource

- genkit-tools/common/src/eval/evaluate.ts
- genkit-tools/common/src/eval/index.ts
- genkit-tools/common/src/eval/localFileEvalStore.ts
- genkit-tools/common/src/server/router.ts
- genkit-tools/common/tests/eval/localFileEvalStore_test.ts
Switch over (safely) to JSON index in local file store. This should fix the bug where the index is left corrupted by deleting evals.
> fix(genkit-tools/evals): Switch to JSON index in EvalStore

- js/core/src/reflection.ts
Similar to the file, we can also have collisions in the map. Changes to be consistent with the filename (pid-port).
We should probably either deprecate `GENKIT_RUNTIME_ID` and/or introduce the ability to pass an id in as part of the genkit instance.
> fix(js/core): add port to runtime id for uniqueness

- js/plugins/compat-oai/src/audio.ts
- js/plugins/compat-oai/src/deepseek/deepseek.ts
- js/plugins/compat-oai/src/deepseek/index.ts
- js/plugins/compat-oai/src/image.ts
- js/plugins/compat-oai/src/model.ts
- js/plugins/compat-oai/src/openai/dalle.ts
- js/plugins/compat-oai/src/openai/gpt.ts
- js/plugins/compat-oai/src/openai/index.ts
- js/plugins/compat-oai/src/openai/tts.ts
- js/plugins/compat-oai/src/openai/whisper.ts
- js/plugins/compat-oai/src/xai/grok-image.ts
- js/plugins/compat-oai/src/xai/grok.ts
- js/plugins/compat-oai/src/xai/index.ts
- js/plugins/compat-oai/tests/compat_oai_test.ts
- js/testapps/compat-oai/src/index.ts
> fix(js/plugins/compat-oai): Use XAI/DEEPSEEK env vars for api key

- py/packages/genkit/src/genkit/ai/_plugin.py
- py/plugins/compat-oai/src/genkit/plugins/compat_oai/openai_plugin.py
- py/plugins/compat-oai/tests/test_plugin.py
- py/plugins/google-genai/src/genkit/plugins/google_genai/google.py
- py/plugins/ollama/src/genkit/plugins/ollama/plugin_api.py
- py/plugins/vertex-ai/src/genkit/plugins/vertex_ai/model_garden/modelgarden_plugin.py
- py/samples/compat-oai-hello/src/compat_oai_hello.py
Added the `list_actions` method to the OpenAI compatibility plugin and refactored the base `Plugin` class contract.
* Added `list_actions` cached property to dynamically discover available OpenAI models
* Refactored base `Plugin` class to support dynamic action discovery
Added unit tests covering:
- Dynamic model discovery
- Correct metadata generation for both embedding and text generation models
- Caching behavior of the `list_actions` property
Updated relevant documentation to reflect the new functionality and base class changes.
Closes #3151
> feat(py): add list_actions method to OpenAI compat plugin

- js/plugins/google-genai/src/common/types.ts
- js/plugins/google-genai/src/common/utils.ts
- js/plugins/google-genai/src/googleai/client.ts
- js/plugins/google-genai/src/googleai/gemini.ts
- js/plugins/google-genai/src/googleai/veo.ts
- js/plugins/google-genai/src/vertexai/client.ts
- js/plugins/google-genai/src/vertexai/converters.ts
- js/plugins/google-genai/src/vertexai/gemini.ts
- js/plugins/google-genai/src/vertexai/index.ts
- js/plugins/google-genai/src/vertexai/types.ts
- js/plugins/google-genai/src/vertexai/utils.ts
- js/plugins/google-genai/tests/common/utils_test.ts
- js/plugins/google-genai/tests/googleai/veo_test.ts
- js/plugins/google-genai/tests/vertexai/client_test.ts
- js/plugins/google-genai/tests/vertexai/converters_test.ts
- js/plugins/google-genai/tests/vertexai/embedder_test.ts
- js/plugins/google-genai/tests/vertexai/gemini_test.ts
- js/plugins/google-genai/tests/vertexai/imagen_test.ts
- js/plugins/google-genai/tests/vertexai/index_test.ts
- js/plugins/google-genai/tests/vertexai/utils_test.ts
> feat(js/plugins/google-genai): Added support for global Vertex endpoint

- go/plugins/compat_oai/generate.go
- go/plugins/googlegenai/googleai_live_test.go
- go/plugins/googlegenai/models.go
- go/plugins/googlegenai/vertexai_live_test.go
- go/plugins/vertexai/modelgarden/anthropic_live_test.go
- go/samples/compat_oai/openai/main.go
- go/samples/prompts/main.go
> feat(go/plugins/compat_oai): Add media parts support

- genkit-tools/cli/src/commands/start.ts
> chore: add a warning when running in .Trash folder

- js/plugins/google-genai/src/common/types.ts
- js/plugins/google-genai/src/googleai/gemini.ts
- js/plugins/google-genai/src/vertexai/gemini.ts
- js/plugins/googleai/src/gemini.ts
- js/plugins/vertexai/src/gemini.ts
Fixes #3335
- Adds to genai plugin
- Backports to gemini & vertex plugins.
> fix: add thinking tokens to usage stats for gemini models

- go/genkit/genkit.go
Description:
- https://github.com/firebase/genkit/issues/3354
- Performs a safe type-switch on the returned value of a registry's LookupPlugin. If a plugin does not exist (or is the incorrect type), this will no longer panic.
> fix(go): Fixed type assertions on LookupPlugin

- js/plugins/google-cloud/src/telemetry/generate.ts
- js/plugins/google-cloud/tests/metrics_test.ts
Related to https://github.com/firebase/genkit/issues/3335
Tested exported metrics are visible in Google Cloud and match new thoughtsTokens attributes in the usage block.
The screenshots below were taken before renaming to thinking, however the logic remains the same.
**New Google Cloud metric** 
**thoughtsToken attribute is visible in Firebase Genkit Monitoring and matches exported metrics**
> feat(js/plugins/google-cloud): Add support to export thinking token usage as a new metric

- go/plugins/compat_oai/generate.go
Addressed issue: https://github.com/firebase/genkit/issues/3247
> fix(go/plugins/compat-oai): Pass tool call ID if available

- js/ai/src/formats/types.ts
- js/ai/src/generate/action.ts
- js/plugins/google-genai/src/common/types.ts
- js/plugins/google-genai/src/common/utils.ts
- js/plugins/google-genai/src/googleai/utils.ts
- js/plugins/google-genai/src/vertexai/client.ts
- js/plugins/google-genai/src/vertexai/converters.ts
- js/plugins/google-genai/src/vertexai/imagen.ts
- js/plugins/google-genai/src/vertexai/index.ts
- js/plugins/google-genai/src/vertexai/lyria.ts
- js/plugins/google-genai/src/vertexai/types.ts
- js/plugins/google-genai/src/vertexai/utils.ts
- js/plugins/google-genai/src/vertexai/veo.ts
- js/plugins/google-genai/tests/common/converters_test.ts
- js/plugins/google-genai/tests/common/utils_test.ts
- js/plugins/google-genai/tests/vertexai/client_test.ts
- js/plugins/google-genai/tests/vertexai/converters_test.ts
- js/plugins/google-genai/tests/vertexai/imagen_test.ts
- js/plugins/google-genai/tests/vertexai/lyria_test.ts
- js/plugins/google-genai/tests/vertexai/utils_test.ts
- js/plugins/google-genai/tests/vertexai/veo_test.ts
> feat(js/plugins/google-genai): Added Veo and Lyria

- js/core/src/flow.ts
- js/core/tests/flow_test.ts
Fix #3376 
- Add tests for `run` function call.
- Avoid to use `arguments.length`
> fix(js): `run()` calls the function with given input

- bin/install_cli
- scripts/cli-releases/README.md
- scripts/cli-releases/promote_cli_gcs.sh
- scripts/cli-releases/update_cli_metadata.sh
This PR adds scripts to promote Genkit CLI binaries from GitHub artifacts to Google Cloud Storage (GCS), along with metadata management for version tracking.
- **`scripts/promote_cli_gcs.sh`** - Downloads binaries from GitHub and uploads to GCS
- **`scripts/update_cli_metadata.sh`** - Updates metadata JSON files with version information
- **`scripts/cli-promotion/README.md`**
> feat(ci): add promotion scripts

- genkit-tools/common/src/types/document.ts
> fix: export proper reasoning part for tools common

- js/plugins/compat-oai/src/model.ts
- js/plugins/compat-oai/src/openai/gpt.ts
Also updated the ModelInfo for unknown compat-oai models to be fully permissive.
> feat(js/plugins/compat-oai): Add GPT-5 model info

- genkit-tools/cli/src/commands/ui-start.ts
- genkit-tools/cli/src/utils/runtime-detector.ts
- genkit-tools/cli/src/utils/spawn-config.ts
- genkit-tools/cli/tests/commands/ui-start_test.ts
- genkit-tools/cli/tests/utils/runtime-detector_test.ts
- genkit-tools/cli/tests/utils/spawn-config_test.ts
This should resolve https://github.com/firebase/genkit/issues/3338
> fix(cli): better runtime handling for ui:start

- js/core/package.json
- js/pnpm-lock.yaml
Similar to https://github.com/firebase/genkit/pull/3459
but removes warnings related to opentelemetry/exporter-jaeger
> fix(js) Add otel jaeger dependency to remove next.js warning

- go/ai/embedder.go
- go/ai/evaluator.go
- go/ai/evaluator_test.go
- go/ai/option.go
- go/ai/retriever.go
> breaking(go): changed `Evaluate()` to take in refs

- go/ai/tools.go
- go/plugins/googlegenai/gemini.go
- go/plugins/mcp/tools.go
- go/plugins/mcp/tools_test.go
- go/samples/mcp-ception/mcp_ception.go
- go/samples/mcp-client/main.go
When we added support for dynamic tools we didn't have a way to define a dynamic tool with an input schema, so the tools weren't propagating the required arguments correctly. This PR fixes that problem.
I also noticed that for JSON schema properties that are numbers (minItems, maxItems, minimum, maximum), our googlegenai gemini plugin expects these fields to be strings and casts to float. However the JSON schemas from MCP tools get unmarshalled into jsonschema.Schema which types them as floats/ints. I think it's most flexible to support both types in the gemini plugin, so I updated that here.
> feat(go): Fix missing input schema from dynamic tools

- go/ai/option.go
Return too early. This leads to the loss of the tools defined in the prompt file after loading it.
Fixes #3499
> fix(go/ai/options): update commonGenOptions apply opts

- go/ai/generate.go
- go/plugins/firebase/telemetry.go
- go/plugins/googlecloud/action.go
- go/plugins/googlecloud/engagement_test.go
- go/plugins/googlecloud/generate.go
- go/plugins/googlecloud/googlecloud.go
- go/plugins/googlecloud/types.go
- go/plugins/vertexai/modelgarden/anthropic.go
Addresses feedback here: https://docs.google.com/spreadsheets/d/1yYuyBLzA6S9blsGv05C-YKJSqyZsfMjh8IX7SW4RbTY/edit?gid=0#gid=0
Mainly:
1) Move the generate span generation to the ai.Generate() method - the Generation Action already gets a span from the action framework so there's no need to add it there, and ai.Generate() DOES need the extra span since it's not an action. This is the cause of most of the weirdness
2) Add support for GCLOUD_PROJECT (same as genkit ts)
3) Make firebase plugin match googlecloud plugin in terms of options (pass thru directly)
4) Handle credential detection automatically
5) Make sure exact same logs as genkit ts are being emitted by ensuring that logic for which telemetry module to call is exactly the same. Also update the user engagement tests to reflect …
> fix(go): fixes to AIM telemetry

- go/plugins/googlecloud/googlecloud.go
- go/plugins/googlecloud/slog_handler.go
- go/plugins/googlecloud/utils.go
Mimics TS behavior. When logger fails, we:
- clearly switch to a new logger that writes to stderr
- show a helpful logging denied helptext (first time only)
- reinitialize the logger in case there was an intermittent issue
Example:
```
time=2025-09-12T19:49:08.192-05:00 level=WARN msg="Switched to stderr logging due to Google Cloud logging failure" error="rpc error: code = PermissionDenied desc = Permission 'logging.logEntries.create' denied on resource (or it may not exist).\nerror details: name = ErrorInfo reason = IAM_PERMISSION_DENIED domain = iam.googleapis.com metadata = map[permission:logging.logEntries.create]\nerror details: name = Unknown  desc = log_entry_errors:{key:0  value:{code:7  message:\"Permission 'logging.logEntries.create' denied on resource (or it may not exist).\"}} …
```
> fix(go): Display clear error message when logger fails

- go/plugins/compat_oai/generate.go
1. Optimize the conversion from ai.Message to OpenAI message.
2. Optimize the streaming function. When a toolcall call is returned, also return the toolcall information through the callback function.
3. Support multiple toolcall messages in a single request.
> (fix/go/compat_oai): update OpenAI message transformation

- go/plugins/compat_oai/anthropic/anthropic.go
Anthropic provider for `compat_oai` plugin checks the `ANTHROPIC_API_KEY` value during its initialization.
> fix(go/plugins/compat_oai): check `ANTHROPIC_API_KEY` during plugin init

- go/internal/registry/registry.go
> fix(go): handle concurrent calls to `Registry.ResolveAction()`

- go/ai/generate.go
- go/ai/prompt.go
- go/ai/prompt_test.go
- go/ai/tools.go
> fix(go/ai): handle tools passed in `Prompt.Execute()`

- js/genkit/.guides/config.json
- js/genkit/.guides/setup.md
- js/genkit/.guides/style.md
- js/genkit/.guides/usage.md
- js/plugins/express/.guides/usage.md
- js/plugins/google-genai/.guides/docs/editing-images.prompt
- js/plugins/google-genai/.guides/docs/generating-speech.prompt
- js/plugins/google-genai/.guides/docs/search-and-urls.prompt
- js/plugins/next/.guides/usage.prompt
- js/plugins/next/README.md
- js/testapps/next/package.json
Provides some useful LLM guidance in a convenient place.
> chore: Adds `.guides` folders to a few Genkit packages

- genkit-tools/cli/src/commands/init-ai-tools/ai-tools/gemini.ts
- genkit-tools/cli/src/mcp/server.ts
- genkit-tools/cli/src/mcp/usage.ts
Will reintroduce extension install once fixed for user-level configuration.
> fix(cli/init-ai-tools): remove Gemini CLI extension installation

- go/internal/registry/registry.go
The child registry was not considering the registered parents' actions and plugins
> fix(go/internal): discover actions and plugins in parent registry

- go/plugins/compat_oai/README.md
- go/plugins/compat_oai/compat_oai.go
- go/plugins/compat_oai/generate.go
- go/samples/compat_oai/custom/main.go
> fix(go/plugins/compat_oai): add support for custom providers

- js/ai/src/generate.ts
- js/ai/src/generate/action.ts
- js/ai/src/model-types.ts
- js/ai/src/resource.ts
- js/ai/src/tool.ts
- js/ai/tests/generate/generate_test.ts
- js/ai/tests/resource/resource_test.ts
- js/core/src/dynamic-action-provider.ts
- js/core/src/index.ts
- js/core/src/registry.ts
- js/core/src/schema.ts
- js/core/tests/dynamic-action-provider_test.ts
- js/genkit/src/common.ts
- js/genkit/src/genkit.ts
- js/plugins/mcp/src/client/client.ts
- js/plugins/mcp/src/client/host.ts
- js/plugins/mcp/src/client/index.ts
- js/plugins/mcp/src/index.ts
- js/plugins/mcp/src/server.ts
- js/testapps/mcp/src/index.ts
> feat(js/core): Add dynamic-action-provider support

- go/ai/prompt.go
- go/samples/prompts/main.go
- go/samples/prompts/prompts/media.prompt
- go/samples/prompts/prompts/multi-msg.prompt
Previously, `.prompt` files were not supporting `gs://` and `http(s):` URIs
> fix(go/ai): enable use of media URIs in prompts

- js/plugins/google-genai/src/googleai/gemini.ts
- js/plugins/google-genai/src/vertexai/gemini.ts
- js/plugins/google-genai/src/vertexai/imagen.ts
> chore(js/plugins/google-genai): Make sure all config is passthrough

- js/genkit/.guides/setup.md
- js/plugins/google-genai/.guides/usage.md
> docs: refine .guides guidance a bit
