firebase/genkit

js/plugins/googleai/src/gemini.ts, js/plugins/vertexai/src/gemini.ts
=> Do not pass systemInstructions to models that do not support it

genkit-tools/config/firebase.index.ts.template, genkit-tools/src/commands/init.ts
There will still be a lint _warning_ because of duplicate imports. But it's not an error and it would be a larger change which I think is probably too risky at this moment.
=> Update init command to play nice with Functions eslint default settings

genkit-tools/package.json, js/package.json, package.json
https://github.com/pnpm/pnpm/releases/tag/v9.1.0
=> Upgrade to pnpm 9.1.0

go/ai/generator.go, go/genkit/dotprompt/genkit.go, go/samples/coffee-shop/main.go
Also update coffee-shop to use GOOGLE_API_KEY rather than GEMINI_API_KEY.
=> [Go] update dotprompt model strings to use provider/model

go/go.mod
=> fix go.mod Go version

docs/models.md
I updated the documentation to match the latest implementation.
=> Replaced `options` with `config` in the `generate` function within the document

go/ai/document.go, go/ai/document_test.go, go/genkit/dotprompt/render.go, go/genkit/dotprompt/render_test.go, go/plugins/googleai/googleai.go, go/plugins/vertexai/vertexai.go
to better match the other Part kinds.
=> rename IsPlainText -> IsText

js/plugins/googleai/src/gemini.ts, js/plugins/googleai/src/index.ts, js/plugins/vertexai/src/gemini.ts, js/plugins/vertexai/src/index.ts
=> Add Gemini 1.5 Pro Flash

docs/firebase.md
menuSuggestionFlow() is missing
=> fix sample code of firebase

go/plugins/googleai/embed.go, go/plugins/googleai/googleai.go, go/plugins/vertexai/vertexai.go
Reorganize the code in the google AI and Vertex plugins to be
more similar.
No behavior changes.
=> [Go] make the two Gemini generators more similar

js/plugins/ollama/src/index.ts
=> Improved error message when ollama is not running

genkit-tools/package.json, js/package.json, package.json
=> Make pnpm version match the one specified by the UI package

go/ai/embedder.go, go/plugins/googleai/embed.go, go/plugins/googleai/googleai.go, go/plugins/vertexai/embed.go
Add DefineEmbedder, which returns an Embedder whose Embed
method runs an action.
=> [Go] embed calls are always actions

go/ai/generator.go, go/plugins/dotprompt/dotprompt.go, go/plugins/dotprompt/genkit_test.go, go/plugins/googleai/googleai.go, go/plugins/googleai/googleai_test.go, go/plugins/vertexai/vertexai.go, go/plugins/vertexai/vertexai_test.go, go/samples/menu/s01.go, go/samples/menu/s02.go, go/samples/menu/s03.go, go/samples/menu/s04.go, go/samples/menu/s05.go
Remove the Generator interface.
Instead, there is a GeneratorAction, which is just a type of Action.
=> [Go] a generator is just an action

go/ai/generate.go, go/ai/prompt.go, go/plugins/dotprompt/dotprompt.go, go/plugins/dotprompt/genkit.go, go/plugins/dotprompt/genkit_test.go, go/plugins/dotprompt/render.go, go/plugins/googleai/googleai.go, go/plugins/googleai/googleai_test.go, go/plugins/vertexai/vertexai.go, go/plugins/vertexai/vertexai_test.go, go/samples/coffee-shop/main.go, go/samples/menu/main.go, go/samples/menu/s01.go, go/samples/menu/s02.go, go/samples/menu/s03.go, go/samples/menu/s04.go, go/samples/menu/s05.go, go/samples/rag/main.go
=> [Go] rename Generator to Model

go/samples/coffee-shop/main.go
=> [Go] don't pass callback from flow to prompt if flow didn't get one

go/ai/tools.go, go/plugins/googleai/googleai_test.go, go/plugins/vertexai/vertexai_test.go, go/samples/menu/s02.go
For consistency with other action types.
Also minor internal tweaks.
=> [Go] rename RegisterTool to DefineTool

go/ai/prompt.go, go/core/action.go, go/plugins/dotprompt/dotprompt.go, go/plugins/dotprompt/genkit.go, go/plugins/dotprompt/genkit_test.go, go/plugins/googleai/googleai.go, go/plugins/vertexai/vertexai.go, go/samples/coffee-shop/main.go, go/samples/menu/s02.go, go/samples/menu/s04.go, go/samples/menu/s05.go, go/samples/rag/main.go
This corresponds to the TypeScript ai/prompt code.
This revealed that we were setting invalid values in the vertexai config, so adjusted that.
Fixes #356
=> [Go] change ai package prompt support to just render

go/core/action.go, go/core/action_test.go, go/core/conformance_test.go, go/core/core.go, go/core/flow.go, go/core/flow_test.go, go/core/registry.go, go/core/servers_test.go, go/core/validation.go, go/genkit/genkit.go
Unexport symbols in the core package that are probably not
needed outside of it.
=> [Go] unexport symbols in core

js/plugins/googleai/src/gemini.ts, js/plugins/googleai/src/index.ts, js/plugins/vertexai/src/gemini.ts, js/plugins/vertexai/src/index.ts, js/testapps/rag/src/index.ts
=> feat: added Gemini 1.5 GA model versions

js/plugins/vertexai/src/embedder.ts, js/plugins/vertexai/src/index.ts
=> feat: added Vertex AI multilingual embeddings and text-embedding-004

docs/firebase.md
Fix the code snippet containing `cors` option on https://firebase.google.com/docs/genkit/firebase#deploy_a_flow_as_a_cloud_function
=> Fix CORS code snippet

js/ai/src/index.ts
Added the NoValidCandidatesError error to the exports inside the index.ts file.
=> add NoValidCandidatesError export

go/genkit/genkit.go, go/genkit/genkit_test.go, go/samples/coffee-shop/main.go, go/samples/flow-sample1/main.go, go/samples/menu/s02.go, go/samples/menu/s03.go, go/samples/menu/s04.go, go/samples/menu/s05.go, go/samples/rag/main.go
```go
menuSuggestionFlow := genkit.DefineFlow(
"menuSuggestionFlow",
func(ctx context.Context, restaurantTheme string) (string, error) {
// ...
},
)
streamingMenuSuggestionFlow := genkit.DefineStreamingFlow(
"streamingMenuSuggestionFlow",
func(ctx context.Context, restaurantTheme string, cb func(context.Context, string) error) (string, error) {
// ...
},
)
```
=> feat: [Go] added DefineStreamingFlow to make DefineFlow simpler

go/ai/gen.go, go/core/schemas.config
=> Remove CandidateError/CandidateErrorCode.

js/plugins/ollama/src/index.ts
Ollama models support the "system" role. Ensure that it is supported in our plugin too.
=> Update ollama js plugin to support system message

go/plugins/googleai/googleai.go, go/plugins/vertexai/vertexai.go
=> [Go] Temporarily removed mutex.

docs-go/get-started-go.md, docs-go/get-started-go.src
=> Some Go get-started fixes

js/plugins/google-cloud/src/gcpOpenTelemetry.ts
=> Carry over the span context.

js/flow/src/flow.ts
Still need to figure out longer term how to enforce flows with auth policies....
=> Check auth on streamFlow() calls

docs-go/README.md
=> Add a readme for Go docs

docs-go/README.md
=> Update README.md -- dotprompt

docs/plugins/firebase.md
=> Update firebase.md -- remove lang from link

docs/plugins/google-cloud.md
=> Add "Test your integration" section to google-cloud.md

docs/get-started.md
- Correct CLI text
- Use commented sample
=> Updates to get-started.md

go/plugins/googleai/googleai.go
Use the BatchEmbedContents RPC so a single call can handle
multiple documents.
=> [Go] plugins/googlai: use batch embed RPC

genkit-tools/package.json, js/package.json, package.json
https://github.com/pnpm/pnpm/releases/tag/v9.5.0
=> Update to pnpm v9.5

js/plugins/firebase/src/index.ts
This wasn't being passed when using the GCLOUD_PROJECT environment variable.
=> Update Firebase plugin to support passing project ID to gcp telemetry

js/plugins/vertexai/package.json, js/plugins/vertexai/src/anthropic.ts, js/plugins/vertexai/src/index.ts, js/pnpm-lock.yaml
Fixes https://github.com/firebase/genkit/issues/437
This PR adds Claude 3.5 Sonnet to the Vertex AI plugin. (Work in progress)
=> feat: add Claude 3.5 Sonnet model

go/internal/doc-snippets/prompts.go
=> Fix error in Go snippet

genkit-tools/common/src/runner/runner.ts, genkit-tools/common/src/utils/runner-utils.ts
=> feat: build code before running runner based CLI commands

js/core/src/tracing.ts
=> Flush metrics in all environments

js/plugins/googleai/package.json, js/plugins/googleai/src/gemini.ts, js/pnpm-lock.yaml, js/testapps/flow-simple-ai/src/index.ts
Added JSON mode support in Google AI plugin in JS. (Only supports Gemini 1.5 Flash.)
Tested manually using the newly added jokeWithOutputFlow in testapps.
- [ x ] Tested (manually, unit tested, etc.)
=> feat(js): add support for json mode in googleai plugin

package.json, pnpm-lock.yaml, tests/pnpm-lock.yaml, tests/src/e2e.ts, tests/src/utils.ts, tests/test_js_app.yaml, tests/test_js_app/package.json
Add a test that checks the responses from the reflection API.
Describe the test in a YAML file so it can be used by other languages.
=> add e2e test for reflection API

js/ai/tests/model/middleware_test.ts, js/plugins/vertexai/src/index.ts
=> Add cloud scope for vertex authclient

go/plugins/googleai/googleai.go, go/plugins/vertexai/vertexai.go
=> [Go] fix system role capability

js/plugins/google-cloud/package.json, js/plugins/google-cloud/src/gcpOpenTelemetry.ts, js/pnpm-lock.yaml
=> Add genkit and its version as the user agent to all metrics exports

go/plugins/googleai/googleai.go, go/plugins/vertexai/vertexai.go
Factor out more common code using the copy tool
=> [Go] copy more code from googleai to vertexai

docs-go/dotprompt.md, docs-go/prompts.md, go/internal/doc-snippets/dotprompt.go, go/internal/doc-snippets/prompts.go
=> Fix docs template issue

js/plugins/chroma/src/index.ts, js/pnpm-lock.yaml, js/testapps/rag/package.json, js/testapps/rag/src/index.ts, js/testapps/rag/src/simple_rag.ts
Will update docs in a follow-up PR.
=> Update chroma to support remote hosts (Cloud Run)

docs-go/README.md, go/README.md
=> Link to Go docs from READMEs

docs-go/plugin-authoring-models.md, docs-go/plugin-authoring.md, go/internal/doc-snippets/modelplugin/modelplugin.go, go/internal/doc-snippets/plugin/plugin.go
=> Go docs: plugin authoring overview and model guide

docs-go/dotprompt.md, go/internal/doc-snippets/dotprompt.go, go/internal/doc-snippets/googleai.go, go/internal/doc-snippets/models.go, go/internal/doc-snippets/rag/main.go, go/internal/doc-snippets/vertexai.go
=> Go docs: make sure to use Gemini 1.5 Flash as the default

docs-go/get-started-go.md, docs/get-started.md
=> Add install section

genkit-tools/package.json, js/package.json, package.json
https://github.com/pnpm/pnpm/releases/tag/v9.6.0
=> Update to pnpm v9.6

docs-go/_guides.yaml, docs-go/plugin-authoring-telemetry.md, docs-go/plugin-authoring.md, go/internal/doc-snippets/telemetryplugin/exporters.go, go/internal/doc-snippets/telemetryplugin/telemetryplugin.go
=> Go docs: telemetry plugin authoring guide

.gitignore, js/ai/src/model.ts, js/plugins/googleai/package.json, js/plugins/googleai/src/gemini.ts, js/pnpm-lock.yaml, js/testapps/google-ai-code-execution/package.json, js/testapps/google-ai-code-execution/src/index.ts, js/testapps/google-ai-code-execution/tsconfig.json
This PR adds support for code execution in the Google AI plugin. 
Google AI returns codeExecutionResult and executableCode as new Part types. I didn't know if we should add these to the core Genkit package or not. For now I've made a draft where i've added a CustomPart. 
=> feat: support custom parts and code execution in googleai

genkit-tools/cli/src/commands/init/init-nodejs.ts
Resolves https://github.com/firebase/genkit/issues/531
Any blocking sync process with stop the spinner in `ora`. 
=> fix: unblock spinner on init

docs/plugins/vertex-ai.md, docs/rag.md
=> Add vector search info to vertex docs

docs-go/dotprompt.md, docs-go/flows.md, docs-go/get-started-go.md, docs-go/models.md, docs-go/pgvector.md, docs-go/plugin-authoring-models.md, docs-go/plugin-authoring-telemetry.md, docs-go/plugin-authoring.md, docs-go/prompts.md
=> Minor corrections to Go docs

docs/_guides.yaml, docs/feedback.md
=> Add feedback info to docs

README.md
=> Update README.md with Go plugin authoring guide

docs/index.md
=> docs: add video to landing page

genkit-tools/package.json, js/package.json, package.json
https://github.com/pnpm/pnpm/releases/tag/v9.7.1
=> Update to pnpm v9.7.1

genkit-tools/package.json, js/package.json, package.json
https://github.com/pnpm/pnpm/releases/tag/v9.8.0
=> Update to pnpm v9.8

docs/_guides.yaml, docs/models.md, docs/tool-calling.md
=> docs: new page on tool calling

genkit-tools/package.json, js/package.json, package.json
https://github.com/pnpm/pnpm/releases/tag/v9.9.0
=> Update to pnpm v9.9

js/ai/src/telemetry.ts
All logged input and output messages will now contain the message role ('system', 'user', 'model', 'tool')
=> [JS] Include the role in the logged input and output messages.

genkit-tools/common/src/types/retrievers.ts
For use in the Dev UI.
- [] Changelog updated
=> Add RetrieverRequest to tools-common

go/genkit/genkit.go
=> Remove doc reference to StartFlowServer from genkit.go

js/plugins/firebase/src/index.ts, js/plugins/google-cloud/package.json, js/plugins/google-cloud/src/auth.ts, js/plugins/google-cloud/src/gcpLogger.ts, js/plugins/google-cloud/src/gcpOpenTelemetry.ts, js/plugins/google-cloud/src/index.ts, js/plugins/google-cloud/src/telemetry/defaults.ts, js/plugins/google-cloud/src/types.ts, js/plugins/google-cloud/tests/logs_test.ts, js/plugins/google-cloud/tests/metrics_test.ts, js/pnpm-lock.yaml
- Distinguishing between external options and internal config
- Centralizing telemetry defaults and making them environment aware
- Exposing configuration methods for use by firebase plugin
- Cleaning up more ts in tests
=>  Improving google-cloud and firebase plugin configuration

js/plugins/google-cloud/src/telemetry/flow.ts, js/plugins/google-cloud/tests/logs_test.ts
If IO logging is enabled, logs the inputs and outputs at the flow level.
=> Add input and output logging at the flow level

js/plugins/google-cloud/src/telemetry/flow.ts
=> Record output properly

docs/plugins/google-genai.md
Add instructions for using a tuned model from the Gemini API. Addresses https://github.com/firebase/genkit/issues/878 
- [x ] Docs updated
=> Add block for tuned models in Gemini

docs/flows.md
=> Update flows.md to show how to call via curl

genkit-tools/cli/src/commands/init.ts
=> Remove Google AI warning

genkit-tools/common/package.json, genkit-tools/common/src/types/trace.ts, genkit-tools/package.json, genkit-tools/pnpm-lock.yaml, genkit-tools/telemetry-server/package.json, genkit-tools/telemetry-server/src/firestoreTraceStore.ts, genkit-tools/telemetry-server/src/index.ts, genkit-tools/telemetry-server/src/localFileTraceStore.ts, genkit-tools/telemetry-server/src/types.ts
tools-common doesn't need to depend on telemetry-server package
=> chore: untangle tools-common and telemetry-server deps

go/plugins/dotprompt/genkit.go, go/plugins/dotprompt/genkit_test.go
=> fix model name lookup in dotprompt plugin and add a test

genkit-tools/common/src/utils/prompt.ts, genkit-tools/common/tests/utils/prompt_test.ts
Fixes https://github.com/firebase/genkit/issues/954.
=> feat: export media urls when generating .prompt from UI

go/ai/generate.go, go/ai/generator_test.go
This PR aims to resolve issue: https://github.com/firebase/genkit/issues/847
=> fix(go): Return `nil` in `LookupModel` when no matching model is found

js/plugins/vertexai/package.json, js/plugins/vertexai/src/anthropic.ts, js/plugins/vertexai/tests/anthropic_test.ts
Follows https://github.com/firebase/genkit/pull/959.
=> chore: update anthropic plugin to use single message response

js/plugins/ollama/src/index.ts, js/plugins/vertexai/src/anthropic.ts
Follows https://github.com/firebase/genkit/pull/959.
=> chore: update ollama plugin to use single message response

docs/plugins/ollama.md
Should resolve https://github.com/firebase/genkit/issues/654
This PR updates the docs for ollama, so that the sample code is handling tokens more efficiently
I will manual test the sample code provided before merging this.
=> docs(js): update token fetching in ollama docs

js/plugins/google-cloud/src/gcpOpenTelemetry.ts, js/plugins/google-cloud/tests/traces_test.ts
Marking genkit root features to facilitate queries for the Genkit entry point (eg flow, a prompt, generate, etc.)
=> Marking genkit root features

js/plugins/vertexai/src/index.ts, js/plugins/vertexai/src/model_garden.ts
- [ x ] Tested (manually, unit tested, etc.)
=> feat(js): add llama 3.2 support

genkit-tools/package.json, js/package.json, package.json
https://github.com/pnpm/pnpm/releases/tag/v9.11.0
=> chore: update to pnpm v9.11 (#940)

genkit-tools/package.json, js/package.json, package.json
For main branch.
https://github.com/pnpm/pnpm/releases/tag/v9.12.0
=> chore: update to pnpm v9.12

js/plugins/google-cloud/src/gcpOpenTelemetry.ts, js/plugins/google-cloud/tests/traces_test.ts
=> Add explicit model attribute to make filtering by model easier.

docs/index.md
=> Fix imports in index.md

js/core/src/tracing/instrumentation.ts, js/plugins/google-cloud/package.json, js/plugins/google-cloud/src/gcpOpenTelemetry.ts, js/plugins/google-cloud/src/telemetry/feature.ts, js/plugins/google-cloud/tests/metrics_test.ts, js/plugins/google-cloud/tests/traces_test.ts, js/pnpm-lock.yaml
Parallels root flow metrics for requests and latency
=> Updating google-cloud plugin to write feature metrics

js/plugins/google-cloud/src/telemetry/engagement.ts, js/plugins/google-cloud/tests/metrics_test.ts
Add standard dimensions to engagement metrics
=> Add standard dimensions to engagement metrics

genkit-tools/cli/src/commands/ui-start.ts, genkit-tools/cli/src/utils/server-harness.ts, genkit-tools/common/src/server/server.ts, genkit-tools/common/src/utils/utils.ts
```bash
tail -f .genkit/servers/devui.log
```
=> fix: write dev ui logs to a file, fixed shutdown health checking

genkit-tools/common/src/eval/evaluate.ts
=> [Evals] fix: run action first, gather traces later

genkit-tools/package.json, js/package.json, package.json
https://github.com/pnpm/pnpm/releases/tag/v9.12.2
=> chore: update to pnpm v9.12.2

genkit-tools/cli/package.json, genkit-tools/common/package.json, genkit-tools/pnpm-lock.yaml
Fixes https://github.com/firebase/genkit/security/dependabot/5
=> Update axios to ^1.7.7

genkit-tools/common/package.json, genkit-tools/pnpm-lock.yaml
Fixes https://github.com/firebase/genkit/security/dependabot/5
=> Update axios to ^1.7.7 (main)

docs/plugins/google-cloud.md
=> Update cloud plugin documentation to make consistent with new metrics.

.gitignore, js/flow/package.json, js/plugins/firebase/package.json, js/plugins/vertexai/package.json, js/pnpm-lock.yaml, js/testapps/cat-eval/package.json, js/testapps/dev-ui-gallery/package.json, js/testapps/firebase-functions-sample1/functions/package.json, js/testapps/flow-simple-ai/package.json, js/testapps/vertexai-vector-search-firestore/package.json
=> fix: made firebase-admin and firebase-functions peers deps more flexible

genkit-tools/common/src/server/router.ts
Missed in https://github.com/firebase/genkit/pull/975.
=> Fix getDataset method output in tools server router

js/plugins/googleai/package.json, js/plugins/googleai/src/gemini.ts, js/pnpm-lock.yaml
=> chore: bump google ai sdk version (0.16.0 -> 0.21.0)

genkit-tools/common/src/manager/manager.ts
=> [CLI] Fixed runtime management bugs.

js/ai/src/generate.ts, js/ai/src/prompt.ts, js/ai/src/tool.ts, js/doc-snippets/src/dotprompt/index.ts, js/genkit/src/genkit.ts, js/genkit/tests/generate_test.ts, js/genkit/tests/prompts_test.ts, js/testapps/dev-ui-gallery/src/main/prompts.ts, js/testapps/flow-simple-ai/src/index.ts, js/testapps/prompt-file/src/index.ts
=> fix: made ai.prompt sync

js/plugins/vertexai/src/anthropic.ts, js/plugins/vertexai/src/index.ts, js/testapps/format-tester/src/index.ts
=> Adds Claude 3.5 Sonnet v2 to Vertex models.

docs/_guides.yaml, docs/multi-agent.md, js/doc-snippets/src/multi-agent/multi.ts, js/doc-snippets/src/multi-agent/simple.ts
=> docs: multi-agent docs

docs/chat.md
=> docs: fix chat.md markdown

js/plugins/googleai/src/gemini.ts, js/plugins/vertexai/src/gemini.ts
```ts
const { text } = await ai.generate({
model: gemini15Flash,
prompt: 'hi',
tools: [toolA, toolB],
config: {
functionCallingConfig: {
mode: 'ANY',
}
}
});
```
=> feat: added `functionCallingConfig` config option for gemini models

js/plugins/googleai/src/gemini.ts, js/plugins/vertexai/src/common/index.ts, js/plugins/vertexai/src/index.ts
=> [JS][vertexai] Improves first request performance w/ specified project id

js/doc-snippets/src/multi-agent/multi.ts
=> docs: preamble syntax

js/plugins/firebase/README.md
Added notes to plugin documentation regarding telemetry reliability
=> Firebase plugin telemetry documentation

docs/plugin-authoring-telemetry.md
Adjusting for the new telemetry and logging apis.
=> Updating telemetry plugin docs for 0.9

js/plugins/chroma/package.json, js/plugins/chroma/src/index.ts, js/pnpm-lock.yaml
Fixes: https://github.com/firebase/genkit/issues/973
Code:
Trace:
=> [fix] Replace `nativeEnum` in ChromaDB plugin; Improve metadata fetching

docs/firebase.md
=> docs: updated CF3 deployment guide

docs/_guides.yaml
=> docs: add 0.5 migration to _guides.yaml

docs/monitoring.md, docs/plugins/google-cloud.md
=> Update monitoring docs and add dashboard links

docs/migrating-from-0.5.md, docs/tool-calling.md
=> docs: misc fixes

docs/devtools.md, docs/index.md
Updated Genkit docs landing page and Developer Tools docs
=> Updated Genkit docs landing page and Developer Tools docs

docs/_guides.yaml
=> docs: move migration guide down

js/core/src/flow.ts
=> fix: flow server should default to env.PORT and never pick new port

docs/cloud-run.md
=> docs: Update cloud-run.md for PORT behavior

docs/index.md
=> docs: fix display issues in index.md

docs/deploy-node.md
=> docs: Update formatting deploy-node.md

docs/get-started.md
=> docs: make get-started.md code sample copy-pastable

docs/plugin-authoring-evaluator.md
=> Update evals plugin doc

docs/plugins/google-cloud.md
=> docs: fixes in google-cloud.md

docs/plugins/firebase.md
=> Update firebase.md phrasing

docs/firebase.md
=> Update firebase.md -- typo

docs/auth.md
=> Updated Auth guide

docs/devtools.md
=> Update devtools.md -- typo

docs/migrating-from-0.5.md
Add in a quickstart with abbreviated step by step instructions to help folks get through the migration faster.
=> docs: update migrating-from-0.5.md

docs/_guides.yaml, docs/nextjs.md
=> docs: revised nextjs guide

docs/migrating-from-0.5.md
=> migrating-from-0.5.md formatting

docs/cloud-run.md
=> docs: Update cloud-run.md ("Three, sir!")

docs/nextjs.md
=> docs: correction to nextjs.md

docs/migrating-from-0.5.md
=> docs: display bug fix migrating-from-0.5.md

js/plugins/google-cloud/src/gcpOpenTelemetry.ts, js/plugins/google-cloud/tests/traces_test.ts
Enabling better searches for failed paths in traces
=> Marking failed paths in google-cloud plugin telemetry

js/core/src/flow.ts
Not sure how I ran across this, but it seems to be erroneous that we call this.authPolicy twice. Let me know if I am missing something, though. :)
=> Remove duplicated call to authPolicy

docs/evaluation.md
=> removed langchain reference from evals doc

docs/evaluation.md
=> Added slash to fix docs link

docs/rag.md
=> fix(docs): Fix flow run command in rag.md

docs/chat.md
Update quotes to fix interpolation
=> fix: Update chat.md docs to correct interpolation

genkit-tools/pnpm-lock.yaml, genkit-tools/telemetry-server/package.json, js/ai/package.json, js/core/package.json, js/genkit/package.json, js/package.json, js/plugins/checks/package.json, js/plugins/chroma/package.json, js/plugins/dev-local-vectorstore/package.json, js/plugins/dotprompt/package.json, js/plugins/evaluators/package.json, js/plugins/firebase/package.json, js/plugins/google-cloud/package.json, js/plugins/googleai/package.json, js/plugins/mcp/examples/client/package.json, js/plugins/mcp/examples/server/package.json, js/plugins/mcp/package.json, js/plugins/ollama/package.json, js/plugins/pinecone/package.json, js/plugins/vertexai/package.json, js/pnpm-lock.yaml, js/testapps/firebase-functions-sample1/functions/package.json
=> chore: a few fixes for the MPC plugin PR

js/plugins/mcp/src/client/resources.ts, js/plugins/mcp/src/index.ts
Doesn't attempt to list / load any capabilities not advertised by the server.
=> fix(js/plugins/mcp): Only load capabilities advertised by the server.

js/plugins/mcp/README.md
=> chore(js/plugins/mcp): Small README updates for MCP plugin.

js/plugins/mcp/src/client/resources.ts
the diff should be self-explanatory
=> fix(js/plugins/mcp): infinite loop for multi-page MCP client resources

js/ai/src/session.ts, js/genkit/tests/chat_test.ts, js/genkit/tests/session_test.ts
See [discord thread](https://discord.com/channels/1255578482214305893/1312610039755837441).
=> fix(js/ai): Ensure messages are serializable before sending to store. 

genkit-tools/common/src/eval/evaluate.ts, genkit-tools/common/src/types/eval.ts
=> feat(evals): Include `actionConfig` in EvalRunkey

js/core/src/action.ts, js/core/src/flow.ts, js/genkit/src/client/client.ts, js/genkit/src/genkit.ts, js/plugins/express/README.md, js/plugins/express/package.json, js/plugins/express/src/index.ts, js/plugins/express/src/utils.ts, js/plugins/express/tests/express_test.ts, js/plugins/express/tsconfig.json, js/plugins/express/tsup.config.ts, js/plugins/express/typedoc.json, js/pnpm-lock.yaml, js/testapps/express/package.json, js/testapps/express/src/index.ts
```ts
const myFlow = ai.defineFlow(
{
name: 'flowWithContext',
inputSchema: z.object({ question: z.string() }),
},
async (input) => {
return `${input.question} - ${JSON.stringify(getFlowContext())}`;
}
);
const app = express();
app.use(express.json());
// simple
app.post('/myFlow', handler(myFlow));
// with auth
app.post(
'/myFlowAuth',
async (req, res, next) => {
const token = req.header('authorization');
// pretend we verify the auth token
(req as any).auth = { user: token };
next();
},
handler(myFlow, {
authPolicy: ({ auth, flow, input, request }) => {
if (auth.user !== 'authorized') {
throw new Error('not authorized');
}
},
})
);
app.listen(5000, () => {
console.log(`Example app listening on port ${port}`);
});
```
=> feat(js/plugins/express): added new express plugin for various express integrations

js/plugins/firebase/src/auth.ts, js/plugins/firebase/tests/auth_test.ts, js/testapps/esm/src/index.ts
=> fix(js/plugins/firebase): fix imports for ESM compatibility in firebase auth

genkit-tools/common/src/eval/evaluate.ts, genkit-tools/common/src/eval/localFileDatasetStore.ts
=> fix(evals): Bugbash - Error if empty dataset, fix message formatting

js/core/src/logging.ts
=> fix(js/core): make sure genkit logger is a true global singleton

docs/plugins/firebase.md
docs: update Firebase plugin docs for 0.9
This is PR includes several general improvements and corrections. The main correction is removing the outdated `firebase()` plugin initialization.
=> docs: update Firebase plugin docs for 0.9

genkit-tools/common/src/manager/manager.ts, genkit-tools/common/src/manager/types.ts, genkit-tools/common/src/server/router.ts, genkit-tools/common/src/server/server.ts, genkit-tools/common/src/types/error.ts, js/core/src/action.ts, js/core/src/reflection.ts, js/testapps/flow-simple-ai/src/index.ts
=> fix(js/core): correctly handle errors when streaming

js/plugins/googleai/src/gemini.ts, js/plugins/googleai/src/index.ts, js/plugins/vertexai/src/gemini.ts, js/plugins/vertexai/src/index.ts
Apply https://github.com/firebase/genkit/pull/1493 to `main` branch.
=> feat: add Gemini 2.0 Flash Experimental support to Google AI and Vertex AI plugins

js/ai/src/chat.ts, js/ai/src/generate.ts, js/core/src/action.ts, js/core/src/flow.ts, js/genkit/tests/generate_test.ts, js/genkit/tests/helpers.ts, js/plugins/dotprompt/src/prompt.ts, js/plugins/dotprompt/tests/prompt_test.ts, js/plugins/express/tests/express_test.ts, js/plugins/mcp/tests/mcp_test.ts, js/testapps/express/src/index.ts
=> feat: renamed generate(streamingCallback) to generate(onChunk)

js/genkit/src/genkit.ts, js/genkit/tests/prompts_test.ts, js/plugins/dotprompt/src/index.ts
=> fix(js/genkit): add prompt metadata to registry for function-based prompts

genkit-tools/common/src/eval/localFileDatasetStore.ts, genkit-tools/common/tests/eval/localFileDatasetStore_test.ts
=> fix(evals): Let datasetIds start with capitals

js/plugins/googleai/src/gemini.ts
See: https://github.com/firebase/genkit/issues/1520
=> fix(js/plugins/googleai): work around googleai forced tool calling infinite loop

js/ai/src/generate.ts, js/ai/src/generate/action.ts, js/genkit/tests/generate_test.ts, js/plugins/dotprompt/src/prompt.ts, js/plugins/dotprompt/tests/prompt_test.ts
```ts
await ai.generate({
prompt: 'call the tool',
tools: ['testTool'],
maxTurns: 17,
})
```
Issue: https://github.com/firebase/genkit/issues/1520
=> feat(js/ai): added `maxTurns` option to generate options

js/plugins/vertexai/src/gemini.ts
=> fix(js/plugins/vertexai): work around vertexai forced tool calling infinite loop

.github/ISSUE_TEMPLATE/dev-ui-feature.md
Create dev-ui-feature.md
- We need a new template for detailed feature tickets for the Dev UI
=> Adding a new issue template for Dev UI feature

js/plugins/pinecone/src/index.ts
=> docs: pinecone docs

docs/monitoring.md
Update text to reference name of monitoring product and link to dashboard
=> docs: update monitoring dashboard links

js/ai/src/prompt.ts, js/genkit/src/genkit.ts, js/genkit/tests/prompts_test.ts, js/plugins/dotprompt/src/index.ts, js/plugins/dotprompt/src/metadata.ts, js/plugins/dotprompt/src/prompt.ts, js/plugins/dotprompt/tests/prompt_test.ts
https://discord.com/channels/1255578482214305893/1318362743690100788/1318363331484188765
=> fix(js): make sure middleware is applied by prompts

genkit-tools/package.json, js/package.json, package.json
Figures, the day after I decide to finally upgrade, they drop another patch release... LOL
=> chore: update to pnpm v9.15.1

js/ai/src/retriever.ts
Fixed missing return statement causing unwanted failure
=> fix: missing return in retriever

go/core/action_test.go
Test case was expecting a different action name
=> fix(go): Fix TestActionTracing test case

js/plugins/google-cloud/src/gcpOpenTelemetry.ts, js/plugins/google-cloud/tests/traces_test.ts
Addressing missing failedSpan and failedPath attributes when a failure happens in the root span.
=> fix(js): Marking root spans that have failed

docs/plugin-authoring-evaluator.md
Revisions to this file as merged in [PR #1512](https://github.com/firebase/genkit/pull/1512)
=> Docs: Update plugin-authoring-evaluator.md

docs/plugins/firebase.md
Clarify the language to indicate that the Firebase plugin and the Google Cloud plugin share configuration options.
=> Make the telemetry instructions more clear.

genkit-tools/cli/src/commands/eval-extract-data.ts, genkit-tools/cli/src/commands/eval-flow.ts, genkit-tools/cli/src/commands/eval-run.ts, genkit-tools/common/src/eval/evaluate.ts, genkit-tools/common/src/eval/index.ts, genkit-tools/common/src/eval/localFileDatasetStore.ts, genkit-tools/common/src/types/apis.ts, genkit-tools/common/src/types/eval.ts, genkit-tools/common/src/utils/eval.ts, js/tsconfig.json
=> fix(evals): make testcaseId and traceId optional in input formats, refactor

js/genkit/tsconfig.json, js/tsconfig.json
=> fix: move lib options down in scope

docs/plugins/firebase.md
Expand the Firebase plugin telemetry section by listing all the necessary API's and roles that need to be enabled.
=> Clarify Firebase plugin documentation

docs/monitoring.md
=> docs: Make observability docs, Firebase Genkit monitoring centric.

docs/plugins/google-cloud.md
Docs: Replaces internal URL with one accessible to non-Google developers.
=> Docs: Update google-cloud.md

js/plugins/google-cloud/src/auth.ts
We have some helpful error messaging to help users apply the necessary roles to their GCP service accounts for telemetry exports. We look up the logged in service account to customize the messaging. If the lookup
fails we need to handle those errors properly.
Resolves: https://discord.com/channels/1255578482214305893/1315032928886984755
- [NA] Docs updated (updated docs or a docs bug required)
=> fix(js/plugins/google-cloud): Catch errors looking for ADC

genkit-tools/common/src/types/model.ts, genkit-tools/genkit-schema.json, js/ai/src/generate.ts, js/ai/src/generate/action.ts, js/ai/src/generate/resolve-tool-requests.ts, js/ai/src/model.ts, js/ai/tests/formats/json_test.ts, js/ai/tests/generate/action_test.ts, js/ai/tests/helpers.ts, js/ai/tests/prompt/prompt_test.ts, js/core/tests/action_test.ts, js/genkit/src/genkit.ts
=> feat(js): added /util/generate action to be exposed to the dev ui

js/ai/src/prompt.ts, js/genkit/tests/prompts_test.ts
=> fix(js/ai/prompt): also delete null description from input schema

js/ai/src/prompt.ts, js/core/src/action.ts, js/core/src/async.ts, js/core/src/registry.ts, js/core/tests/async_test.ts
=> fix(js/ai/prompt): lazy load dotprompt files to avoid initialization race conditions

.github/workflows/builder.yml, js/ai/src/prompt.ts, js/core/src/action.ts, js/core/src/async.ts, js/genkit/tests/prompts/badSchemaRef.prompt, js/genkit/tests/prompts_test.ts
=> fix(js/ai/prompt): fix prompt loading in node 20, make sure-sure that .prompt loading is lazy

.gitignore, samples/chatbot/package-lock.json, samples/js-angular/package-lock.json, samples/js-character-generator/package-lock.json, samples/js-coffee-shop/package-lock.json, samples/js-menu/package-lock.json, samples/js-schoolAgent/package-lock.json, samples/js-schoolAgent/package.json, samples/prompts/package-lock.json
Helps prevent CI flakiness.
- [N/A] Tested (manually, unit tested, etc.)
- [N/A] Docs updated (updated docs or a docs bug required)
=> chore: include package-lock files for samples

js/ai/src/generate.ts, js/genkit/tests/prompts/output.prompt, js/genkit/tests/prompts_test.ts
=> fix(js/ai): default to JSON format when schema is set

samples/js-coffee-shop/README.md, samples/js-coffee-shop/package-lock.json, samples/js-coffee-shop/package.json
Updates js-coffeeshop to 1.0
- [x ] PR title is following https://www.conventionalcommits.org/en/v1.0.0/
- [ x] Docs updated (updated docs or a docs bug required)
=> chore: Update js-coffeeshop to 1.0

js/testapps/dev-ui-gallery/src/genkit.ts
=> chore: add all vertex models to the dev-ui-gallery test app

js/ai/src/chat.ts, js/genkit/tests/chat_test.ts, js/genkit/tests/session_test.ts
```ts
const { response, stream } = chat.sendStream('hi');
```
=> refactor(js/ai/chat): make sendStream sync

js/ai/src/prompt.ts
=> fix(js/ai/prompts): fix prompt loading on node 18

js/core/src/context.ts, js/core/src/index.ts, js/genkit/src/beta.ts, js/genkit/src/genkit.ts, js/genkit/src/index.ts, js/genkit/tests/formats_test.ts, js/genkit/tests/generate_test.ts, js/genkit/typedoc.json
=> chore(js): moved defineFormat and defineInterrupt to beta, api ref fixes

samples/js-schoolAgent/README.md, samples/js-schoolAgent/package-lock.json, samples/js-schoolAgent/package.json, samples/js-schoolAgent/src/genkit.ts
=> chore: update school agent sample to 1.0

docs/evaluation.md
Fixes https://github.com/firebase/genkit/issues/1617
=> fix: update API ref link

samples/js-menu/package.json, samples/js-menu/src/03/flows.ts, samples/js-menu/src/types.ts
=> chore: update menu sample to 1.0

js/plugins/vertexai/package.json, js/pnpm-lock.yaml
=> chore(js/plugins/vertexai): bump vertexai SDK to 1.9.3

samples/js-angular/README.md, samples/js-angular/genkit-app/package-lock.json, samples/js-angular/genkit-app/package.json, samples/js-angular/genkit-app/src/app/samples/chatbot/chatbot.component.ts, samples/js-angular/genkit-app/src/app/samples/streaming-json/streaming-json.component.ts, samples/js-angular/server/package-lock.json, samples/js-angular/server/package.json, samples/js-angular/server/src/agent.ts, samples/js-angular/server/src/index.ts
Updates js-chat
Also fixes the steps in the readme 
=> chore: update-js-chat-to-1.0

docs/plugins/firebase.md, docs/plugins/google-genai.md, docs/plugins/ollama.md, docs/plugins/vertex-ai.md, docs/templates/pgvector.md, js/plugins/chroma/src/index.ts, js/plugins/evaluators/src/metrics/answer_relevancy.ts, js/plugins/firebase/src/firestoreRetriever.ts, js/plugins/ollama/tests/embedding_live_test.ts, js/plugins/vertexai/src/vectorsearch/vector_search/retrievers.ts, js/testapps/multimodal/src/genkit.ts, js/testapps/multimodal/src/pdf.ts, js/testapps/multimodal/src/video.ts
test: Add pinecone to multimodal testapp
test: Add chromaDb to multimodal testapp
fix: Fix bugs found during chromaDb testing
docs: Fixed docs for ai.embed references
=> fix: multimodal bugs in Chroma fixed

docs/auth.md, docs/evaluation.md, genkit-tools/cli/src/commands/eval-flow.ts, genkit-tools/cli/src/commands/flow-batch-run.ts, genkit-tools/cli/src/commands/flow-run.ts, genkit-tools/common/src/eval/evaluate.ts, genkit-tools/common/src/types/apis.ts
=> fix: update `auth` to `context` in CLI

docs/devtools.md
=> docs: Update devtools.md to reference an existing runtime running.

docs/chat.md
=> docs: Update chat.md to Genkit beta.

docs/dotprompt.md, js/doc-snippets/src/dotprompt/index.ts
=> fix: dotprompt docs

docs/templates/pgvector.md
=> fix: syntax in pgvector

docs/interrupts.md
=> docs: New page about interrupts

docs/plugins/firebase.md
=> chore(docs): Fix merge conflict markers in plugins/firebase.md

samples/js-chatbot/server/src/index.ts
=> fix: fix chatbot chunk

.github/workflows/scripts/ensure-clean-working-tree.sh
Help debug failures like https://github.com/firebase/genkit/actions/runs/13162235661/job/36733626823
=> update working tree output to be more verbose

docs/auth.md, docs/chat.md, docs/devtools.md, docs/dotprompt.md, docs/evaluation.md
This PR contains edits made after an editorial and production pass.
=> docs: Edits to docs for GA release

package.json, pnpm-lock.yaml
Fixes e2e test failure introduced in https://github.com/firebase/genkit/pull/1839
=> fix: include updated pnpm files

js/plugins/googleai/src/gemini.ts, js/plugins/googleai/src/index.ts, js/plugins/vertexai/src/gemini.ts, js/plugins/vertexai/src/index.ts
=> feat(js/plugins): added new gemini 2.0 models to googleai and vertexai plugins

docs/codelabs/codelab-chat-with-a-pdf.md
This PR is a template-based structural overhaul of this doc.
=> docs: Restructuring of codelab-chat-with-a-pdf.md

genkit-tools/common/src/eval/evaluate.ts, genkit-tools/common/src/eval/validate.ts, genkit-tools/common/src/utils/eval.ts
Part of https://github.com/firebase/genkit/issues/1554
=> feat: support model validation

js/ai/src/generate/action.ts, js/ai/src/generate/resolve-tool-requests.ts, js/genkit/tests/generate_test.ts
=> fix(js): stream tool message generated by interrupt resume

samples/idx-template.json, samples/js-chatbot/genkit-app/package-lock.json, samples/js-chatbot/genkit-app/package.json, samples/js-chatbot/package-lock.json, samples/js-chatbot/package.json, samples/js-chatbot/server/package-lock.json, samples/js-chatbot/server/package.json, samples/js-coffee-shop/package-lock.json, samples/js-coffee-shop/package.json, samples/js-menu/package-lock.json, samples/js-menu/package.json, samples/js-prompts/package-lock.json, samples/js-prompts/package.json, samples/js-schoolAgent/package-lock.json, samples/js-schoolAgent/package.json
Update the samples to 1.0.0.rc17
This PR can be tested here:
<a href="https://idx.google.com/new?template=https%3A%2F%2Fgithub.com%2Ffirebase%2Fgenkit%2Ftree%2Fupdate-samples-to-1.0.0.rc17%2Fsamples">
<img
height="32"
alt="Open in IDX"
src="https://cdn.idx.dev/btn/open_purple_32.svg">
</a>
=> fix: update-samples-to-v17

docs/plugins/ollama.md
=> fix: minor fixes in ollama plugin doc

samples/js-angular/genkit-app/package-lock.json, samples/js-angular/genkit-app/package.json, samples/js-angular/server/package-lock.json, samples/js-angular/server/package.json, samples/js-chatbot/genkit-app/package-lock.json, samples/js-chatbot/genkit-app/package.json, samples/js-chatbot/server/package-lock.json, samples/js-chatbot/server/package.json, samples/js-coffee-shop/package-lock.json, samples/js-coffee-shop/package.json, samples/js-menu/package-lock.json, samples/js-menu/package.json, samples/js-prompts/package-lock.json, samples/js-prompts/package.json, samples/js-schoolAgent/package-lock.json, samples/js-schoolAgent/package.json
=> chore: update samples to 1.0.0.rc.18

js/ai/package.json, js/core/package.json, js/plugins/evaluators/package.json, js/pnpm-lock.yaml
=> chore(js): bump dotprompt version in the lock file

genkit-tools/common/src/eval/validate.ts, genkit-tools/common/src/utils/eval.ts
=> fix: graceful handling of model input conversion

docs/context.md
=> docs: minor editorial revisions to context.md

docs/migrating-from-0.9.md
=> docs: add Embed breaking changes to 0.9 migration guide

samples/js-character-generator/index.ts, samples/js-character-generator/package-lock.json, samples/js-character-generator/package.json
Updates to 1.0 syntax
A little improvement to the start script to prompt for a Gemini Key
- [ x] PR title is following https://www.conventionalcommits.org/en/v1.0.0/
- [ x] Docs updated (updated docs or a docs bug required)
=> chore: update to 1.0 syntax

samples/js-angular/genkit-app/package-lock.json, samples/js-angular/genkit-app/package.json, samples/js-angular/server/package-lock.json, samples/js-angular/server/package.json, samples/js-chatbot/genkit-app/package-lock.json, samples/js-chatbot/genkit-app/package.json, samples/js-chatbot/genkit-app/tsconfig.json, samples/js-chatbot/server/package-lock.json, samples/js-chatbot/server/package.json, samples/js-coffee-shop/package-lock.json, samples/js-coffee-shop/package.json, samples/js-menu/package-lock.json, samples/js-menu/package.json, samples/js-prompts/package-lock.json, samples/js-prompts/package.json, samples/js-schoolAgent/package-lock.json, samples/js-schoolAgent/package.json
=> chore: update samples to 1.0.4

docs/migrating-from-0.9.md
=> docs: fix list in migration docs

docs/auth.md, docs/index.md, docs/migrating-from-0.5.md, docs/migrating-from-0.9.md
docs: This PR brings the public docs repo into sync with the content on DevSite
=> docs: Post-GA backports from DevSite repo

js/plugins/firebase/typedoc.json
=> docs: fix typedoc.json for firebase plugin to include all modules

docs/migrating-from-0.5.md
docs: Updates title to clarify scope of migration.
=> docs: update title of migrating-from-0.5.md

js/typedoc-ga.mjs, js/typedoc.json
=> chore(docs): added GA to js api ref

js/plugins/googleai/src/gemini.ts, js/plugins/googleai/src/index.ts
=> feat(js/ai/googleai): added gemini-2.0-pro-exp-02-05

js/plugins/googleai/src/common.ts, js/plugins/googleai/src/embedder.ts, js/plugins/googleai/src/gemini.ts
=> feat(js/plugins/googleai): added GEMINI_API_KEY as possible env var for API key

docs/plugins/google-cloud.md
=> Update google-cloud.md to remove internal link

docs/_guides.yaml, docs/cloud-run.md, docs/deploy-node.md, docs/local-observability.md, docs/observability/getting-started.md, docs/observability/troubleshooting.md, docs/plugins/google-cloud.md
docs: delta from internal cl/725855143
=> docs: Resolves delta between GH and google3 for Observability docs.

docs/_guides.yaml, docs/auth.md, docs/chat.md, docs/cloud-run.md, docs/index.md, docs/interrupts.md, docs/local-observability.md, docs/multi-agent.md
=> docs: Resolves deltas between internal and GH docs

docs/api-stability.md
=> docs: Fixes typo in api-stability.md

docs/codelabs/codelab-chat-with-a-pdf.md
This PR fixes the following issues:
- Use Gemini 2.0 Flash
- In Genkit 1.0, the `chat` feature needs to be imported from the `beta` namespace
- Ensures that the correct TypeScript types are installed for the PDF library
- Fixes missing comment slashes for step 5
- Cleans up the formatting, using plain Markdown
- Made it easier to follow the implementation steps by including the comments in the code snippets
- Made sure all commands will be executed in the correct folder
I verified the formatting by staging this file in DevSite.
=> (docs) update codelab for Genkit 1.0

js/plugins/evaluators/src/index.ts
=> fix: remove extraneous line

go/plugins/googleai/googleai.go
=> feat(go): add gemini-2.0-pro-exp-02-05

docs/observability/advanced-configuration.md, docs/observability/authentication.md, docs/observability/getting-started.md, docs/observability/telemetry-collection.md, docs/observability/troubleshooting.md, docs/plugins/firebase.md
=> docs(observability): More linting fixes for line length

CONTRIBUTING.md
Updated contribution guide to add instructions for GO developers, per conversation with @apascal07. Additionally, updated branch naming convention to be consistent with majority of active branches in repo. 
=> docs(contribution): update contribution guide to include GO

js/testapps/flow-sample1/src/index.ts
Corrects the execution code comment for the streamyThrowy flow, updating it from streamy.
=> fix(js/testapps/flow-sample1): correct flow execution comment for streamyThrowy

js/plugins/googleai/src/gemini.ts, js/plugins/vertexai/src/gemini.ts
We noticed that metrics are missing for streaming results for Gemini model calls in AIM. Refactored things a bit so that we process the final streaming result and non-streaming result the same way.
cc @schnecle
=> fix: add usage stats for streaming results

docs/observability/advanced-configuration.md, docs/observability/authentication.md, docs/observability/getting-started.md, docs/observability/telemetry-collection.md, docs/observability/troubleshooting.md, docs/plugins/firebase.md
=> docs(observability): Backport docs changes to Github

genkit-tools/common/src/types/model.ts, genkit-tools/genkit-schema.json, py/packages/genkit/src/genkit/ai/generate.py, py/packages/genkit/src/genkit/ai/generate_test.py, py/packages/genkit/src/genkit/ai/model.py, py/packages/genkit/src/genkit/core/action.py, py/packages/genkit/src/genkit/core/codec.py, py/packages/genkit/src/genkit/core/registry.py, py/packages/genkit/src/genkit/core/typing.py, py/packages/genkit/src/genkit/veneer/veneer.py, py/samples/hello/src/hello.py
=> feat(py): started generate action with basic tools calling

py/packages/genkit/src/genkit/veneer/veneer.py, py/plugins/vertex-ai/src/genkit/plugins/vertex_ai/__init__.py, py/plugins/vertex-ai/src/genkit/plugins/vertex_ai/imagen.py, py/plugins/vertex-ai/src/genkit/plugins/vertex_ai/plugin_api.py, py/plugins/vertex-ai/tests/test_gemini.py, py/plugins/vertex-ai/tests/test_imagen.py, py/samples/vetex-ai-imagen/LICENSE, py/samples/vetex-ai-imagen/README.md, py/samples/vetex-ai-imagen/example_imagen.py, py/samples/vetex-ai-imagen/pyproject.toml, py/uv.lock
- This is Imagen model added as a part of VertexAI. It generates an image based on prompt and saves into the folder from which it is called.
=> feat(py): Basic imagen

go/internal/doc-snippets/dotprompt.go, go/plugins/googleai/googleai.go, go/plugins/vertexai/vertexai.go, go/samples/basic-gemini/main.go, go/samples/coffee-shop/main.go, go/samples/menu/s02.go, go/samples/menu/s04.go, go/samples/rag/main.go
=> fix(go): Fixed `nil` options on `Generate()` calls in samples.

genkit-tools/cli/package.json, js/core/package.json
=> chore(js): added force flag to genversion to overwrite generated files

samples/js-angular/README.md, samples/js-angular/server/package-lock.json, samples/js-angular/server/package.json, samples/js-angular/server/src/chatbot.ts, samples/js-angular/server/src/genkit.ts, samples/js-angular/server/src/jsonStreaming.ts
=> sample: migrated js-angular samples to use Google AI instead of Vertex AI for easier set up

py/packages/genkit/pyproject.toml, py/packages/genkit/src/genkit/core/extract.py, py/packages/genkit/tests/genkit/core/extract_test.py, py/uv.lock
=> feat(py/core): implemented json extractor library (based on JS impl)

py/packages/genkit/src/genkit/core/schema.py, py/packages/genkit/tests/genkit/core/schema_test.py
=> chore(py/core/schema): added docstrings and tests

py/packages/genkit/src/genkit/ai/model.py, py/packages/genkit/src/genkit/veneer/veneer_test.py, py/packages/genkit/tests/genkit/ai/generate_test.py, py/packages/genkit/tests/genkit/ai/model_test.py
=> feat(pj/ai): added text/output methods to response and chunk wrappers

genkit-tools/common/src/types/model.ts, genkit-tools/genkit-schema.json
=> fix: sync model types in genkit-tools

go/tests/test_app/main.go
=> fix(go): Fixed e2e tests.

genkit-tools/common/src/server/server.ts
=> chore(cli): bump max dev ui request size to 30mb (from 100kb)

go/plugins/googleai/googleai.go, go/plugins/googleai/googleai_test.go, go/plugins/internal/gemini/gemini.go, go/plugins/vertexai/vertexai.go
Some end-to-end tests `plugins/googleai` were failing before and are still failing (#2190).
Resolves #2177
=> feat(go/plugins/googleai): Respect `ToolChoice` setting

go/ai/action_test.go, go/ai/generate.go, go/ai/generator_test.go, go/ai/model_middleware.go, go/ai/model_middleware_test.go, go/genkit/genkit.go, go/internal/doc-snippets/modelplugin/modelplugin.go, go/plugins/dotprompt/genkit.go, go/plugins/googleai/googleai.go, go/plugins/vertexai/vertexai.go, go/samples/basic-gemini/main.go
=> refactor(go): Moved model version validation to middleware.

js/plugins/firebase/package.json, js/plugins/firebase/src/firestoreRetriever.ts, js/pnpm-lock.yaml, js/testapps/rag/src/pdf-rag-firebase.ts
=> feat(js/plugins/firebase): Expose vector distance and distance threshold options in Firestore vector store retriever

go/ai/prompt/execute.go, go/ai/prompt/render_test.go
=> fix(go): Fixed stream callback naming.

py/packages/genkit/src/genkit/core/action.py, py/packages/genkit/tests/genkit/core/action_test.py
=> feat(py/core): propagate action context to sub actions via contextvar

py/packages/genkit/src/genkit/ai/generate.py, py/packages/genkit/src/genkit/ai/model.py, py/packages/genkit/src/genkit/core/action.py, py/packages/genkit/src/genkit/veneer/veneer.py, py/packages/genkit/src/genkit/veneer/veneer_test.py, py/packages/genkit/tests/genkit/ai/generate_test.py
Also fixed/implemented generate method context handling
=> feat(py/ai): implemented model middleware framework

genkit-tools/common/src/eval/evaluate.ts
=> fix(evals): populate `testcaseId` when inference failed

genkit-tools/common/src/types/document.ts, genkit-tools/common/src/types/reranker.ts, genkit-tools/genkit-schema.json, js/ai/src/document.ts, js/ai/src/reranker.ts, py/packages/genkit/src/genkit/ai/generate.py, py/packages/genkit/src/genkit/core/typing.py, py/packages/genkit/src/genkit/veneer/veneer_test.py, py/plugins/vertex-ai/src/genkit/plugins/vertex_ai/imagen.py, py/plugins/vertex-ai/tests/test_imagen.py
=> chore(typing): cleanup more json schema and python model generation

py/packages/genkit/src/genkit/core/reflection.py, py/packages/genkit/src/genkit/veneer/veneer.py
=> fix(py): write runtime file at server startup

py/packages/genkit/src/genkit/ai/generate.py, py/packages/genkit/src/genkit/ai/middleware.py, py/packages/genkit/src/genkit/ai/model.py, py/packages/genkit/src/genkit/ai/prompt.py, py/packages/genkit/src/genkit/veneer/veneer.py, py/packages/genkit/tests/genkit/ai/generate_test.py, py/packages/genkit/tests/genkit/ai/middleware_test.py, py/packages/genkit/tests/genkit/veneer/veneer_test.py
=> feat(py/ai): implemented augment context middleware to simulate grounding with provided docs

genkit-tools/common/src/types/trace.ts, genkit-tools/genkit-schema.json, genkit-tools/telemetry-server/src/index.ts, go/core/tracing/trace_server_exporter.go
also fixed telemetry server error handling
=> fix({go,cli}): relax time event shema

go/samples/rag/main.go
=> fix(go/samples/rag): Fixed `rag` sample missing template.

py/packages/genkit/src/genkit/core/action.py, py/packages/genkit/src/genkit/core/constants.py, py/packages/genkit/src/genkit/core/error.py, py/packages/genkit/src/genkit/core/reflection.py, py/packages/genkit/tests/genkit/core/action_test.py, py/packages/genkit/tests/genkit/core/error_test.py, py/samples/hello/src/hello.py
=> feat(py/core): implemented reflection api error handling and encoding

go/ai/gen.go
=> fix(go): Fixed duplicate `Score`.

go/ai/action_test.go, go/ai/gen.go, go/ai/generate.go, go/ai/generator_test.go, go/ai/model_middleware.go, go/ai/model_middleware_test.go, go/ai/prompt_test.go, go/core/schemas.config, go/internal/doc-snippets/modelplugin/modelplugin.go, go/internal/doc-snippets/ollama.go, go/plugins/internal/gemini/gemini.go, go/plugins/ollama/ollama.go
=> refactor(go): Added better naming for generated types.

py/plugins/google-genai/src/genkit/plugins/google_genai/google.py, py/plugins/google-genai/src/genkit/plugins/google_genai/models/gemini.py, py/plugins/google-genai/test/models/test_googlegenai_gemini.py, py/samples/google_genai/src/hello.py
- Works only in case VertexAI is set
=> feat(py): Gemini API tools

py/packages/genkit-ai/src/genkit/ai/__init__.py, py/plugins/google-genai/pyproject.toml, py/plugins/google-genai/src/genkit/plugins/google_genai/__init__.py, py/plugins/google-genai/src/genkit/plugins/google_genai/google.py, py/plugins/google-genai/src/genkit/plugins/google_genai/models/embedder.py, py/plugins/google-genai/src/genkit/plugins/google_genai/models/gemini.py, py/plugins/google-genai/src/genkit/plugins/google_genai/models/utils.py, py/plugins/google-genai/test/models/test_googlegenai_embedder.py, py/samples/google_genai/src/hello.py
Added embedders to Google Genai
- moved PartConverter to utils module
- added handling of jsonmode
=> feat(py): Google Genai embeddings

py/packages/genkit-ai/src/genkit/core/action.py
=> fix(py/core): correctly set action subtype

go/plugins/googlegenai/googleai_live_test.go, go/plugins/googlegenai/vertexai_live_test.go, go/plugins/internal/gemini/gemini.go, go/plugins/internal/uri/uri.go
=> feat(go/plugins/googlegenai): Added data part support

go/ai/generate.go, go/ai/generator_test.go, go/ai/prompt.go, go/genkit/genkit.go, go/genkit/reflection.go, go/genkit/servers.go, go/internal/registry/registry.go, go/plugins/googlegenai/googlegenai.go, go/plugins/internal/gemini/gemini.go, go/plugins/ollama/ollama.go, go/samples/prompts/main.go
=> docs(go): Updated package docs and made various fixes along the way

py/packages/genkit-ai/src/genkit/ai/veneer.py, py/packages/genkit-ai/src/genkit/aio/loop.py, py/packages/genkit-ai/src/genkit/core/action.py, py/packages/genkit-ai/src/genkit/core/reflection.py, py/samples/google_genai/src/hello.py, py/samples/hello/src/hello.py
=> fix(py): a temporaty workaround for event loop scheduling issue

genkit-tools/common/src/eval/parser.ts, go/ai/evaluator.go, js/ai/src/embedder.ts, js/ai/src/evaluator.ts, js/ai/src/reranker.ts, js/ai/src/retriever.ts
Fixes: #2349 
Part of https://github.com/firebase/genkit/issues/2449
Also see: https://github.com/FirebasePrivate/genkit-ui/pull/1325
=> fix: make customOptions consistent in action metadata

py/packages/genkit-ai/src/genkit/ai/veneer.py, py/packages/genkit-ai/src/genkit/aio/loop.py, py/packages/genkit-ai/src/genkit/core/reflection.py, py/samples/google_genai/src/hello.py
=> refactor(py/aio): don't require loop.run_forever, run until completion as necessary

.github/workflows/tests.yml
=> chore: fixed run tests GHA triggering

go/ai/generate.go, go/ai/prompt.go
=> fix(go): Fixed default input for prompts.

py/plugins/compat-oai/src/genkit/plugins/compat_oai/models/model.py, py/plugins/compat-oai/tests/conftest.py, py/plugins/compat-oai/tests/test_model.py, py/samples/openai/src/main.py
Add system instructions support: https://github.com/firebase/genkit/issues/2500
=> feat(py): add system instructions support for openai-compat plugin

go/genkit/genkit.go, go/internal/version.go
=> docs(go/genkit): Updated `genkit` package docs and increment version

py/packages/genkit-ai/src/genkit/blocks/generate.py, py/packages/genkit-ai/src/genkit/core/action.py
=> chore(py): delete print debug statements

py/packages/genkit-ai/src/genkit/ai/__init__.py, py/packages/genkit-ai/src/genkit/blocks/prompt.py, py/plugins/google-genai/src/genkit/plugins/google_genai/__init__.py, py/plugins/google-genai/src/genkit/plugins/google_genai/google.py, py/plugins/google-genai/src/genkit/plugins/google_genai/models/gemini.py, py/samples/hello-google-genai/src/hello.py
=> fix(py/plugins/genai): expose full Gemini config schema

py/plugins/google-genai/src/genkit/plugins/google_genai/models/gemini.py, py/plugins/google-genai/test/models/test_googlegenai_gemini.py, py/samples/hello-google-genai/src/hello_google_genai.py
=> fix(py/plugins/genai): currecly handle enum and nested schemas

py/packages/genkit-ai/src/genkit/ai/__init__.py, py/packages/genkit-ai/src/genkit/core/__init__.py, py/packages/genkit-ai/src/genkit/core/constants.py, py/packages/genkit-ai/src/genkit/core/registry.py, py/plugins/google-ai/pyproject.toml, py/plugins/google-genai/pyproject.toml, py/plugins/google-genai/src/genkit/plugins/google_genai/google.py, py/uv.lock
=> fix(py-plugins/genai): added attribution headers to genai plugin

go/genkit/genkit.go
=> feat(go): Call `DefineGenerateAction` in `Genkit.Init`

.github/workflows/publish_python.yml, py/bin/publish_pypi.sh, py/packages/genkit-ai/pyproject.toml, py/plugins/compat-oai/pyproject.toml, py/plugins/dev-local-vector-store/pyproject.toml, py/plugins/firebase/pyproject.toml, py/plugins/flask/pyproject.toml, py/plugins/google-cloud/pyproject.toml, py/plugins/google-genai/pyproject.toml, py/plugins/ollama/pyproject.toml, py/plugins/vertex-ai/pyproject.toml
=> chore(python): prepare CI for pypi publishing

go/ai/generate.go, go/ai/generator_test.go, go/ai/model_middleware.go, go/plugins/googlegenai/models.go
Models now expose their current release state (deprecated, unstable, legacy, featured, etc) 
=> feat(go/plugins): Add model `stage` support

py/docs/reference/interrupts.md, py/docs/reference/tools.md, py/mkdocs.yml, py/uv.lock
=> docs(py): added tool and interrupt docs

genkit-tools/common/src/types/model.ts, genkit-tools/genkit-schema.json, go/ai/gen.go, js/ai/src/model.ts, py/packages/genkit-ai/src/genkit/core/typing.py
This unblocks using CustomConfig in Go.
=> Add customConfig field to ModelInfo

py/docs/flask.md, py/packages/genkit-ai/src/genkit/core/context.py, py/packages/genkit-ai/src/genkit/types/__init__.py, py/plugins/flask/src/genkit/plugins/flask/handler.py, py/samples/hello-flask/README.md, py/samples/hello-flask/src/hello_flask.py
=> feat(py): added context provider and implemented for flask plugin

py/docs/get-started.md
- [x ] PR title is following https://www.conventionalcommits.org/en/v1.0.0/
=> docs(py): update get-started.md

py/docs/index.md, py/packages/genkit-ai/src/genkit/ai/plugin.py, py/plugins/google-genai/src/genkit/plugins/google_genai/__init__.py, py/plugins/google-genai/src/genkit/plugins/google_genai/google.py, py/plugins/google-genai/src/genkit/plugins/google_genai/models/gemini.py, py/plugins/google-genai/test/models/test_googlegenai_gemini.py, py/samples/google-genai-image/src/google_genai_image.py, py/samples/google-genai-imagen/README.md, py/samples/google-genai-imagen/src/google_genai_imagen.py, py/samples/hello-google-genai-vertexai/LICENSE, py/samples/hello-google-genai-vertexai/README.md, py/samples/hello-google-genai-vertexai/pyproject.toml, py/samples/hello-google-genai-vertexai/src/hello_google_genai_vertexai.py, py/uv.lock
- Separate plugin into two entrypoints, but leave Gemini model as a common class
=> feat(py): Separate GoogleAI and VertexAI inside of GenAI plugin

py/docs/get-started.md, py/docs/index.md
=> docs(py): updated code samples

go/ai/prompt.go
=> fix(go): add tool to prompt metadata

docs/plugins/firebase.md, docs/plugins/vertex-ai.md
=> fix: Rag docs links in plugin docs

go/genkit/genkit.go
=> feat(go/genkit): Exposed `DefineFormat` in `Genkit`.

py/plugins/ollama/src/genkit/plugins/ollama/models.py, py/samples/ollama-hello/src/ollama_hello.py
=> fix(py/plugins/ollama): fixed ollama tool calling

docs/auth.md
- change withContext to withContextProvider
- change UserFacingErrorError to UserFacingError
=> fix(typo): resolve typo of auth.md

go/ai/format_json.go, go/ai/format_jsonl.go, go/ai/format_text.go, go/ai/formatter.go, go/ai/formatter_test.go, go/ai/generate.go, go/ai/generator_test.go, go/ai/prompt.go, go/ai/prompt_test.go, go/ai/tools.go, go/plugins/googlegenai/cache.go, go/plugins/googlegenai/gemini.go, go/samples/basic-gemini/main.go
=> fix(go/plugins): Unpacked common fields in `GeminiConfig` and fixed output config

go/plugins/googlegenai/models.go, go/samples/basic-gemini/main.go, js/plugins/googleai/src/gemini.ts, js/plugins/googleai/src/index.ts, js/plugins/vertexai/src/gemini.ts, js/plugins/vertexai/src/index.ts
=> chore: expose model `gemini-2.5-pro-preview-03-25`

go/ai/generate.go, go/ai/prompt.go, go/ai/prompt_test.go, go/samples/prompts-dir/main.go, go/samples/prompts-dir/prompts/example.prompt
=> fix(go): Fixed prompt fields not propagating to execute for loaded prompts.

py/plugins/google-genai/src/genkit/plugins/google_genai/google.py, py/samples/hello-google-genai-vertexai/src/hello_google_genai_vertexai.py
=> fix(py/plugins/genai): made location param optional for VertexAI plugin

py/docs/get-started.md, py/docs/reference/plugins/google-genai.md, py/docs/reference/plugins/ollama.md, py/mkdocs.yml
Staged: https://genkit-py-api-staging.web.app/
=> docs(py): documented genai and ollama plugins, simplified docs nav

py/plugins/ollama/src/genkit/plugins/ollama/models.py, py/plugins/ollama/src/genkit/plugins/ollama/plugin_api.py, py/plugins/ollama/tests/conftest.py, py/samples/ollama-hello/src/ollama_hello.py, py/samples/ollama-simple-embed/src/pokemon_glossary.py
=> refactor(py/plugins/ollama): simplified ollama plugin init interface

js/plugins/firebase/typedoc.json
=> docs(js): expose data connect in typedoc

go/genkit/genkit.go, go/plugins/ollama/ollama.go, go/plugins/ollama/ollama_test.go
This fix following Issues:
- #2679 
- #2680 
=> fix(go): Fix Issues in using genkit with ollama plugin.

go/ai/evaluator.go, go/ai/evaluator_test.go, go/samples/rag/main.go
=> fix(go): metadata and status enum fixes

go/plugins/googlegenai/gemini.go
=> fix(go): Fixed nil pointer in Google AI plugin.

py/packages/genkit/pyproject.toml, py/plugins/compat-oai/pyproject.toml, py/plugins/dev-local-vectorstore/pyproject.toml, py/plugins/firebase/pyproject.toml, py/plugins/flask/pyproject.toml, py/plugins/google-cloud/pyproject.toml, py/plugins/google-genai/pyproject.toml, py/plugins/ollama/pyproject.toml, py/plugins/vertex-ai/pyproject.toml, py/uv.lock
=> chore(py): bump version to 0.3.0.dev2

py/docs/reference/models.md, py/docs/reference/tools.md, py/packages/genkit/README.md
=> docs(py): cleanup genai model refs

py/packages/genkit/README.md
=> chore(py): update README.md for genkit package

go/plugins/googlegenai/gemini.go, go/samples/basic-gemini-with-context/main.go, go/samples/cache-gemini/main.go, go/samples/menu/s03.go, go/samples/menu/s04.go, go/samples/menu/s05.go, go/samples/prompts/main.go
=> fix(go): update samples to use `GeminiConfig`

go/plugins/googlegenai/googleai_live_test.go, go/plugins/googlegenai/vertexai_live_test.go, go/samples/menu/s05.go
=> fix(go): use `GeminiConfig` in cache live tests

genkit-tools/common/package.json, genkit-tools/pnpm-lock.yaml
This will match the version of @trpc/client that the UI uses.
=> chore(genkit-tools/common): update @trpc/server to 10.45.2

go/ai/format_array.go, go/ai/format_enum.go, go/ai/formatter.go, go/ai/formatter_test.go, go/internal/base/json.go
Added new json array formatter, and enum formatter
=> feat(go/ai): added array and enum format support

go/ai/generate.go
=> fix(go/ai): pass ptr. of value for generate data in JSON (#2756)

genkit-tools/common/src/manager/manager.ts, genkit-tools/common/src/types/apis.ts, genkit-tools/telemetry-server/src/index.ts, genkit-tools/telemetry-server/src/localFileTraceStore.ts, genkit-tools/telemetry-server/src/types.ts, genkit-tools/telemetry-server/tests/file_store_test.ts
=> feat: Add experimental filter in tooling listTraces API

genkit-tools/common/src/manager/manager.ts, genkit-tools/telemetry-server/src/localFileTraceStore.ts
=> fix: Filter addition in listTraces tooling API

genkit-tools/package.json, js/package.json, package.json
https://github.com/pnpm/pnpm/releases/tag/v10.8.1
=> chore: update pnpm to v10.8.1

genkit-tools/telemetry-server/src/localFileTraceStore.ts
=> fix(cli): Set type in trace index as the action subtype

genkit-tools/common/src/eval/localFileDatasetStore.ts, genkit-tools/common/src/types/apis.ts, genkit-tools/common/src/types/eval.ts, genkit-tools/common/tests/eval/localFileDatasetStore_test.ts
API fix for https://github.com/firebase/genkit/issues/2306
=> feat(evals): Support metrics on datasetMetadata

js/plugins/googleai/src/gemini.ts, js/plugins/vertexai/src/gemini.ts
=> fix(js/plugins/{googleai,vertexai}): fixed gemini-2.5-flash-preview-04-17 refs and init

README.md
=> docs: update IDX to Firebase Studio in README

js/plugins/mcp/README.md
=> chore(js/plugins/mcp): fixes to README.md

genkit-tools/common/src/types/eval.ts
=> fix(cli): set default metricRefs

py/packages/genkit/src/genkit/ai/_base.py, py/packages/genkit/src/genkit/blocks/generate.py, py/packages/genkit/tests/genkit/blocks/generate_test.py
=> chore(py/ai): expose generate action as action

js/core/src/plugin.ts, js/core/src/registry.ts, js/genkit/src/genkit.ts, js/genkit/src/plugin.ts
=> feat(js): Dynamic action resolver support

go/go.mod, go/go.sum, go/plugins/googlegenai/gemini.go
=> chore(go/plugins/googlegenai): bump `go-genai` sdk to v1.1.0

go/plugins/googlegenai/gemini_test.go
=> fix(go/plugins/googlegenai): update test cases with new go-genai types

go/ai/generate.go
=> fix(go): fix `ModelResponse.ToolRequests()` return type

js/core/src/registry.ts, js/plugins/googleai/src/gemini.ts, js/plugins/googleai/src/index.ts, js/plugins/googleai/tests/gemini_test.ts, js/plugins/vertexai/src/index.ts, js/plugins/vertexai/tests/plugin_test.ts, js/testapps/flow-simple-ai/package.json, js/testapps/flow-simple-ai/src/index.ts, package.json, pnpm-lock.yaml
Undocumented feature for now until we support all the models.
=> refactor(js/plugins/vertexai): Dynamic model support for Gemini models

js/plugins/googleai/tests/gemini_test.ts, js/plugins/vertexai/tests/plugin_test.ts
=> refactor(js/plugins/vertexai): refactored tests for dynamic models

js/plugins/vertexai/src/imagen.ts, js/plugins/vertexai/src/index.ts, js/plugins/vertexai/src/list-models.ts
=> feat('js/plugins/vertexai'): dynamically resolve imagen models and try to list models from the API

js/doc-snippets/src/flows/index.ts, js/doc-snippets/src/index.ts, js/doc-snippets/src/models/imagen.ts, js/doc-snippets/src/models/index.ts, js/doc-snippets/src/models/minimal.ts
=> docs(js): updated code snippets to use the latest 1.8 syntax

js/plugins/googleai/src/gemini.ts, js/plugins/vertexai/src/gemini.ts
This reverts commit 58ae2e41704c33821061a8c231c13b79f574f07b.
=> revert: "feat(js): thinking mode options for Gemini models (#2851)"

py/samples/vertex-ai-vector-search-bigquery/LICENSE, py/samples/vertex-ai-vector-search-bigquery/README.md, py/samples/vertex-ai-vector-search-bigquery/pyproject.toml, py/samples/vertex-ai-vector-search-bigquery/src/sample.py, py/samples/vertex-ai-vector-search-bigquery/src/setup_env.py, py/uv.lock
Previous PR: https://github.com/firebase/genkit/pull/2833
Description:
- added vector search sample for BigQuery
- added sample to populate an index with Genkit
=> feat(py): vertex-ai vector search bigquery sample

py/plugins/vertex-ai/pyproject.toml, py/plugins/vertex-ai/src/genkit/plugins/vertex_ai/__init__.py, py/plugins/vertex-ai/src/genkit/plugins/vertex_ai/models/retriever.py, py/plugins/vertex-ai/src/genkit/plugins/vertex_ai/vector_search/vector_search.py, py/samples/vertex-ai-vector-search-bigquery/LICENSE, py/samples/vertex-ai-vector-search-bigquery/README.md, py/samples/vertex-ai-vector-search-bigquery/pyproject.toml, py/samples/vertex-ai-vector-search-bigquery/src/sample.py, py/samples/vertex-ai-vector-search-bigquery/src/setup_env.py, py/samples/vertex-ai-vector-search-firestore/LICENSE, py/samples/vertex-ai-vector-search-firestore/README.md, py/samples/vertex-ai-vector-search-firestore/pyproject.toml, py/samples/vertex-ai-vector-search-firestore/src/sample.py, py/uv.lock
Previous PR: https://github.com/firebase/genkit/pull/2833
Description:
- added Vertex AI vector search
=> feat(py): add vertex-ai vector search plugin

go/ai/generate.go, go/ai/prompt.go, go/core/action_test.go, go/core/tracing/store.go, go/genkit/genkit_test.go, go/genkit/reflection_test.go, go/genkit/servers.go, go/internal/cmd/weave/weave.go, go/plugins/firebase/retriever.go, go/plugins/firebase/retriever_test.go, go/plugins/googlecloud/slog_handler_test.go, go/plugins/googlegenai/cache_test.go, go/plugins/googlegenai/gemini_test.go, go/plugins/localvec/localvec.go, go/plugins/ollama/embed.go, go/plugins/pinecone/genkit.go, go/plugins/pinecone/pinecone_test.go, go/samples/code-execution-gemini/main.go, go/samples/firebase-retrievers/main.go, go/samples/ollama-tools/main.go
Run `modernize` happy.
Note that I'm not manually adding the `omitzero` new JSON field tag because `modernize` said :
> ignoring alternative fix "Replace omitempty with omitzero (behavior change)"
```console
$ go run golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize@latest -fix -test ./...
modernize: modernize@github.com/firebase/genkit/go/core/tracing: ignoring alternative fix "Replace omitempty with omitzero (behavior change)"
modernize: modernize@github.com/firebase/genkit/go/core/tracing: ignoring alternative fix "Replace omitempty with omitzero (behavior change)"
modernize: modernize@github.com/firebase/genkit/go/core/tracing: ignoring alternative fix "Replace omitempty with omitzero (behavior change)"
modernize: modernize@github.com/firebase/genkit/go/core/tracing: …
```
=> fix(go): run modernize happy

go/go.mod
Unify indirect `require` section in go.mod.
=> fix(go): unify indirect require section in go.mod

py/plugins/google-genai/src/genkit/plugins/google_genai/google.py, py/plugins/google-genai/test/test_google_plugin.py
Tests for GoogleAI plugin to validate correct functionality
=> chore(py): Tests for GoogleAI plugin

py/plugins/google-genai/src/genkit/plugins/google_genai/google.py
=> feat(py/plugins/genai): allow specifying API Key for VertexAI

js/plugins/googleai/src/gemini.ts, js/plugins/vertexai/src/gemini.ts
=> chore(js/plugins/googleai): added google search options to gemini config schema

.github/workflows/go.yml
Ran into formatting errors in pre-commit checks so ensuring this gets checked per PR in the CI.
=> ci(go): configure the go.yaml checks to ensure go code is properly formatted

.gitignore, js/plugins/compat-oai/.npmignore, js/plugins/compat-oai/LICENSE, js/plugins/compat-oai/README.md, js/plugins/compat-oai/jest.config.js, js/plugins/compat-oai/package.json, js/plugins/compat-oai/src/dalle.ts, js/plugins/compat-oai/src/embedder.ts, js/plugins/compat-oai/src/gpt.test.ts, js/plugins/compat-oai/src/gpt.ts, js/plugins/compat-oai/src/index.ts, js/plugins/compat-oai/src/tts.ts, js/plugins/compat-oai/src/whisper.ts, js/plugins/compat-oai/tsconfig.json, js/plugins/compat-oai/tsup.config.ts, js/plugins/compat-oai/typedoc.json, js/pnpm-lock.yaml, js/testapps/compat-oai/README.md, js/testapps/compat-oai/package.json, js/testapps/compat-oai/src/index.ts, js/testapps/compat-oai/tsconfig.json
- Added the openai compatible plugin
- Added the openai compatible sample app
=> feat(js): openai compatible plugin

go/ai/document.go, go/ai/gen.go, go/ai/generate.go, go/core/schemas.config, go/plugins/googlegenai/gemini.go, go/plugins/googlegenai/vertexai_live_test.go
=> feat(go/plugins/googlegenai): Add `reasoning` parts

js/genkit/README.md, js/genkit/package.json
=> chore(js/genkit): updated links from readme and genkit package metadata

js/plugins/googleai/src/gemini.ts, js/plugins/vertexai/src/gemini.ts, js/testapps/flow-simple-ai/src/index.ts
=> fix(js/plugins/{googleai,vertexai}): correctly passthrough custom tool definitions

js/plugins/vertexai/src/gemini.ts, js/plugins/vertexai/tests/gemini_test.ts
followup for https://github.com/firebase/genkit/pull/3014
=> fix(js/plugins/vertexai): Handle Gemini API thought signatures

js/plugins/googleai/src/gemini.ts
Fix for https://github.com/firebase/genkit/issues/3017
=> fix(js/plugins/googleai): fixed systemRole support for dynamic models

go/ai/prompt.go, go/plugins/googlegenai/googleai_live_test.go, go/plugins/googlegenai/vertexai_live_test.go, go/plugins/vertexai/modelgarden/anthropic_live_test.go, go/samples/prompts/main.go, go/samples/prompts/prompts/media.prompt
=> feat(go/dotprompt): Add support to MediaParts

js/plugins/vertexai/src/embedder.ts
=> fix(js/plugins/vertexai): fixed dynamic embedder resolution

go/plugins/googlegenai/gemini.go
- https://github.com/firebase/genkit/issues/3033
=> fix(go/plugins/googlegenai): Skip nil part

js/plugins/googleai/src/gemini.ts
=> fix(js): Add config for 2.5 Pro TTS model

go/samples/mcp-server/run-server.sh
=> chore: add license header to run-server.sh

go/plugins/googlegenai/gemini.go
=> fix(go/plugins/googlegenai): distinct text parts from thoughts

genkit-tools/common/src/types/eval.ts
=> feat: introduce combined generate input schema for validation

go/plugins/googlegenai/gemini.go, go/plugins/googlegenai/googleai_live_test.go, go/plugins/googlegenai/vertexai_live_test.go
=> chore(go/plugins/googlegenai): update live tests to use env vars

js/plugins/mcp/src/client/client.ts, js/plugins/mcp/src/client/host.ts, js/plugins/mcp/tests/fakes.ts, js/plugins/mcp/tests/host_test.ts
=> feat(js/plugins/mcp): added support for mcp roots

js/testapps/flow-simple-ai/src/index.ts
=> chore(js/testapps): tweaked audioSimple to return the media in a way that can be displayed in a ui

js/plugins/google-genai/src/common/types.ts, js/plugins/google-genai/src/googleai/gemini.ts, js/plugins/google-genai/src/googleai/types.ts, js/plugins/google-genai/src/vertexai/utils.ts, js/plugins/google-genai/tests/googleai/gemini_test.ts
=> feat(js/plugins/google-genai): Added Gemini for GoogleAI

js/plugins/google-genai/src/googleai/gemini.ts, js/plugins/google-genai/src/vertexai/converters.ts, js/plugins/google-genai/src/vertexai/gemini.ts, js/plugins/google-genai/tests/vertexai/converters_test.ts, js/plugins/google-genai/tests/vertexai/gemini_test.ts
=> feat(js/plugins/google-genai): Added Gemini for VertexAI

go/plugins/googlegenai/models.go, go/plugins/vertexai/modelgarden/anthropic.go, go/plugins/vertexai/modelgarden/models.go
=> fix(go/plugins): update gemini models and modelgarden provider

go/plugins/compat_oai/anthropic/anthropic.go, go/plugins/compat_oai/compat_oai.go, go/plugins/compat_oai/openai/openai.go
=> feat(go/plugins/compat_oai/openai): add dynamic model resolution

js/ai/src/document.ts, js/ai/src/generate/action.ts, js/ai/src/resource.ts, js/ai/tests/generate/generate_test.ts, js/ai/tests/resource/resource_test.ts, js/testapps/flow-simple-ai/src/index.ts
=> patch(#3133): added resource name, handle parent resources

js/plugins/compat-oai/src/audio.ts, js/plugins/compat-oai/src/image.ts, js/plugins/compat-oai/src/model.ts, js/testapps/compat-oai/src/index.ts
Also manually tested web search built in tool.
=> feat(js/plugins/compat-oai): Add `raw` field in responses, support config.tools

js/plugins/express/src/index.ts, js/plugins/express/tests/express_test.ts
=> feat(js/plugins/express): use connection close/timeout as abort signal for the action

js/plugins/next/src/client.ts, js/plugins/next/src/index.ts
=> feat(js/plugins/next): use request signal as abort signal for the action

go/plugins/googlegenai/models.go
- linking to an issue that includes more details [3142](https://github.com/firebase/genkit/issues/3142)
=> fix(go/plugins/googlegenai): Update gemini models

js/plugins/google-genai/src/googleai/client.ts, js/plugins/google-genai/src/googleai/embedder.ts, js/plugins/google-genai/src/googleai/index.ts, js/plugins/google-genai/src/index.ts, js/plugins/google-genai/src/vertexai/client.ts, js/plugins/google-genai/tests/googleai/client_test.ts, js/plugins/google-genai/tests/googleai/embedder_test.ts, js/plugins/google-genai/tests/googleai/index_test.ts, js/plugins/google-genai/tests/vertexai/client_test.ts
also fixed embedder and clients
=> feat(js/plugins/google-genai): Added GoogleAI index 

js/core/src/background-action.ts
=> fix(js): Export Operation type for use in dev UI

js/plugins/google-genai/src/googleai/gemini.ts, js/plugins/google-genai/src/googleai/index.ts, js/plugins/google-genai/tests/googleai/index_test.ts
=> feat(js/plugins/google-genai): Added Gemma Models to GoogleAI

js/plugins/google-genai/src/common/utils.ts, js/plugins/google-genai/src/googleai/gemini.ts, js/plugins/google-genai/src/googleai/index.ts, js/plugins/google-genai/src/vertexai/embedder.ts, js/plugins/google-genai/src/vertexai/gemini.ts, js/plugins/google-genai/src/vertexai/imagen.ts, js/plugins/google-genai/src/vertexai/index.ts, js/plugins/google-genai/src/vertexai/types.ts, js/plugins/google-genai/src/vertexai/utils.ts, js/plugins/google-genai/tests/common/utils_test.ts, js/plugins/google-genai/tests/vertexai/embedder_test.ts, js/plugins/google-genai/tests/vertexai/gemini_test.ts, js/plugins/google-genai/tests/vertexai/imagen_test.ts, js/plugins/google-genai/tests/vertexai/index_test.ts, js/plugins/google-genai/tests/vertexai/utils_test.ts
=> refactor(js/plugins/google-genai): Refactored vertexAI to match googleAI

js/plugins/mcp/README.md, js/testapps/mcp/src/server.ts
=> chore: updated mcp readme/samples

js/plugins/compat-oai/src/audio.ts, js/plugins/compat-oai/src/image.ts, js/plugins/compat-oai/src/model.ts, js/plugins/compat-oai/tests/compat_oai_test.ts, js/plugins/compat-oai/tests/openai_test.ts
=> feat(js/plugins/compat-oai): Support abortSignal

js/core/src/action.ts, js/core/tests/action_test.ts, js/plugins/googleai/src/gemini.ts, js/testapps/flow-simple-ai/src/index.ts
=> fix(js/plugins/gemini): correctly handle the model abort signal

js/plugins/compat-oai/src/audio.ts, js/plugins/compat-oai/src/deepseek/deepseek.ts, js/plugins/compat-oai/src/deepseek/index.ts, js/plugins/compat-oai/src/image.ts, js/plugins/compat-oai/src/model.ts, js/plugins/compat-oai/src/openai/dalle.ts, js/plugins/compat-oai/src/openai/gpt.ts, js/plugins/compat-oai/src/openai/index.ts, js/plugins/compat-oai/src/openai/tts.ts, js/plugins/compat-oai/src/openai/whisper.ts, js/plugins/compat-oai/src/xai/grok-image.ts, js/plugins/compat-oai/src/xai/grok.ts, js/plugins/compat-oai/src/xai/index.ts, js/plugins/compat-oai/tests/compat_oai_test.ts, js/testapps/compat-oai/src/index.ts
=> fix(js/plugins/compat-oai): Support custom config, with default model info

js/ai/src/generate.ts, js/ai/src/generate/action.ts, js/ai/src/index.ts, js/ai/src/model.ts, js/ai/tests/generate/generate_test.ts, js/ai/tests/model/model_test.ts, js/plugins/express/tests/express_test.ts, js/testapps/flow-simple-ai/src/index.ts
=> fix(js/ai): remove obsolete streaming callback ALS and correctly passthrought streaming callback from action

js/genkit/README.md, js/plugins/express/README.md, js/plugins/express/package.json, js/plugins/express/tests/express_test.ts, js/pnpm-lock.yaml
=> chore: minor updates to readmes and opportunistic package.json cleanup

js/plugins/google-genai/src/common/utils.ts, js/plugins/google-genai/src/googleai/client.ts, js/plugins/google-genai/src/googleai/embedder.ts, js/plugins/google-genai/src/googleai/gemini.ts, js/plugins/google-genai/src/googleai/imagen.ts, js/plugins/google-genai/src/googleai/utils.ts, js/plugins/google-genai/src/googleai/veo.ts, js/plugins/google-genai/src/vertexai/embedder.ts, js/plugins/google-genai/src/vertexai/gemini.ts, js/plugins/google-genai/src/vertexai/imagen.ts, js/plugins/google-genai/src/vertexai/utils.ts, js/plugins/google-genai/tests/common/utils_test.ts, js/plugins/google-genai/tests/vertexai/imagen_test.ts, js/plugins/google-genai/tests/vertexai/index_test.ts
=> fix(js/plugins/google-genai): Fixed imagen, veo, and streaming thoughts

README.md
=> fix: Update OpenAI links in README

genkit-tools/common/src/manager/manager.ts, genkit-tools/common/src/manager/types.ts, js/core/src/reflection.ts, js/genkit/src/genkit.ts, js/testapps/dev-ui-gallery/src/genkit.ts
Will be displayed in developer tooling
=> feat: add instance name to GenkitOptions

genkit-tools/common/src/types/apis.ts
=> fix(genkit-tools): ensure runtime is optional for listing actions

js/plugins/compat-oai/src/image.ts, js/plugins/compat-oai/src/openai/dalle.ts, js/plugins/compat-oai/src/openai/index.ts
=> fix(js/plugins/compat-oai): Fix gpt-image-1

js/plugins/google-genai/README.md, js/plugins/google-genai/src/common/utils.ts, js/plugins/google-genai/src/googleai/veo.ts, js/plugins/google-genai/src/vertexai/client.ts, js/plugins/google-genai/src/vertexai/utils.ts, js/plugins/google-genai/tests/vertexai/client_test.ts, js/plugins/google-genai/tests/vertexai/index_test.ts
Also added the README and new veo models.
=> fix(js/plugins/google-genai) Fix aggregation, supported tuned models

go/fix_genkit_init.sh
=> fix: failing checks

js/ai/src/embedder.ts, js/ai/src/model.ts, js/plugins/compat-oai/src/audio.ts, js/plugins/compat-oai/src/deepseek/deepseek.ts, js/plugins/compat-oai/src/image.ts, js/plugins/compat-oai/src/model.ts, js/plugins/compat-oai/src/openai/embedder.ts, js/plugins/compat-oai/src/openai/gpt.ts, js/plugins/compat-oai/src/openai/index.ts, js/plugins/compat-oai/src/xai/grok.ts, js/plugins/compat-oai/src/xai/index.ts, js/pnpm-lock.yaml, js/testapps/compat-oai/package.json, js/testapps/compat-oai/src/index.ts
=> fix(plugins/compat-oai): correctly set the namespace on modelRef

js/ai/src/retriever.ts, js/ai/tests/retriever/indexer_test.ts, js/ai/tests/retriever/retriever_test.ts
=> fix(js/ai): fixed action type typo in defineIndexer

js/plugins/google-genai/src/googleai/gemini.ts, samples/js-gemini/src/index.ts
=> chore(js/plugins/google-genai): add nano banana model

.github/workflows/go.yml
=> chore: bump node version in go presubmit gha

genkit-tools/cli/context/GENKIT.md, genkit-tools/cli/package.json
=> feat(genkit-tools/cli/ai-tools): Improve support for other model providers

go/genkit/genkit.go
=> chore(go): fixed godocs

genkit-tools/cli/context/GENKIT_GO.md
=> docs(go): created GENKIT_GO.md

go/ai/prompt.go, go/ai/prompt_test.go
=> fix(go/ai): added handling for `WithMessages()` in `Prompt.Execute()`

go/ai/document.go, go/ai/generate.go
=> feat(go): Added convenience `Interrupts()` method.

genkit-tools/cli/src/mcp/server.ts, genkit-tools/cli/src/mcp/usage.ts
=> feat(genkit-tools/mcp): Add new MCP tool to fetch usage guide

js/plugins/vertexai/src/embedder.ts, js/plugins/vertexai/src/evaluation/evaluation.ts, js/plugins/vertexai/src/evaluation/evaluator_factory.ts, js/plugins/vertexai/src/evaluation/index.ts, js/plugins/vertexai/src/gemini.ts, js/plugins/vertexai/src/imagen.ts, js/plugins/vertexai/src/index.ts, js/plugins/vertexai/src/modelgarden/anthropic.ts, js/plugins/vertexai/src/modelgarden/index.ts, js/plugins/vertexai/src/modelgarden/mistral.ts, js/plugins/vertexai/src/modelgarden/model_garden.ts, js/plugins/vertexai/src/modelgarden/openai_compatibility.ts, js/plugins/vertexai/src/rerankers/index.ts, js/plugins/vertexai/src/rerankers/reranker.ts
Reverts firebase/genkit#3487 The plugin does not work.
=> Revert "refactor(plugins/vertexai): migrate to v2 API"
